using System.Security.Cryptography;
using System.Text;
using System.Text.Json.Nodes;
using AeroLink.Domain.Baselines;
using AeroLink.Domain.ChangeControl;
using AeroLink.Domain.Identity;
using AeroLink.Domain.Traceability;
using AeroLink.Domain.Verification;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Infrastructure.Persistence;

/// <summary>
/// Completes the part of the software Case identity migration that cannot truthfully run in SQL: controlled
/// output bytes live in EvidenceFileStore, while the database stores only their immutable storage key/hash.
/// The migration records a durable Pending event; this authority must finish every rendition and signature
/// supersession before it records Completed. Any missing source bytes, renderer failure, or unresolved signed
/// identity throws and therefore fails startup closed instead of silently claiming a partial upgrade.
/// </summary>
public sealed class SoftwareVerificationCaseMigrationAuthority(
    AeroLinkDbContext db, ControlledOutputGenerator generator, EvidenceFileStore files)
{
    public const string MigrationMarker = "VerificationIdentityMigration.SoftwareCases.v1";
    private const string CompletedEvent = MigrationMarker + ".Completed";
    private const string Actor = "aerolink-migration";

    public async Task EnsureCompletedAsync(CancellationToken ct = default)
    {
        if (!db.Database.IsNpgsql()) return;
        if (await db.SecurityAuditEvents.AsNoTracking().AnyAsync(x => x.EventType == CompletedEvent
                && x.Target == "software-verification-identities", ct)) return;
        // A Pending event is the durable hand-off from SQL to this authority. It must be retried after a
        // renderer/storage failure; returning here would leave every upgraded database permanently pending.
        // The authority also tolerates a direct invocation before the SQL event exists, which is useful for
        // disposable qualification databases and keeps the completion check idempotent.

        var now = DateTimeOffset.UtcNow;
        await using var transaction = await db.Database.BeginTransactionAsync(ct);
        try
        {
            var documents = await db.ControlledDocuments
                .Where(x => x.Type == ControlledDocumentType.HighLevelTestCases
                    || x.Type == ControlledDocumentType.LowLevelTestCases)
                .OrderBy(x => x.Id).ToListAsync(ct);
            var artifacts = await db.ControlledDocumentArtifacts
                .Where(x => documents.Select(d => d.Id).Contains(x.DocumentId))
                .OrderBy(x => x.DocumentId).ThenBy(x => x.Format).ToListAsync(ct);
            var renditionByArtifactId = new Dictionary<Guid, (string OldHash, string NewHash)>();
            var renditionByDocumentId = new Dictionary<Guid, string>();
            var documentHashes = new Dictionary<Guid, List<(string Format, byte[] Content)>>();

            // The baseline manifest is part of the document's rendered content. Recompute it before assigning
            // each document's content basis and persist both values before the generator reads them through its
            // no-tracking queries. A document ContentHash is the controlled basis below, never a hash of the
            // generated bytes; each artifact owns that exact-byte SHA-256 separately.
            await RecomputeProcedureManifestsAsync(now, ct);
            // RecomputeProcedureManifestsAsync updates tracked baselines. Persist that new manifest before
            // the no-tracking lookup below; otherwise the document basis and the generated file would still
            // use the pre-rename hash even though the final database row claims the new one.
            await db.SaveChangesAsync(ct);
            foreach (var document in documents)
            {
                var manifestHash = await db.CandidateBaselines.AsNoTracking()
                    .Where(x => x.Id == document.BaselineId)
                    .Select(x => x.TestProceduresHash)
                    .SingleOrDefaultAsync(ct);
                if (string.IsNullOrWhiteSpace(manifestHash))
                    throw new InvalidOperationException($"Software Case migration cannot render document {document.Id} without a recomputed Case manifest hash.");
                var contentBasis = $"{manifestHash}|{document.Type}|{document.ArtifactCount}|{Actor}";
                var contentHash = Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(contentBasis))).ToLowerInvariant();
                document.RecordMigrationContentBasis(contentHash, now);
            }
            await db.SaveChangesAsync(ct);

            foreach (var artifact in artifacts)
            {
                ct.ThrowIfCancellationRequested();
                if (!files.Exists(artifact.StorageKey))
                    throw new InvalidOperationException($"Software Case migration cannot read stored rendition {artifact.Id} ({artifact.StorageKey}).");
                var oldHash = artifact.Sha256;
                var oldStorageKey = artifact.StorageKey;
                var output = await generator.GenerateAsync(artifact.DocumentId, artifact.Format, ct)
                    ?? throw new InvalidOperationException($"Software Case migration could not regenerate document {artifact.DocumentId} ({artifact.Format}).");
                await using var content = new MemoryStream(output.Content, writable: false);
                var stored = await files.StoreAsync(content, output.FileName, output.ContentType, ct);
                artifact.ReplaceMigrationRendition(stored.StorageKey, stored.OriginalFileName, stored.ContentType,
                    stored.Size, stored.Sha256, now);
                renditionByArtifactId[artifact.Id] = (oldHash, stored.Sha256);
                if (!documentHashes.TryGetValue(artifact.DocumentId, out var outputs))
                    documentHashes[artifact.DocumentId] = outputs = [];
                outputs.Add((artifact.Format, output.Content));
                db.SecurityAuditEvents.Add(new SecurityAuditEvent(
                    "VerificationIdentityMigration.DocumentRenditionRewritten", Actor,
                    $"ControlledDocumentArtifact:{artifact.Id}", "Succeeded",
                    Json(new
                    {
                        migration = MigrationMarker,
                        documentId = artifact.DocumentId,
                        format = artifact.Format,
                        oldStorageKey,
                        oldContentHash = oldHash,
                        newStorageKey = stored.StorageKey,
                        newContentHash = stored.Sha256,
                        reason = "Regenerated through ControlledOutputGenerator after structured Case identity migration."
                    }), "", now));
            }

            var reviewCycleRenditions = await RecomputeReviewCycleSnapshotsAsync(now, ct);
            foreach (var documentId in documentHashes.Keys)
            {
                var document = documents.Single(x => x.Id == documentId);
                renditionByDocumentId[documentId] = document.ContentHash;
            }
            var supersededSignatures = await CompleteSignatureSupersessionsAsync(
                renditionByArtifactId, renditionByDocumentId, reviewCycleRenditions, now, ct);

            db.SecurityAuditEvents.Add(new SecurityAuditEvent(
                CompletedEvent, Actor, "software-verification-identities", "Succeeded",
                Json(new
                {
                    migration = MigrationMarker,
                    renderedDocuments = documentHashes.Count,
                    renderedArtifacts = artifacts.Count,
                    reviewCyclesRewritten = reviewCycleRenditions.Count,
                    signaturesSuperseded = supersededSignatures,
                    systemPrefixPreserved = true,
                    forwardOnly = true,
                    reason = "All stored controlled renditions were regenerated and every superseded signature has a real replacement content hash."
                }), "", now));
            await db.SaveChangesAsync(ct);
            await transaction.CommitAsync(ct);
        }
        catch (Exception ex) when (ex is not OperationCanceledException)
        {
            throw new InvalidOperationException(
                "Software Case identity migration is incomplete; startup is fail-closed until stored renditions and signature evidence can be regenerated.", ex);
        }
    }

    private async Task<Dictionary<Guid, (Guid ReviewId, string OldHash, string NewHash)>> RecomputeReviewCycleSnapshotsAsync(
        DateTimeOffset now, CancellationToken ct)
    {
        var reviews = await db.TestChangeReviews
            .Include(x => x.ProcedureChanges).Include(x => x.AdditionalSources).Include(x => x.ReviewCycles)
            .Where(x => x.Discipline == TestChangeReviewDiscipline.HighLevelSoftware
                || x.Discipline == TestChangeReviewDiscipline.LowLevelSoftware)
            .ToListAsync(ct);
        if (reviews.Count == 0) return [];

        var reviewIds = reviews.Select(x => x.Id).ToList();
        var problemReports = await db.ProblemReportLinks.AsNoTracking()
            .Where(x => x.ArtifactType == "TestChangeRequest" && reviewIds.Contains(x.ArtifactId))
            .Select(x => new { x.ArtifactId, x.ProblemReportId }).ToListAsync(ct);
        var impactRows = await db.VerificationImpactItems.AsNoTracking()
            .Where(x => reviewIds.Contains(x.TestChangeReviewId)).ToListAsync(ct);
        var rewritten = new Dictionary<Guid, (Guid ReviewId, string OldHash, string NewHash)>();
        foreach (var review in reviews)
        {
            var problemReportIds = problemReports.Where(x => x.ArtifactId == review.Id)
                .Select(x => x.ProblemReportId).ToList();
            var impactDecisions = impactRows.Where(x => x.TestChangeReviewId == review.Id)
                .Select(x => new VerificationImpactSnapshot(
                    x.Id, x.ChangeRequestId, x.Trigger, x.RequirementChangeId, x.RequirementRevisionId,
                    x.ProcedureId, x.SubjectDisplayNumber, x.Outcome, x.ProcedureChangeAction,
                    x.ResolutionRationale, x.ResolvedProcedureId, x.ResolvedProcedureRevisionId,
                    x.RetargetedRequirementRevisionId, x.PreReleaseEvidenceRequired)).ToList();
            // Only the latest cycle of an open/approved package is reconstructible from the current aggregate.
            // Returned/cancelled earlier cycles may describe a body that was subsequently edited, so their
            // historical snapshot hashes remain immutable evidence rather than being guessed from today's body.
            var cycle = review.ReviewCycles.OrderBy(x => x.Sequence).LastOrDefault();
            if (cycle is null || review.State is not (TestChangeReviewState.InReview or TestChangeReviewState.Approved)
                || cycle.State is not (ReviewCycleState.Active or ReviewCycleState.Approved))
                continue;
            var replacementHash = review.ComputeSnapshotHashForIdentityMigration(problemReportIds, impactDecisions);
            if (string.Equals(cycle.SnapshotHash, replacementHash, StringComparison.OrdinalIgnoreCase)) continue;
            var oldHash = cycle.SnapshotHash;
            cycle.RecordVerificationIdentityMigration(replacementHash);
            rewritten[cycle.Id] = (review.Id, oldHash, replacementHash);
            db.SecurityAuditEvents.Add(new SecurityAuditEvent(
                "VerificationIdentityMigration.ReviewCycleSnapshotRewritten", Actor,
                $"ReviewCycle:{cycle.Id}", "Succeeded",
                Json(new
                {
                    migration = MigrationMarker,
                    reviewId = review.Id,
                    reviewCycleId = cycle.Id,
                    oldSnapshotHash = oldHash,
                    newSnapshotHash = replacementHash,
                    reason = "Recomputed through TestChangeReview canonical snapshot authority for the current immutable package cycle; prior cycles remain unchanged historical evidence."
                }), "", now));
        }
        return rewritten;
    }

    private async Task RecomputeProcedureManifestsAsync(DateTimeOffset now, CancellationToken ct)
    {
        var baselines = await db.CandidateBaselines
            .Where(x => x.TestProceduresMaterializedAt != null)
            .ToListAsync(ct);
        foreach (var baseline in baselines)
        {
            var entries = await (from member in db.BaselineTestProcedures.AsNoTracking()
                                  where member.BaselineId == baseline.Id
                                  join revision in db.TestProcedureRevisions.AsNoTracking()
                                      on member.RevisionId equals revision.Id
                                  join procedure in db.TestProcedures.AsNoTracking().Where(x => x.Level == TestProcedureLevel.System || x.ArtifactKind == VerificationArtifactKind.Case)
                                      on member.ProcedureId equals procedure.Id
                                  select new TestProcedureManifestEntry(procedure.Id, revision.Id,
                                      procedure.BaseNumber, revision.Revision)).ToListAsync(ct);
            baseline.RecordVerificationIdentityMigration(Actor, TestProcedureManifest.Hash(entries), now);
        }
    }

    private async Task<int> CompleteSignatureSupersessionsAsync(
        IReadOnlyDictionary<Guid, (string OldHash, string NewHash)> renditionByArtifactId,
        IReadOnlyDictionary<Guid, string> renditionByDocumentId,
        IReadOnlyDictionary<Guid, (Guid ReviewId, string OldHash, string NewHash)> reviewCycleRenditions,
        DateTimeOffset now, CancellationToken ct)
    {
        var pending = await db.SecurityAuditEvents
            .Where(x => x.EventType == "VerificationIdentityMigration.SignatureSuperseded")
            .ToListAsync(ct);
        var completed = 0;
        foreach (var evidence in pending)
        {
            var detail = JsonNode.Parse(evidence.Detail)?.AsObject()
                ?? throw new InvalidOperationException($"Signature migration evidence {evidence.Id} is not valid structured JSON.");
            var signatureId = ParseSignatureTarget(evidence.Target);
            var signature = await db.ElectronicSignatures.AsNoTracking()
                .SingleOrDefaultAsync(x => x.Id == signatureId, ct)
                ?? throw new InvalidOperationException($"Signature migration evidence {evidence.Id} has no source signature {signatureId}.");
            string replacementHash;
            var evidenceEventType = "VerificationIdentityMigration.SignatureSupersessionCompleted";
            var evidenceReason = "Stored controlled bytes were regenerated by the governed migration authority; the original human signature row and hash remain unchanged and require a new human signature.";
            if (signature.ArtifactType.Equals("TestChangeRequest", StringComparison.OrdinalIgnoreCase))
            {
                var review = await db.TestChangeReviews
                    .Include(x => x.ProcedureChanges).Include(x => x.AdditionalSources).Include(x => x.ReviewCycles)
                    .SingleOrDefaultAsync(x => x.Id == signature.ArtifactId, ct)
                    ?? throw new InvalidOperationException($"Signature {signature.Id} references missing TestChangeRequest {signature.ArtifactId}.");
                var problemReportIds = await db.ProblemReportLinks.AsNoTracking()
                    .Where(x => x.ArtifactType == "TestChangeRequest" && x.ArtifactId == review.Id)
                    .Select(x => x.ProblemReportId).ToListAsync(ct);
                var impactDecisions = await db.VerificationImpactItems.AsNoTracking()
                    .Where(x => x.TestChangeReviewId == review.Id)
                    .Select(x => new VerificationImpactSnapshot(
                        x.Id, x.ChangeRequestId, x.Trigger, x.RequirementChangeId, x.RequirementRevisionId,
                        x.ProcedureId, x.SubjectDisplayNumber, x.Outcome, x.ProcedureChangeAction,
                        x.ResolutionRationale, x.ResolvedProcedureId, x.ResolvedProcedureRevisionId,
                        x.RetargetedRequirementRevisionId, x.PreReleaseEvidenceRequired)).ToListAsync(ct);
                var cycle = review.ReviewCycles.OrderBy(x => x.Sequence).LastOrDefault()
                    ?? throw new InvalidOperationException($"Signature {signature.Id} references a TestChangeRequest with no review cycle.");
                // SQL selected only a signature whose old hash equals this latest active/approved
                // cycle. Earlier cycles may share that exact hash (the signed bytes are therefore the
                // same), so duplicate historical hashes are not an ambiguity and must not make startup
                // fail. A distinct old hash, however, proves that this signature is not the authority we
                // can rewrite and remains outside the pending set.
                var latestRenditionExists = reviewCycleRenditions.TryGetValue(cycle.Id, out var latestRendition);
                var latestHashMatches = string.Equals(cycle.SnapshotHash, signature.ContentHash, StringComparison.OrdinalIgnoreCase)
                    || latestRenditionExists
                        && string.Equals(latestRendition.OldHash, signature.ContentHash, StringComparison.OrdinalIgnoreCase);
                if (!latestHashMatches)
                    throw new InvalidOperationException($"Signature {signature.Id} does not match the latest reconstructible review-cycle snapshot.");
                if (signature.ReviewStepId is { } reviewStepId)
                {
                    var signedCycleId = await db.ApprovalSteps.AsNoTracking()
                        .Where(x => x.Id == reviewStepId)
                        .Select(x => (Guid?)x.ReviewCycleId)
                        .SingleOrDefaultAsync(ct);
                    if (signedCycleId is null)
                        throw new InvalidOperationException($"Signature {signature.Id} references missing approval step {reviewStepId}.");
                    var signedCycle = review.ReviewCycles.SingleOrDefault(x => x.Id == signedCycleId.Value)
                        ?? throw new InvalidOperationException($"Signature {signature.Id} approval step {reviewStepId} is not owned by its TestChangeRequest.");
                    var signedCycleHashMatches = string.Equals(signedCycle.SnapshotHash, signature.ContentHash, StringComparison.OrdinalIgnoreCase)
                        || signedCycle.Id == cycle.Id && latestRenditionExists
                            && string.Equals(latestRendition.OldHash, signature.ContentHash, StringComparison.OrdinalIgnoreCase);
                    if (!signedCycleHashMatches)
                        throw new InvalidOperationException($"Signature {signature.Id} approval step {reviewStepId} does not name the signed snapshot hash.");
                }
                if (!reviewCycleRenditions.TryGetValue(cycle.Id, out var cycleRendition))
                    throw new InvalidOperationException($"Signature {signature.Id} targets review cycle {cycle.Id}, whose renamed canonical snapshot cannot be reconstructed safely.");
                replacementHash = cycleRendition.NewHash;
                if (string.Equals(replacementHash, signature.ContentHash, StringComparison.OrdinalIgnoreCase))
                {
                    evidenceEventType = "VerificationIdentityMigration.SignatureHashVerified";
                    evidenceReason = "The canonical TestChangeRequest snapshot was recomputed through the same domain authority and remained byte-identical after the identity migration.";
                }
            }
            else if (signature.ArtifactType.Equals("ControlledDocumentArtifact", StringComparison.OrdinalIgnoreCase)
                && renditionByArtifactId.TryGetValue(signature.ArtifactId, out var artifactRendition))
                replacementHash = artifactRendition.NewHash;
            else if (signature.ArtifactType.Equals("ControlledDocument", StringComparison.OrdinalIgnoreCase)
                && renditionByDocumentId.TryGetValue(signature.ArtifactId, out var documentHash))
                replacementHash = documentHash;
            else
                throw new InvalidOperationException($"Signature {signature.Id} ({signature.ArtifactType}/{signature.ArtifactId}) has no exact controlled-output hash authority; migration remains pending.");

            // Audit history is append-only. The SQL-created Pending event remains the immutable statement of
            // what was superseded; this second event records the real governed replacement hash.
            db.SecurityAuditEvents.Add(new SecurityAuditEvent(
                evidenceEventType, Actor,
                evidence.Target, "Succeeded",
                Json(new
                {
                    migration = MigrationMarker,
                    pendingEvidenceId = evidence.Id,
                    signatureId = signature.Id,
                    oldArtifactIdentity = signature.ArtifactRevision,
                    oldSignatureHash = signature.ContentHash,
                    newArtifactIdentity = detail["newArtifactIdentity"]?.GetValue<string>(),
                    newContentHash = replacementHash,
                    reason = evidenceReason
                }), "", now));
            completed++;
        }
        return completed;
    }

    private static Guid ParseSignatureTarget(string target)
    {
        var value = target.StartsWith("ElectronicSignature:", StringComparison.Ordinal)
            ? target["ElectronicSignature:".Length..] : "";
        return Guid.TryParse(value, out var id) && id != Guid.Empty
            ? id
            : throw new InvalidOperationException($"Signature migration target '{target}' is not a valid ElectronicSignature identity.");
    }

    private static string Json(object value) => System.Text.Json.JsonSerializer.Serialize(value);
}
