using System.Text.Json;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Infrastructure.Persistence;

public sealed record GeneratedVariantPublication(GeneratedOutput Output,string SourceManifestJson,string SourceManifestHash,string TemplateManifestHash,string? PreviousManifestHash,int RequirementCount,int TraceCount,int TestCount);

public sealed class VariantPublicationGenerator(AeroLinkDbContext db,VariantConfigurationProjectionService projector)
{
    public async Task<GeneratedVariantPublication?> GenerateAsync(Guid variantBaselineId,Guid templateRevisionId,Guid? previousVariantBaselineId,string format,CancellationToken ct)
    {
        var projection=await projector.ProjectAsync(variantBaselineId,ct);if(projection is null)return null;var template=await db.DocumentTemplateRevisions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==templateRevisionId,ct);if(template is null)return null;var baseline=await db.ProductVariantBaselines.AsNoTracking().SingleAsync(x=>x.Id==variantBaselineId,ct);var variant=await db.ProductVariants.AsNoTracking().SingleAsync(x=>x.Id==baseline.VariantId,ct);var project=await db.Projects.AsNoTracking().SingleAsync(x=>x.Id==variant.ProjectId,ct);var program=await db.Programs.AsNoTracking().SingleAsync(x=>x.Id==project.ProgramId,ct);var previous=previousVariantBaselineId is null?null:await projector.ProjectAsync(previousVariantBaselineId.Value,ct);
        using var templateBody=JsonDocument.Parse(template.BodyJson);var titlePrefix=Read(templateBody.RootElement,"titlePrefix","Configured Product");var subtitle=Read(templateBody.RootElement,"subtitle","Exact configuration requirements, traceability, and verification evidence");var documentKind=template.TemplateKind;var sourceManifest=JsonSerializer.Serialize(new{format="AeroLink variant-publication-source/v1",projection.BaselineId,configurationManifestHash=projection.ManifestHash,templateRevisionId,template.Revision,templateManifestHash=template.ManifestHash,previousBaselineId=previous?.BaselineId,previousManifestHash=previous?.ManifestHash,requirements=projection.Requirements.Select(x=>new{x.Id,x.Source,hash=VariantConfigurationProjectionService.Hash(JsonSerializer.Serialize(x))}),traces=projection.Traces,tests=projection.Tests});var sourceHash=VariantConfigurationProjectionService.Hash(sourceManifest);
        var records=projection.Requirements.Select(requirement=>new PublicationRecord(requirement.Id,"Configured requirement",requirement.Source,requirement.Statement,new[]{("Verification",requirement.Verification),("Exact source",requirement.Source),("Trace links",projection.Traces.Count(x=>x.Source==requirement.Id||x.Target==requirement.Id).ToString()),("Verification artifacts",projection.Tests.Count(x=>x.Covers.Contains(requirement.Id,StringComparer.OrdinalIgnoreCase)).ToString())},requirement.RichContentJson)).ToList();var sections=new List<PublicationSection>{new("Configured Requirements",$"Exact content selected by {projection.VariantKey} configuration baseline revision {projection.Revision}.",records),new("Configuration-Correct Traceability","Every relationship resolves only between records present in this immutable configuration.",projection.Traces.Select(x=>new PublicationRecord(x.Source,x.Type,"Targets "+x.Target,$"{x.Source} {x.Type} {x.Target}",Array.Empty<(string,string)>())).ToList()),new("Configuration-Correct Verification","Verification artifacts and outcomes are projected from the same component and library revisions.",projection.Tests.Select(x=>new PublicationRecord(x.Id,"Verification artifact",x.Status,x.Title,new[]{("Covers",string.Join("; ",x.Covers)),("Status",x.Status)})).ToList())};
        if(previous is not null){var old=previous.Requirements.ToDictionary(x=>x.Id,StringComparer.OrdinalIgnoreCase);var current=projection.Requirements.ToDictionary(x=>x.Id,StringComparer.OrdinalIgnoreCase);var changes=current.Keys.Union(old.Keys,StringComparer.OrdinalIgnoreCase).OrderBy(x=>x).Select(id=>{var hasOld=old.TryGetValue(id,out var before);var hasNew=current.TryGetValue(id,out var after);var kind=!hasOld?"Introduced":!hasNew?"Retired":before!.Statement==after!.Statement&&before.RichContentJson==after.RichContentJson?"Unchanged":"Modified";return new PublicationRecord(id,kind,"Exact configuration redline",kind=="Modified"?$"OLD: {before!.Statement}\nNEW: {after!.Statement}":hasNew?after!.Statement:before!.Statement,new[]{("Previous configuration",previous.ManifestHash),("Current configuration",projection.ManifestHash)});}).Where(x=>x.Classification!="Unchanged").ToList();sections.Add(new("Exact Configuration Redline","Introduced, modified, and retired records between immutable variant baselines.",changes));}
        var generatedAt=baseline.CreatedAt>template.ApprovedAt?baseline.CreatedAt:template.ApprovedAt;
        var publication=new ProfessionalPublication(project.SoftwareProduct,program.Name+" ("+program.Code+")",project.Name,documentKind,$"{titlePrefix} — {projection.VariantName}",subtitle,$"{projection.VariantKey.Replace(".","")}-{documentKind.ToUpperInvariant()}","00","Controlled Configuration",projection.VariantKey,$"{projection.VariantKey} / Configuration {projection.Revision:D2}",template.ApprovedBy,generatedAt,sourceHash,new[]{("Variant manifest",projection.ManifestHash),("Template",$"{template.Organization} {template.TemplateKind} Rev {template.Revision:D2}"),("Template hash",template.ManifestHash),("Requirements",projection.Requirements.Count.ToString()),("Trace links",projection.Traces.Count.ToString()),("Verification artifacts",projection.Tests.Count.ToString())},Array.Empty<PublicationApproval>(),new[]{("00","Controlled Configuration",generatedAt.UtcDateTime.ToString("yyyy-MM-dd"),template.ApprovedBy)},sections);var output=ProfessionalPublicationRenderer.Render(publication,format,$"{projection.VariantKey}-configuration-r{projection.Revision:D2}");return new(output,sourceManifest,sourceHash,template.ManifestHash,previous?.ManifestHash,projection.Requirements.Count,projection.Traces.Count,projection.Tests.Count);
    }
    private static string Read(JsonElement root,string property,string fallback)=>root.TryGetProperty(property,out var value)&&value.ValueKind==JsonValueKind.String&&!string.IsNullOrWhiteSpace(value.GetString())?value.GetString()!:fallback;
}
