import { useEffect, useState } from 'react'
import './CommandPalette.css'

type Artifact={kind:string;id:string;identifier:string;title:string;state:string;subtitle:string;updatedAt?:string;details:Record<string,string|number|boolean|null>;related:{kind:string;id:string;identifier:string;title:string}[]}
export default function ArtifactRecordPage({api,kind,id,onBack,onOpen}:{api:string;kind:string;id:string;onBack:()=>void;onOpen:(kind:string,id:string)=>void}){
 const [artifact,setArtifact]=useState<Artifact>(),[status,setStatus]=useState<'loading'|'ready'|'missing'|'forbidden'|'error'>('loading'),[copied,setCopied]=useState(false)
 useEffect(()=>{setStatus('loading');fetch(`${api}/api/artifacts/${encodeURIComponent(kind)}/${id}`).then(async response=>{if(response.status===404){setStatus('missing');return}if(response.status===403){setStatus('forbidden');return}if(!response.ok){setStatus('error');return}setArtifact(await response.json());setStatus('ready')}).catch(()=>setStatus('error'))},[api,id,kind])
 if(status!=='ready'||!artifact)return <main className="artifactState"><div><span>{status==='forbidden'?'⊘':status==='missing'?'?':'!'}</span><h1>{status==='forbidden'?'Not authorized':status==='missing'?'Artifact not found':status==='loading'?'Opening controlled artifact…':'Artifact unavailable'}</h1><p>{status==='forbidden'?'Your session does not have authority to view this artifact.':status==='missing'?'The link may be stale, or the artifact no longer exists in this Program.':'AeroLink could not load this controlled record.'}</p><button onClick={onBack}>Return to Command Center</button></div></main>
 return <main className="artifactRecord"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">AUTHORITATIVE ARTIFACT / {artifact.kind.toUpperCase()}</p><h1>{artifact.identifier}</h1><p>{artifact.title}</p></div><div className="artifactActions"><span className={`stateBadge ${artifact.state.toLowerCase()}`}>{artifact.state}</span><button onClick={async()=>{await navigator.clipboard.writeText(location.href);setCopied(true);setTimeout(()=>setCopied(false),1800)}}>{copied?'Link copied':'Copy link'}</button></div></header><section className="artifactHero"><div><small>CONTROLLED IDENTITY</small><b>{artifact.identifier}</b><span>{artifact.subtitle}</span></div><div><small>LAST RECORDED CHANGE</small><b>{artifact.updatedAt?new Date(artifact.updatedAt).toLocaleString():'Immutable record'}</b><span>Server-authoritative lifecycle data</span></div></section><section className="artifactDetails"><h2>Record details</h2><dl>{Object.entries(artifact.details).map(([key,value])=><div key={key}><dt>{key.replace(/([A-Z])/g,' $1')}</dt><dd>{value===null||value===''?'—':String(value)}</dd></div>)}</dl></section>{artifact.related.length>0&&<section className="artifactRelated"><h2>Related controlled artifacts</h2>{artifact.related.map(item=><button key={`${item.kind}-${item.id}`} onClick={()=>onOpen(item.kind,item.id)}><i>{item.kind.slice(0,2).toUpperCase()}</i><span><b>{item.identifier}</b><small>{item.title}</small></span><em>Open →</em></button>)}</section>}</main>
}
