import { useCallback, useEffect, useState, type FormEvent } from 'react'
import { PersonName } from './People'
import './CodeTraceabilityCenter.css'

type Mapping={id:string;disposition:string;repositoryPath:string;mergeRequestReference:string;mergeRequestTitle:string;mergeRequestUrl:string;mergeCommitSha:string;mergedAt?:string;noCodeChangeRationale:string;isDemonstration:boolean;recordedBy:string;recordedAt:string}
type Requirement={artifactId:string;revisionId:string;displayNumber:string;statement:string;mapping?:Mapping}
type Overview={build:{version:string;readOnly:boolean};sourceOfTruth:string;demonstrationScope:boolean;summary:{required:number;mapped:number;missing:number;percent:number;gateComplete:boolean};requirements:Requirement[]}

export default function CodeTraceabilityCenter({api,projectId,releaseId,readOnly,onBack}:{api:string;projectId:string;releaseId:string;readOnly:boolean;onBack:()=>void}){
 const [overview,setOverview]=useState<Overview>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showForm,setShowForm]=useState(false)
 const [selected,setSelected]=useState(''),[disposition,setDisposition]=useState('GitLabMerge')
 const load=useCallback(async()=>{const response=await fetch(`${api}/api/code-traceability?projectId=${projectId}&releaseId=${releaseId}`);if(!response.ok){setError('Code traceability could not be loaded.');return}const body=await response.json();setOverview(body);setSelected(body.requirements.find((item:Requirement)=>!item.mapping)?.revisionId??'')},[api,projectId,releaseId])
 useEffect(()=>{void load()},[load])
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const requirement=overview?.requirements.find(item=>item.revisionId===selected);if(!requirement)return;const form=new FormData(event.currentTarget);setBusy(true);setError('');const response=await fetch(`${api}/api/code-traceability`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,releaseId,requirementArtifactId:requirement.artifactId,requirementRevisionId:requirement.revisionId,disposition,repositoryPath:form.get('repositoryPath'),mergeRequestReference:form.get('mergeRequestReference'),mergeRequestTitle:form.get('mergeRequestTitle'),mergeRequestUrl:form.get('mergeRequestUrl'),mergeCommitSha:form.get('mergeCommitSha'),mergedAt:form.get('mergedAt')?new Date(String(form.get('mergedAt'))).toISOString():null,noCodeChangeRationale:form.get('noCodeChangeRationale')})});setBusy(false);if(!response.ok){setError((await response.json()).error??'The code mapping could not be recorded.');return}setShowForm(false);await load()}
 const missing=overview?.requirements.filter(item=>!item.mapping)??[]
 return <main className="codeTracePage"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">SOFTWARE / CODE TRACEABILITY</p><h1>Code</h1><p>Exact approved LLR revisions mapped to the GitLab changes that implement them.</p></div>{!readOnly&&missing.length>0&&<button className="primaryAction" onClick={()=>setShowForm(true)}>+ Record code mapping</button>}</header>
  {error&&<div className="workspaceError" role="alert">{error}<button onClick={()=>setError('')}>Dismiss</button></div>}
  <section className="gitLabBoundary"><span>GL</span><div><b>GitLab is the source of truth</b><p>{overview?.sourceOfTruth}</p></div></section>
  {overview?.demonstrationScope&&<aside className="demoDataNotice"><b>Demonstration data</b><span>These example merge requests and commit SHAs illustrate the integration contract. They are not production GitLab records.</span></aside>}
  <section className={`codeGate ${overview?.summary.gateComplete?'complete':'open'}`}><div><small>RELEASE GATE · BUILD {overview?.build.version}</small><h2>{overview?.summary.mapped??0} of {overview?.summary.required??0} exact LLR revisions mapped</h2><p>{overview?.summary.gateComplete?'Code traceability is complete for this build scope.':`${overview?.summary.missing??0} LLR revision${overview?.summary.missing===1?'':'s'} still need a GitLab merge or a justified no-code decision.`}</p></div><strong>{overview?.summary.percent??0}%</strong></section>
  <section className="codeRecords"><div><h2>LLR-to-code evidence</h2><span>{readOnly?'Historical · read-only':'Active development'}</span></div>{overview?.requirements.map(requirement=><article key={requirement.revisionId} className={requirement.mapping?'mapped':'missing'}><header><div><b>{requirement.displayNumber}</b><p>{requirement.statement}</p></div><span>{requirement.mapping?requirement.mapping.disposition==='NoCodeChangeRequired'?'No code change required':'Mapped':'Missing'}</span></header>{requirement.mapping?.disposition==='GitLabMerge'?<div className="mergeEvidence"><div><small>GITLAB MERGE REQUEST</small><a href={requirement.mapping.mergeRequestUrl} target="_blank" rel="noreferrer">{requirement.mapping.mergeRequestReference} · {requirement.mapping.mergeRequestTitle} ↗</a><span>{requirement.mapping.repositoryPath}</span></div><div><small>IMMUTABLE MERGE COMMIT</small><code>{requirement.mapping.mergeCommitSha}</code><span>{requirement.mapping.mergedAt&&new Date(requirement.mapping.mergedAt).toLocaleString()}</span></div></div>:requirement.mapping?<p className="noCodeRationale">{requirement.mapping.noCodeChangeRationale}</p>:<p className="missingCallout">Record the implementing GitLab merge request, or explain why the exact approved LLR requires no code change.</p>}{requirement.mapping&&<footer>{requirement.mapping.isDemonstration&&<em>DEMO</em>}Recorded by <PersonName userName={requirement.mapping.recordedBy}/> · {new Date(requirement.mapping.recordedAt).toLocaleString()}</footer>}</article>)}</section>
  {showForm&&<div className="codeModal" role="dialog" aria-label="Record code mapping"><form onSubmit={save}><button type="button" className="close" aria-label="Close" onClick={()=>setShowForm(false)}>×</button><p className="eyebrow">EXACT LLR REVISION</p><h2>Record code traceability</h2><label>Approved LLR revision<select value={selected} onChange={event=>setSelected(event.target.value)}>{missing.map(item=><option value={item.revisionId} key={item.revisionId}>{item.displayNumber} · {item.statement}</option>)}</select></label><fieldset><legend>Disposition</legend><label><input type="radio" checked={disposition==='GitLabMerge'} onChange={()=>setDisposition('GitLabMerge')}/> GitLab merge</label><label><input type="radio" checked={disposition==='NoCodeChangeRequired'} onChange={()=>setDisposition('NoCodeChangeRequired')}/> No code change required</label></fieldset>{disposition==='GitLabMerge'?<><label>Repository path<input name="repositoryPath" placeholder="group/project" required/></label><label>Merge request reference<input name="mergeRequestReference" placeholder="!1842" required/></label><label>Merge request title<input name="mergeRequestTitle" required/></label><label>GitLab merge request URL<input name="mergeRequestUrl" type="url" placeholder="https://gitlab.example/group/project/-/merge_requests/1842" required/></label><label>Merge commit SHA<input name="mergeCommitSha" minLength={40} maxLength={64} required/></label><label>Merged at<input name="mergedAt" type="datetime-local" required/></label></>:<label>No-code rationale<textarea name="noCodeChangeRationale" required/></label>}<button className="primaryAction" disabled={busy||!selected}>Record immutable mapping</button></form></div>}
 </main>
}
