import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './ControlledAuthoringCenter.css'

type Release={id:string;version:string;isReleased:boolean}
type Requirement={id:string;displayNumber:string;baseNumber:string;level:string;revisionId:string;statement:string}
type ImpactItem={id:string;displayNumber?:string;buildNumber?:string;documentNumber?:string;title?:string;statement?:string;level?:string;state?:string;release?:string;baseline?:string;name?:string;type?:string}
type Impact={displayNumber:string;currentRevision:number;parents:ImpactItem[];children:ImpactItem[];tests:ImpactItem[];baselines:ImpactItem[];builds:ImpactItem[];documents:ImpactItem[];activeChanges:ImpactItem[];openComments:number;openAssignments:number;categories:{key:string;label:string;count:number;needsAction:boolean}[]}
type Assignment={id:string;assignedTo:string;title:string;description:string;dueAt?:string;state:string;createdBy:string;version:number;completedBy?:string}
type Collaboration={watching:boolean;watchers:{userName:string;isCurrent:boolean}[];assignments:Assignment[]}
type WorkQueue={assignments:{id:string;artifactId:string;requirement:string;title:string;description:string;dueAt?:string;version:number;overdue:boolean}[];notifications:{id:string;type:string;title:string;detail:string;route:string;artifactId?:string;createdAt:string}[]}
type Performance={totalRequirements:number;scaleTarget:number;allPassed:boolean;samples:{name:string;targetMs:number;p95Ms:number;passed:boolean;timings:number[]}[]}
type Interchange={mappings:{id:string;name:string;version:number;updatedAt:string}[];jobs:{id:string;fileName:string;sha256:string;validRows:number;invalidRows:number;state:string;createdBy:string;createdAt:string;createdScrId?:string}[]}
type Props={api:string;projectId:string;releases:Release[];requirement?:Requirement;onClose:()=>void;onOpenScr:(id:string)=>void;onChanged:()=>Promise<void>}

export default function ControlledAuthoringCenter({api,projectId,releases,requirement,onClose,onOpenScr,onChanged}:Props){
 const [tab,setTab]=useState<'impact'|'propose'|'collaboration'|'work'> (requirement?'impact':'work'),[impact,setImpact]=useState<Impact>(),[collaboration,setCollaboration]=useState<Collaboration>(),[queue,setQueue]=useState<WorkQueue>(),[performance,setPerformance]=useState<Performance>(),[interchange,setInterchange]=useState<Interchange>(),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const load=useCallback(async()=>{setError('');const requests:Promise<Response>[]=[fetch(`${api}/api/enterprise-requirements/work-queue?projectId=${projectId}`),fetch(`${api}/api/enterprise-requirements/performance?projectId=${projectId}`),fetch(`${api}/api/enterprise-requirements/interchange?projectId=${projectId}`)];if(requirement)requests.push(fetch(`${api}/api/enterprise-requirements/${requirement.id}/impact`),fetch(`${api}/api/enterprise-requirements/${requirement.id}/collaboration`));const results=await Promise.all(requests);if(results.some(x=>!x.ok)){setError('One or more controlled-work services could not be loaded.');return}setQueue(await results[0].json());setPerformance(await results[1].json());setInterchange(await results[2].json());if(requirement){setImpact(await results[3].json());setCollaboration(await results[4].json())}},[api,projectId,requirement])
 useEffect(()=>{load()},[load])
 const propose=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!requirement)return;const form=new FormData(e.currentTarget);setBusy(true);const response=await fetch(`${api}/api/enterprise-requirements/${requirement.id}/propose`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({targetReleaseId:form.get('targetReleaseId'),kind:form.get('kind'),title:form.get('title'),existingScrId:null})});setBusy(false);if(!response.ok){setError((await response.json()).error||'The proposal could not be created.');return}const result=await response.json();await onChanged();onOpenScr(result.id)}
 const toggleWatch=async()=>{if(!requirement)return;await fetch(`${api}/api/enterprise-requirements/${requirement.id}/watch`,{method:'POST'});await load()}
 const assign=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!requirement)return;const target=e.currentTarget;const form=new FormData(target);const date=String(form.get('dueAt')||'');setBusy(true);const response=await fetch(`${api}/api/enterprise-requirements/${requirement.id}/assignments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({assignedTo:form.get('assignedTo'),title:form.get('title'),description:form.get('description'),dueAt:date?new Date(`${date}T17:00:00`).toISOString():null,commentId:null})});setBusy(false);if(!response.ok){setError((await response.json()).error);return}target.reset();await load()}
 const complete=async(id:string,version:number)=>{const response=await fetch(`${api}/api/enterprise-requirements/assignments/${id}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:version})});if(!response.ok){setError((await response.json()).error);return}await load()}
 const markRead=async(id:string)=>{await fetch(`${api}/api/enterprise-requirements/notifications/${id}/read`,{method:'POST'});await load()}
 const openNotification=async(item:WorkQueue['notifications'][number])=>{await fetch(`${api}/api/enterprise-requirements/notifications/${item.id}/read`,{method:'POST'});if(item.route.startsWith('scr:')&&item.artifactId)onOpenScr(item.artifactId);else await load()}
 const collection=(title:string,items:ImpactItem[],empty:string)=><section className="impactCollection"><div><h3>{title}</h3><span>{items.length}</span></div>{items.length?items.slice(0,8).map((x,i)=><article key={x.id??i}><b>{x.displayNumber||x.buildNumber||x.documentNumber||x.title}</b><p>{x.statement||x.title||x.name||x.release}</p><small>{[x.level,x.state,x.type,x.baseline].filter(Boolean).join(' · ')}</small></article>):<p className="emptyImpact">{empty}</p>}</section>
 return <div className="controlCenterBackdrop"><section className="controlCenter"><header><div><p className="eyebrow">CONTROLLED AUTHORING / IMPACT INTELLIGENCE</p><h2>{requirement?requirement.displayNumber:'Engineering Work Center'}</h2><p>{requirement?requirement.statement:'Assignments, notifications, interchange operations, and measured repository health.'}</p></div><button aria-label="Close controlled authoring center" onClick={onClose}>×</button></header>{error&&<div className="workspaceError">{error}</div>}<nav>{requirement&&<><button className={tab==='impact'?'active':''} onClick={()=>setTab('impact')}>Impact analysis</button><button className={tab==='propose'?'active':''} onClick={()=>setTab('propose')}>Propose controlled change</button><button className={tab==='collaboration'?'active':''} onClick={()=>setTab('collaboration')}>Collaboration</button></>}<button className={tab==='work'?'active':''} onClick={()=>setTab('work')}>My work & operations</button></nav>
 {tab==='impact'&&impact&&<div className="centerBody"><div className="impactReadiness"><div><b>Change-impact readiness</b><p>Every category must receive an explicit disposition inside the SCR/SWCR before review.</p></div>{impact.categories.map(x=><article className={x.needsAction?'attention':'ready'} key={x.key}><i>{x.needsAction?'!':'✓'}</i><div><b>{x.label}</b><small>{x.count} affected record{x.count===1?'':'s'}</small></div></article>)}</div><div className="impactGrid">{collection('Parent requirements',impact.parents,'No parent trace is recorded; disposition is required.')}{collection('Child requirements',impact.children,'No derived children are currently linked.')}{collection('Verification procedures',impact.tests,'Coverage gap detected—assign additional test work.')}{collection('Baselines',impact.baselines,'Not present in a materialized baseline.')}{collection('Software builds',impact.builds,'No build currently contains this revision.')}{collection('Controlled documents',impact.documents,'No generated controlled output contains this revision.')}{collection('Active SCR/SWCR proposals',impact.activeChanges,'No other active change request proposes this requirement.')}</div></div>}
 {tab==='propose'&&requirement&&<div className="centerBody"><div className="authorityBoundary"><span>◆</span><div><b>SCR/SWCR remains the approval authority</b><p>This action creates a Draft change package and copies the current requirement into its proposed next revision. It does not modify the approved requirement.</p></div></div><form className="proposalForm" onSubmit={propose}><label>Change type<select name="kind"><option value="Modify">Modify requirement</option><option value="Retire">Retire requirement</option></select></label><label>Target release<select name="targetReleaseId" required>{releases.filter(x=>!x.isReleased).map(x=><option value={x.id} key={x.id}>{x.version}</option>)}</select></label><label className="wide">Change package title<input name="title" defaultValue={`Update ${requirement.displayNumber} through controlled impact analysis`} required/></label><div className="proposalPreview"><span>{requirement.displayNumber}</span><b>Current approved revision remains immutable</b><i>→</i><span>{requirement.baseNumber}.{String(Number(requirement.displayNumber.split('.').at(-1))+1).padStart(2,'0')}</span><b>Proposed revision inside Draft SCR/SWCR</b></div><button disabled={busy}>{busy?'Creating controlled package…':'Create Draft SCR/SWCR →'}</button></form></div>}
 {tab==='collaboration'&&requirement&&<div className="centerBody"><div className="collabSummary"><div><b>{collaboration?.watchers.length??0}</b><span>watchers</span></div><div><b>{collaboration?.assignments.filter(x=>x.state==='Open').length??0}</b><span>open assignments</span></div><button onClick={toggleWatch}>{collaboration?.watching?'Stop watching':'Watch requirement'}</button></div><div className="collabGrid"><section><h3>Assignments</h3>{collaboration?.assignments.map(x=><article className="assignmentCard" key={x.id}><div><b>{x.title}</b><i>{x.state}</i></div><p>{x.description}</p><small>{x.assignedTo}{x.dueAt?` · due ${new Date(x.dueAt).toLocaleDateString()}`:''}</small>{x.state==='Open'&&<button onClick={()=>complete(x.id,x.version)}>Complete</button>}</article>)}</section><form onSubmit={assign}><h3>Assign controlled follow-up</h3><label>Assignee username<input name="assignedTo" placeholder="Account username" required/></label><label>Title<input name="title" placeholder="Describe the required follow-up" required/></label><label>Description<textarea name="description" placeholder="Describe the exact work and expected outcome." required/></label><label>Due date<input name="dueAt" type="date"/></label><button disabled={busy}>Create assignment</button></form></div></div>}
 {tab==='work'&&<div className="centerBody"><div className="operationsHero"><div><span>Repository scale</span><b>{performance?.totalRequirements.toLocaleString()??'—'}</b><small>of {performance?.scaleTarget.toLocaleString()??'10,000'} qualification target</small></div><div><span>Performance gate</span><b className={performance?.allPassed?'gatePass':'gateWarn'}>{performance?.allPassed?'PASS':'CHECK'}</b><small>{performance?.samples.map(x=>`${x.name} ${x.p95Ms} ms`).join(' · ')}</small></div><div><span>Interchange history</span><b>{interchange?.jobs.length??0}</b><small>{interchange?.mappings.length??0} reusable mappings</small></div></div><div className="workGrid"><section><h3>My assignments</h3>{queue?.assignments.length?queue.assignments.map(x=><article className={x.overdue?'overdue':''} key={x.id}><div><b>{x.requirement}</b><i>{x.overdue?'Overdue':'Open'}</i></div><p>{x.title}</p><small>{x.dueAt?new Date(x.dueAt).toLocaleDateString():'No due date'}</small><button onClick={()=>complete(x.id,x.version)}>Complete</button></article>):<p className="emptyImpact">No open engineering assignments.</p>}</section><section><h3>Notifications</h3>{queue?.notifications.length?queue.notifications.map(x=><article key={x.id}><b>{x.title}</b><p>{x.detail}</p><small>{new Date(x.createdAt).toLocaleString()}</small><div><button onClick={()=>openNotification(x)}>Open exact artifact</button><button onClick={()=>markRead(x.id)}>Mark read</button></div></article>):<p className="emptyImpact">No unread notifications.</p>}</section><section><h3>Recent interchange jobs</h3>{interchange?.jobs.slice(0,8).map(x=><article key={x.id}><div><b>{x.fileName}</b><i>{x.state}</i></div><p>{x.validRows} valid · {x.invalidRows} invalid</p><small>{x.sha256.slice(0,18)}… · {x.createdBy}</small></article>)}</section></div></div>}
 </section></div>
}
