import {useCallback,useEffect,useState} from 'react'
import './EnterpriseLifecycleAssurance.css'

type ProductLine={components:{id:string;componentNumber:string;name:string;description:string;state:string;streamCount:number;revisionCount:number}[];variants:{id:string;variantKey:string;name:string;state:string;componentCount:number;baselineCount:number}[];streams:{id:string;componentId:string;streamKey:string;name:string;state:string;revisionCount:number}[];changeSets:{id:string;changeSetNumber:string;title:string;state:string;hasConflicts:boolean;updatedAt:string}[]}
type Operations={health:{database:string;integrity:string;openAlerts:number};qualification:{qualified:boolean;evidence?:{environment:string;requirementCount:number;concurrentUsers:number;durationMinutes:number;reportHash:string;executedAt:string}};restoreAssurance:{id:string;state:string;actualRpoMinutes:number;actualRtoMinutes:number;backupLocation:string;executedAt:string}[];retentionPolicies:{id:string;recordType:string;retentionDays:number;legalHold:boolean}[];upgradeEvidence:{id:string;state:string}[]}
type Metrics={contracts:{key:string;value:number;unit:string}[]}

export default function EnterpriseLifecycleAssurance({api,projectId,mode}:{api:string;projectId:string;mode:'configuration'|'assurance'}){
 const [productLine,setProductLine]=useState<ProductLine>(),[operations,setOperations]=useState<Operations>(),[metrics,setMetrics]=useState<Metrics>(),[error,setError]=useState('')
 const load=useCallback(async()=>{setError('');const [p,o,m]=await Promise.all([fetch(`${api}/api/product-line/overview?projectId=${projectId}`),fetch(`${api}/api/operations/overview?projectId=${projectId}`),fetch(`${api}/api/quality/metric-contracts?projectId=${projectId}`)]);if(p.ok)setProductLine(await p.json());if(o.ok)setOperations(await o.json());if(m.ok)setMetrics(await m.json());if(!p.ok||!o.ok||!m.ok)setError('Some lifecycle assurance evidence could not be loaded.')},[api,projectId])
 useEffect(()=>{load()},[load])
 if(error&&!productLine&&!operations)return <section className="assuranceEmpty"><b>Lifecycle assurance unavailable</b><p>{error}</p><button onClick={load}>Try again</button></section>
 if(mode==='configuration')return <section className="assurancePage"><header className="assuranceHero"><div><p>PRODUCT LINE / CONTROLLED REUSE</p><h2>Configuration intelligence</h2><span>Reusable components move through explicit streams, merges, approvals, applicability decisions, and immutable variant baselines.</span></div><b>{productLine?.variants.filter(x=>x.state==='Approved').length||0}<small>approved variants</small></b></header>
  <div className="assuranceMetrics"><article><span>Reusable components</span><b>{productLine?.components.length||0}</b><small>{productLine?.components.filter(x=>x.state==='Approved').length||0} approved libraries</small></article><article><span>Parallel streams</span><b>{productLine?.streams.length||0}</b><small>{productLine?.streams.reduce((n,x)=>n+x.revisionCount,0)||0} immutable revisions</small></article><article><span>Controlled merges</span><b>{productLine?.changeSets.length||0}</b><small>{productLine?.changeSets.filter(x=>x.hasConflicts).length||0} awaiting resolution</small></article><article><span>Frozen configurations</span><b>{productLine?.variants.reduce((n,x)=>n+x.baselineCount,0)||0}</b><small>reproducible manifests</small></article></div>
  <div className="configurationGrid"><section><div className="assuranceTitle"><div><h3>Reusable component library</h3><p>Approved content with independent development streams</p></div><i>CONTROLLED</i></div>{productLine?.components.length?productLine.components.map(component=><article className="componentCard" key={component.id}><div><i>{component.componentNumber.slice(0,2)}</i><div><b>{component.name}</b><span>{component.componentNumber} · {component.state}</span></div></div><p>{component.description||'Reusable controlled engineering content.'}</p><footer><span>{component.streamCount} streams</span><span>{component.revisionCount} revisions</span></footer></article>):<Empty title="No reusable components yet" text="Create the first controlled library component when reuse becomes part of this Program."/>}</section>
  <section><div className="assuranceTitle"><div><h3>Product configurations</h3><p>Applicability plus exact component revisions</p></div></div>{productLine?.variants.length?productLine.variants.map(variant=><article className="variantCard" key={variant.id}><header><div><b>{variant.name}</b><span>{variant.variantKey}</span></div><i>{variant.state}</i></header><div><strong>{variant.componentCount}</strong><span>selected components</span><strong>{variant.baselineCount}</strong><span>immutable baselines</span></div></article>):<Empty title="No variants configured" text="Variants will appear after applicability and controlled component selections are defined."/>}</section></div>
  <section className="changeSetLane"><div className="assuranceTitle"><div><h3>Merge and propagation decisions</h3><p>Every divergence is explicit; no reusable content silently moves between streams.</p></div></div>{productLine?.changeSets.length?<div>{productLine.changeSets.map(change=><article key={change.id}><i className={change.hasConflicts?'attention':'ok'}>{change.hasConflicts?'!':'✓'}</i><div><b>{change.changeSetNumber} · {change.title}</b><span>{change.state} · updated {new Date(change.updatedAt).toLocaleDateString()}</span></div></article>)}</div>:<Empty title="No open configuration decisions" text="Parallel stream comparisons and attributable resolutions will collect here."/>}</section></section>
 return <section className="assurancePage"><header className="assuranceHero operations"><div><p>OPERATIONS / RETAINED EVIDENCE</p><h2>Production assurance</h2><span>Targets are never shown as achievements. Qualification, restore, retention, upgrades, and alerts require attributable evidence.</span></div><b className={operations?.qualification.qualified?'passed':'pending'}>{operations?.qualification.qualified?'QUALIFIED':'NOT QUALIFIED'}<small>150 users / 50k requirements</small></b></header>
  <div className="assuranceMetrics">{metrics?.contracts.map(metric=><article key={metric.key}><span>{metric.key.replaceAll('_',' ')}</span><b>{metric.value.toLocaleString()}</b><small>{metric.unit} · permission scoped</small></article>)}</div>
  <div className="operationsGrid"><section><div className="assuranceTitle"><div><h3>Qualification evidence</h3><p>Production claim requires a retained run at both targets</p></div><i className={operations?.qualification.qualified?'good':'warn'}>{operations?.qualification.qualified?'PROVEN':'GAP'}</i></div>{operations?.qualification.evidence?<article className="evidenceCard"><b>{operations.qualification.evidence.environment}</b><div><strong>{operations.qualification.evidence.requirementCount.toLocaleString()}</strong><span>requirements</span><strong>{operations.qualification.evidence.concurrentUsers}</strong><span>concurrent users</span><strong>{operations.qualification.evidence.durationMinutes}</strong><span>minutes</span></div><code>{operations.qualification.evidence.reportHash}</code><small>{new Date(operations.qualification.evidence.executedAt).toLocaleString()}</small></article>:<Empty title="Production workload is not yet qualified" text="Run and retain a passing 150-user / 50,000-requirement test in production-like infrastructure."/>}</section>
  <section><div className="assuranceTitle"><div><h3>Restore assurance</h3><p>Off-device backup and isolated recovery proof</p></div></div>{operations?.restoreAssurance.length?operations.restoreAssurance.slice(0,3).map(drill=><article className="restoreRow" key={drill.id}><i className={drill.state==='Passed'?'ok':'attention'}>{drill.state==='Passed'?'✓':'!'}</i><div><b>{drill.backupLocation}</b><span>RPO {drill.actualRpoMinutes} min · RTO {drill.actualRtoMinutes} min</span><small>{new Date(drill.executedAt).toLocaleDateString()}</small></div></article>):<Empty title="No retained restore drill" text="Qualification remains incomplete until an isolated restore has measured RPO and RTO."/>}</section>
  <section><div className="assuranceTitle"><div><h3>Operational controls</h3><p>Live exceptions and policy posture</p></div></div><div className="controlRows"><article><b>Database</b><span>{operations?.health.database||'checking'}</span></article><article><b>Repository integrity</b><span>{operations?.health.integrity||'not checked'}</span></article><article><b>Open alerts</b><span className={operations?.health.openAlerts?'attention':''}>{operations?.health.openAlerts||0}</span></article><article><b>Retention policies</b><span>{operations?.retentionPolicies.length||0}</span></article><article><b>Upgrade evidence</b><span>{operations?.upgradeEvidence.length||0}</span></article></div></section></div></section>
}

function Empty({title,text}:{title:string;text:string}){return <div className="assuranceEmpty"><b>{title}</b><p>{text}</p></div>}
