import {useCallback,useEffect,useState} from 'react'
import { stateLabel } from './presentation'
import './EnterpriseLifecycleAssurance.css'

type ProductLine={components:{id:string;componentNumber:string;name:string;description:string;state:string;streamCount:number;revisionCount:number}[];variants:{id:string;variantKey:string;name:string;state:string;componentCount:number;baselineCount:number;latestBaseline?:{id:string;revision:number;manifestHash:string}}[];streams:{id:string;componentId:string;streamKey:string;name:string;state:string;revisionCount:number}[];changeSets:{id:string;changeSetNumber:string;title:string;state:string;hasConflicts:boolean;updatedAt:string}[]}
type Library={id:string;libraryNumber:string;name:string;description:string;state:string;revisions:{id:string;revision:number;manifestHash:string}[];reuses:{id:string;variantKey:string;mode:string;syncState:string;selectedRevisionId:string;latestUpstreamRevisionId:string;decisionRationale:string}[]}
type Template={id:string;templateNumber:string;title:string;state:string;approvedRevision:number;revisions:{id:string;revision:number;templateKind:string;organization:string;manifestHash:string}[]}
type RichBlock={type:string;text?:string;value?:string;label?:string;target?:string;dataUri?:string;alt?:string;caption?:string;rows?:string[][]}
type Projection={baselineId:string;variantKey:string;variantName:string;revision:number;manifestHash:string;components:unknown[];libraries:unknown[];requirements:{id:string;statement:string;verification:string;source:string;richContentJson:string}[];traces:unknown[];tests:unknown[];metrics:{requirements:number;traces:number;tests:number;coveragePercent:number;verificationPercent:number}}
type Operations={health:{database:string;integrity:string;openAlerts:number};qualification:{qualified:boolean;evidence?:{environment:string;requirementCount:number;concurrentUsers:number;durationMinutes:number;reportHash:string;executedAt:string}};restoreAssurance:{id:string;state:string;actualRpoMinutes:number;actualRtoMinutes:number;backupLocation:string;executedAt:string}[];retentionPolicies:{id:string;recordType:string;retentionDays:number;legalHold:boolean}[];upgradeEvidence:{id:string;state:string}[]}
type Metrics={contracts:{key:string;value:number;unit:string}[]}

export default function EnterpriseLifecycleAssurance({api,projectId,mode}:{api:string;projectId:string;mode:'configuration'|'assurance'}){
 const [productLine,setProductLine]=useState<ProductLine>(),[operations,setOperations]=useState<Operations>(),[metrics,setMetrics]=useState<Metrics>(),[libraries,setLibraries]=useState<Library[]>([]),[templates,setTemplates]=useState<Template[]>([]),[projection,setProjection]=useState<Projection>(),[selectedVariant,setSelectedVariant]=useState(''),[error,setError]=useState('')
 const load=useCallback(async()=>{setError('');const [p,o,m,l,t]=await Promise.all([fetch(`${api}/api/product-line/overview?projectId=${projectId}`),fetch(`${api}/api/operations/overview?projectId=${projectId}`),fetch(`${api}/api/quality/metric-contracts?projectId=${projectId}`),fetch(`${api}/api/product-line/libraries?projectId=${projectId}`),fetch(`${api}/api/publication-templates?projectId=${projectId}`)]);if(p.ok){const value=await p.json() as ProductLine;setProductLine(value);setSelectedVariant(current=>current||value.variants.at(-1)?.id||'')}if(o.ok)setOperations(await o.json());if(m.ok)setMetrics(await m.json());if(l.ok)setLibraries(await l.json());if(t.ok)setTemplates(await t.json());if(!p.ok||!o.ok||!m.ok||!l.ok||!t.ok)setError('Some lifecycle assurance evidence could not be loaded.')},[api,projectId])
 useEffect(()=>{load()},[load])
 useEffect(()=>{const baseline=productLine?.variants.find(x=>x.id===selectedVariant)?.latestBaseline?.id;if(!baseline){setProjection(undefined);return}fetch(`${api}/api/product-line/configurations/${baseline}`).then(async response=>{if(response.ok)setProjection(await response.json())})},[api,productLine,selectedVariant])
 if(error&&!productLine&&!operations)return <section className="assuranceEmpty"><b>Lifecycle assurance unavailable</b><p>{error}</p><button onClick={load}>Try again</button></section>
 if(mode==='configuration')return <ConfigurationView productLine={productLine} libraries={libraries} templates={templates} projection={projection} selectedVariant={selectedVariant} setSelectedVariant={setSelectedVariant}/>
 return <AssuranceView operations={operations} metrics={metrics}/>
}

function ConfigurationView({productLine,libraries,templates,projection,selectedVariant,setSelectedVariant}:{productLine?:ProductLine;libraries:Library[];templates:Template[];projection?:Projection;selectedVariant:string;setSelectedVariant:(id:string)=>void}){return <section className="assurancePage">
 <header className="assuranceHero"><div><p>PRODUCT LINE / CONTROLLED REUSE</p><h2>Configuration intelligence</h2><span>See exactly what ships in each product configuration, why reusable content differs, and which frozen evidence belongs to it.</span></div><b>{productLine?.variants.filter(x=>x.state==='Approved').length||0}<small>approved variants</small></b></header>
 <div className="configurationPicker"><div><span>INSPECT CONFIGURATION</span><div>{productLine?.variants.map(variant=><button className={variant.id===selectedVariant?'active':''} onClick={()=>setSelectedVariant(variant.id)} key={variant.id}><b>{variant.variantKey}</b><small>{variant.name}</small></button>)}</div></div>{projection&&<aside><span>FROZEN MANIFEST</span><b>Revision {projection.revision}</b><code>{projection.manifestHash.slice(0,16)}…</code></aside>}</div>
 <div className="assuranceMetrics"><article><span>Configured requirements</span><b>{projection?.metrics.requirements||0}</b><small>{projection?.metrics.coveragePercent||0}% verification coverage</small></article><article><span>Reusable libraries</span><b>{projection?.libraries.length||0}</b><small>{libraries.reduce((n,x)=>n+x.revisions.length,0)} immutable revisions</small></article><article><span>Trace relationships</span><b>{projection?.metrics.traces||0}</b><small>configuration-correct only</small></article><article><span>Controlled templates</span><b>{templates.filter(x=>x.state==='Approved').length}</b><small>approved organization formats</small></article></div>
 <div className="configurationGrid"><section><div className="assuranceTitle"><div><h3>Controlled reuse decisions</h3><p>One upstream revision, an explicit decision for every variant</p></div><i>ATTRIBUTABLE</i></div>{libraries.length?libraries.map(library=><article className="libraryCard" key={library.id}><header><div><b>{library.name}</b><span>{library.libraryNumber} · {stateLabel(library.state)}</span></div><strong>Rev {library.revisions[0]?.revision}</strong></header><p>{library.description}</p><div className="reuseDecisions">{library.reuses.map(reuse=><div key={reuse.id}><b>{reuse.variantKey}</b><span className={`reuseState ${reuse.syncState.toLowerCase()}`}>{reuse.syncState}</span><small>{reuse.decisionRationale}</small></div>)}</div></article>):<Empty title="No controlled libraries" text="Approved reusable requirements will appear here with variant-specific propagation decisions."/>}</section>
 <section><div className="assuranceTitle"><div><h3>Exact configuration</h3><p>Frozen components, libraries, tests, and template readiness</p></div></div>{projection?<div className="configurationSummary"><article><b>{projection.components.length}</b><span>component revisions</span></article><article><b>{projection.libraries.length}</b><span>library revisions</span></article><article><b>{projection.metrics.tests}</b><span>verification artifacts</span></article><article><b>{projection.metrics.verificationPercent}%</b><span>passing verification</span></article><footer><span>Publication-ready</span><b>{templates.some(x=>x.state==='Approved')?'YES':'NO'}</b></footer></div>:<Empty title="Choose a baselined configuration" text="The exact controlled projection appears after a product variant is frozen."/>}</section></div>
 <section className="configuredRequirements"><div className="assuranceTitle"><div><h3>Requirements in this configuration</h3><p>Authoritative content, trace context, and rich engineering detail from the selected immutable baseline</p></div><i>{projection?.variantKey||'SELECT'}</i></div>{projection?.requirements.length?projection.requirements.map(requirement=><details key={requirement.id} open={projection.requirements.length===1}><summary><div><code>{requirement.id}</code><b>{requirement.statement}</b></div><span>{requirement.source}</span></summary><div className="requirementDetail"><p><b>Verification</b>{requirement.verification}</p><RichContent json={requirement.richContentJson}/></div></details>):<Empty title="No requirements in this projection" text="Only requirements selected by the exact frozen component and library revisions are shown."/>}</section>
 <details className="componentDisclosure" open><summary><div><b>Reusable component streams</b><span>Inspect lower-level stream inventory and immutable revision counts</span></div><strong>{productLine?.components.length||0} COMPONENTS</strong></summary><div>{productLine?.components.map(component=><article className="componentCard" key={component.id}><div><i>{component.componentNumber.slice(0,2)}</i><div><b>{component.name}</b><span>{component.componentNumber} · {stateLabel(component.state)}</span></div></div><p>{component.description}</p><footer><span>{component.streamCount} streams</span><span>{component.revisionCount} revisions</span></footer></article>)}</div></details>
 <section className="changeSetLane"><div className="assuranceTitle"><div><h3>Merge and propagation decisions</h3><p>Parallel development remains visible without crowding the configuration inspection flow.</p></div></div>{productLine?.changeSets.length?<div>{productLine.changeSets.map(change=><article key={change.id}><i className={change.hasConflicts?'attention':'ok'}>{change.hasConflicts?'!':'✓'}</i><div><b>{change.changeSetNumber} · {change.title}</b><span>{stateLabel(change.state)} · updated {new Date(change.updatedAt).toLocaleDateString()}</span></div></article>)}</div>:<Empty title="No open configuration decisions" text="Parallel stream comparisons and attributable resolutions will collect here."/>}</section>
 </section>}

function AssuranceView({operations,metrics}:{operations?:Operations;metrics?:Metrics}){return <section className="assurancePage"><header className="assuranceHero operations"><div><p>OPERATIONS / RETAINED EVIDENCE</p><h2>Production assurance</h2><span>Targets are never shown as achievements. Workload scale, restore, retention, upgrades and alerts require attributable evidence. Nothing on this page is a tool-qualification or certification claim.</span></div><b className={operations?.qualification.qualified?'passed':'pending'}>{operations?.qualification.qualified?'WORKLOAD TARGET MET':'WORKLOAD TARGET NOT MET'}<small>Target · 150 concurrent users, 50,000 requirements</small></b></header>
 <div className="assuranceMetrics">{metrics?.contracts.map(metric=><article key={metric.key}><span>{metric.key.replaceAll('_',' ')}</span><b>{metric.value.toLocaleString()}</b><small>{metric.unit} · permission scoped</small></article>)}</div>
 <div className="operationsGrid"><section><div className="assuranceTitle"><div><h3>Workload qualification evidence</h3><p>A workload claim requires a retained run at both targets</p></div><i className={operations?.qualification.qualified?'good':'warn'}>{operations?.qualification.qualified?'PROVEN':'GAP'}</i></div>{operations?.qualification.evidence?<article className="evidenceCard"><b>{operations.qualification.evidence.environment}</b><div><strong>{operations.qualification.evidence.requirementCount.toLocaleString()}</strong><span>requirements</span><strong>{operations.qualification.evidence.concurrentUsers}</strong><span>concurrent users</span><strong>{operations.qualification.evidence.durationMinutes}</strong><span>minutes</span></div><code>{operations.qualification.evidence.reportHash}</code><small>{new Date(operations.qualification.evidence.executedAt).toLocaleString()}</small></article>:<Empty title="Production workload is not yet qualified" text="Run and retain a passing 150-user / 50,000-requirement test in production-like infrastructure."/>}</section>
 <section><div className="assuranceTitle"><div><h3>Restore assurance</h3><p>Off-device backup and isolated recovery proof</p></div></div>{operations?.restoreAssurance.length?operations.restoreAssurance.slice(0,3).map(drill=><article className="restoreRow" key={drill.id}><i className={drill.state==='Passed'?'ok':'attention'}>{drill.state==='Passed'?'✓':'!'}</i><div><b>{drill.backupLocation}</b><span>RPO {drill.actualRpoMinutes} min · RTO {drill.actualRtoMinutes} min</span><small>{new Date(drill.executedAt).toLocaleDateString()}</small></div></article>):<Empty title="No retained restore drill" text="Restore assurance remains incomplete until an isolated restore has measured RPO and RTO."/>}</section>
 <section><div className="assuranceTitle"><div><h3>Operational controls</h3><p>Live exceptions and policy posture</p></div></div><div className="controlRows"><article><b>Database</b><span>{operations?.health.database||'checking'}</span></article><article><b>Repository integrity</b><span>{operations?.health.integrity||'not checked'}</span></article><article><b>Open alerts</b><span className={operations?.health.openAlerts?'attention':''}>{operations?.health.openAlerts||0}</span></article><article><b>Retention policies</b><span>{operations?.retentionPolicies.length||0}</span></article><article><b>Upgrade evidence</b><span>{operations?.upgradeEvidence.length||0}</span></article></div></section></div></section>}

function Empty({title,text}:{title:string;text:string}){return <div className="assuranceEmpty"><b>{title}</b><p>{text}</p></div>}
function RichContent({json}:{json:string}){let blocks:RichBlock[]=[];try{blocks=(JSON.parse(json).blocks||[]) as RichBlock[]}catch{return null}return <div className="richEngineeringContent">{blocks.map((block,index)=>{if(block.type==='paragraph')return <p key={index}>{block.text}</p>;if(block.type==='symbol')return <blockquote key={index}><span>CONTROLLED SYMBOL</span><b>{block.value}</b></blockquote>;if(block.type==='reference')return <a key={index} href={`#${block.target}`}>{block.label}<small>{block.target}</small></a>;if(block.type==='image')return <figure key={index}><img src={block.dataUri} alt={block.alt}/><figcaption>{block.caption||block.alt}</figcaption></figure>;if(block.type==='table')return <table key={index}><tbody>{block.rows?.map((row,r)=><tr key={r}>{row.map((cell,c)=>r===0?<th key={c}>{cell}</th>:<td key={c}>{cell}</td>)}</tr>)}</tbody></table>;return null})}</div>}
