import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './IdentityCenter.css'
import './IdentitySetup.css'

export type AuthUser={id:string;userName:string;displayName:string;email:string;isAdministrator:boolean;programs:{programId:string;roles:string[]}[]}
export function LoginPage({api,onLogin}:{api:string;onLogin:(user:AuthUser)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[setupComplete,setSetupComplete]=useState(false)
 const [setup,setSetup]=useState<{bootstrapRequired:boolean;bootstrapEnabled:boolean}>()
 useEffect(()=>{let active=true;fetch(`${api}/api/setup/status`).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(status=>{if(active)setSetup(status)}).catch(()=>{if(active)setSetup({bootstrapRequired:false,bootstrapEnabled:false})});return()=>{active=false}},[api])
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const response=await fetch(`${api}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userName:f.get('userName'),password:f.get('password')})});if(!response.ok){let message='The username or password was not accepted.';try{const body=await response.json();if(body?.error)message=body.error}catch{/* Preserve the safe fallback when the server returns no JSON. */}setError(message);return}onLogin(await response.json())}catch{setError('AeroLink could not reach its local API. Run START_AEROLINK.bat, then try again.')}finally{setBusy(false)}}
 const bootstrap=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget),password=String(f.get('password')??'');if(password!==f.get('confirmation')){setError('The administrator passwords do not match.');setBusy(false);return}try{const response=await fetch(`${api}/api/setup/bootstrap`,{method:'POST',headers:{'Content-Type':'application/json','X-AeroLink-Bootstrap-Secret':String(f.get('secret')??'')},body:JSON.stringify({displayName:f.get('displayName'),email:f.get('email'),password})});if(!response.ok){const body=await response.json().catch(()=>({}));setError(body.error||'The administrator could not be created.');return}setSetup({bootstrapRequired:false,bootstrapEnabled:false});setSetupComplete(true)}catch{setError('AeroLink could not reach its setup service. Verify the API and try again.')}finally{setBusy(false)}}
 const signIn=<form onSubmit={submit}><div className="securityMark">◈</div><h2>{setupComplete?'Administrator created':'Welcome back'}</h2><p>{setupComplete?'First-install setup is closed. Sign in with the new admin account.':'Sign in to your on-premises AeroLink workspace.'}</p>{setupComplete&&<div className="setupSuccess" role="status">✓ The one-time administrator bootstrap completed successfully.</div>}<label>Username<input name="userName" autoComplete="username" required autoFocus/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div className="loginError">{error}</div>}<button disabled={busy}>{busy?'Authenticating…':'Sign in securely →'}</button><aside><b>Controlled access</b><span>Use the account issued by your workspace administrator.</span><small>Credentials are authenticated locally and are never sent outside this deployment.</small></aside></form>
 const setupPanel=setup?.bootstrapRequired?(setup.bootstrapEnabled?<form className="bootstrapForm" onSubmit={bootstrap}><div className="securityMark">◇</div><p className="eyebrow">ONE-TIME SECURE ACTIVATION</p><h2>Create the global administrator</h2><p>This empty deployment accepts exactly one bootstrap. After it succeeds, this setup path closes permanently.</p><label>Bootstrap secret<input name="secret" type="password" autoComplete="off" required autoFocus/></label><label>Administrator username<input value="admin" readOnly aria-readonly="true"/></label><label>Display name<input name="displayName" autoComplete="name" required/></label><label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" autoComplete="new-password" minLength={14} required/><small>At least 14 characters with uppercase, lowercase, a number, and a symbol.</small></label><label>Confirm password<input name="confirmation" type="password" autoComplete="new-password" minLength={14} required/></label>{error&&<div className="loginError">{error}</div>}<button disabled={busy}>{busy?'Creating administrator…':'Activate controlled workspace →'}</button><aside><b>One-way setup boundary</b><span>The secret is checked in constant time and never stored in the database.</span><small>Remove the bootstrap secret from service configuration immediately after activation.</small></aside></form>:<div className="setupBlocked"><div className="securityMark">◇</div><p className="eyebrow">ACTIVATION REQUIRED</p><h2>Protected setup is not enabled</h2><p>This deployment has no accounts. An operator must set <code>Identity__BootstrapSecret</code> to a protected random value of at least 32 characters, restart the API, then refresh this page.</p><aside><b>Fail-closed by design</b><span>No default administrator or known production password was created.</span><small>See the Operations guide for the approved first-install sequence.</small></aside></div>):signIn
 return <main className="loginPage"><section className="loginStory"><div className="loginBrand"><span>▲</span>AeroLink</div><div><p className="eyebrow">DEVELOPMENT ASSURANCE · CONTROLLED ACCESS</p><h1>Every decision.<br/>Every revision.<br/><em>Accountable.</em></h1><p>A secure engineering workspace for requirements, verification evidence, baselines, and release authority.</p></div><div className="trustStrip"><span>IMMUTABLE HISTORY</span><span>PROGRAM-SCOPED ROLES</span><span>ELECTRONIC SIGNATURES</span></div></section><section className="loginPanel">{setup?setupPanel:<div className="setupChecking" role="status"><div className="securityMark">◈</div><h2>Checking workspace security</h2><p>Resolving the controlled sign-in boundary…</p></div>}</section></main>
}

type WorkTask={id:string;type:string;artifact:string;title:string;priority:string;dueAt:string;ageDays:number;route:string}
export function MyWorkCenter({api,projectId,user,onBack,onOpenScr,onOpenRelease}:{api:string;projectId:string;user:AuthUser;onBack:()=>void;onOpenScr:(id:string)=>void;onOpenRelease:()=>void}){
 const [data,setData]=useState<{generatedAt:string;summary:{total:number;approvals:number;overdue:number;drafts:number};tasks:WorkTask[]}>()
 useEffect(()=>{fetch(`${api}/api/my-work?projectId=${projectId}`).then(x=>x.json()).then(setData)},[api,projectId])
 return <main className="identityPage"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">PERSONAL WORKSPACE / {user.userName.toUpperCase()}</p><h1>My Work</h1><p>One accountable queue for reviews, signatures, drafts, and release decisions.</p></div><div className="identityBadge"><span>{user.displayName.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{user.displayName}</b><small>Authenticated · secure session</small></div></div></header>{data&&<><section className="workMetrics">{[['Assigned to me',data.summary.total],['Awaiting signature',data.summary.approvals],['Overdue',data.summary.overdue],['Drafts I own',data.summary.drafts]].map(([x,n],i)=><article className={i===2&&Number(n)>0?'urgent':''} key={String(x)}><span>{x}</span><b>{n}</b><small>{i===2?'Requires immediate attention':'Current program scope'}</small></article>)}</section><section className="workQueue"><div className="queueTitle"><div><h2>Priority queue</h2><p>Ordered by formal authority and due date</p></div><span>LIVE · {new Date(data.generatedAt).toLocaleTimeString()}</span></div>{data.tasks.length?data.tasks.map(task=><article key={`${task.type}-${task.id}`} onClick={()=>task.route==='scr'?onOpenScr(task.id):onOpenRelease()}><i className={task.priority.toLowerCase()}>{task.priority}</i><div><span>{task.type}</span><b>{task.artifact} · {task.title}</b><small>Assigned {task.ageDays} day{task.ageDays===1?'':'s'} ago · due {new Date(task.dueAt).toLocaleDateString()}</small></div><button>Open work item →</button></article>):<div className="workZero"><span>✓</span><h3>You are caught up</h3><p>No controlled work is awaiting your action in this program.</p></div>}</section></>}</main>
}

type AdminUser={id:string;userName:string;displayName:string;email:string;state:string;lastLoginAt?:string;memberships:{programId:string;role:string}[]}
export function AdministrationCenter({api,programId,onBack}:{api:string;programId:string;onBack:()=>void}){
 const [users,setUsers]=useState<AdminUser[]>([]),[selected,setSelected]=useState<AdminUser>(),[error,setError]=useState('')
 const load=useCallback(()=>fetch(`${api}/api/admin/users`).then(async x=>{if(!x.ok)throw new Error('Administrator access required.');setUsers(await x.json())}).catch(x=>setError(x.message)),[api]);useEffect(()=>{load()},[load])
 const setState=async(user:AdminUser)=>{await fetch(`${api}/api/admin/users/${user.id}/state`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:user.state!=='Active'})});await load()}
 const grant=async(role:string)=>{if(!selected)return;await fetch(`${api}/api/admin/users/${selected.id}/memberships`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({programId,role})});await load();setSelected(undefined)}
 return <main className="identityPage"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">ENTERPRISE CONTROL / IDENTITY & ACCESS</p><h1>People & Authority</h1><p>Manage accounts, program roles, access state, and accountable authority.</p></div><button className="primaryAction" onClick={()=>setSelected({id:'',userName:'',displayName:'',email:'',state:'New',memberships:[]})}>+ Create account</button></header>{error&&<div className="loginError">{error}</div>}<section className="adminSummary"><article><b>{users.filter(x=>x.state==='Active').length}</b><span>Active accounts</span></article><article><b>{users.filter(x=>x.memberships.some(m=>m.role==='Approver')).length}</b><span>Authorized approvers</span></article><article><b>{users.filter(x=>x.state!=='Active').length}</b><span>Disabled or locked</span></article><article><b>{users.reduce((n,x)=>n+x.memberships.length,0)}</b><span>Role assignments</span></article></section><section className="userTable"><div className="userHead"><span>PERSON</span><span>PROGRAM AUTHORITY</span><span>LAST ACCESS</span><span>STATE</span><span/></div>{users.map(user=><article key={user.id}><div className="person"><i>{user.displayName.split(' ').map(x=>x[0]).join('').slice(0,2)}</i><div><b>{user.displayName}</b><small>{user.userName} · {user.email}</small></div></div><div className="roleCloud">{user.memberships.filter(x=>x.programId===programId).map(x=><span key={x.role}>{x.role}</span>)}</div><time>{user.lastLoginAt?new Date(user.lastLoginAt).toLocaleString():'Never'}</time><strong className={user.state.toLowerCase()}>{user.state}</strong><div><button onClick={()=>setSelected(user)}>Manage roles</button><button className="quiet" onClick={()=>setState(user)}>{user.state==='Active'?'Disable':'Enable'}</button></div></article>)}</section>{selected&&<div className="identityModal"><div>{selected.id?<><p className="eyebrow">PROGRAM AUTHORITY</p><h2>{selected.displayName}</h2><p>Grant an additional role for this program. Existing role history remains retained.</p><div className="rolePicker">{['Engineer','Reviewer','Approver','ConfigurationManager','TestEngineer','ProgramManager','Administrator'].map(x=><button onClick={()=>grant(x)} key={x}>{x}</button>)}</div></>:<CreateAccount api={api} onDone={()=>{setSelected(undefined);load()}}/>}<button className="cancel" onClick={()=>setSelected(undefined)}>Cancel</button></div></div>}</main>
}
function CreateAccount({api,onDone}:{api:string;onDone:()=>void}){const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const r=await fetch(`${api}/api/admin/users`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(f))});if(!r.ok){setError((await r.json()).error);return}onDone()};return <form className="accountForm" onSubmit={submit}><p className="eyebrow">NEW CONTROLLED IDENTITY</p><h2>Create account</h2><label>Username<input name="userName" required/></label><label>Display name<input name="displayName" required/></label><label>Email<input name="email" type="email" required/></label><label>Temporary password<input name="temporaryPassword" type="password" minLength={10} required/></label>{error&&<div className="loginError">{error}</div>}<button>Create secure account</button></form>}

export function SignatureDialog({title,meaning,onCancel,onSign}:{title:string;meaning:string;onCancel:()=>void;onSign:(password:string,meaning:string)=>Promise<void>}){const [password,setPassword]=useState(''),[busy,setBusy]=useState(false);return <div className="identityModal signatureModal"><div><div className="signatureSeal">✓</div><p className="eyebrow">ELECTRONIC SIGNATURE</p><h2>{title}</h2><p>By signing, you confirm that you reviewed the exact controlled snapshot and accept the stated approval meaning. Your identity, time, content hash, and decision will be permanently recorded.</p><label>Signature meaning<textarea value={meaning} readOnly/></label><label>Re-enter your password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoFocus/></label><div className="signatureActions"><button className="cancel" onClick={onCancel}>Cancel</button><button disabled={password.length<1||busy} onClick={async()=>{setBusy(true);await onSign(password,meaning);setBusy(false)}}>{busy?'Signing…':'Sign & approve'}</button></div></div></div>}
