import { useCallback, useEffect, useState } from "react";
import { stateLabel } from './presentation'
import type { FormEvent } from "react";
import "./IntegrationCommandCenter.css";
import ReqIfExchangeCenter from "./ReqIfExchangeCenter";
import JiraConnectorPanel from "./JiraConnectorPanel";

type Overview={generatedAt:string;api:{version:string;basePath:string;status:string;capabilities:string[]};metrics:{activeIdentities:number;enabledWebhooks:number;events24h:number;deliverySuccess:number;deadLetters:number};identities:{id:string;name:string;clientId:string;scopes:string[];state:string;createdAt:string;createdBy:string;lastUsedAt?:string;revokedAt?:string}[];webhooks:{id:string;name:string;endpointUrl:string;eventTypes:string[];isEnabled:boolean;createdAt:string;updatedAt:string}[];events:{id:string;eventType:string;aggregateType:string;actor:string;occurredAt:string;state:string;deliveryCount:number}[];deliveries:{id:string;integrationEventId:string;subscriptionId:string;state:string;attemptCount:number;nextAttemptAt:string;responseStatusCode?:number;lastError?:string;createdAt:string;deliveredAt?:string}[];interchange:{id:string;fileName:string;state:string;validRows:number;invalidRows:number;createdAt:string;completedAt?:string}[]};
type Reveal={title:string;value:string;detail:string};

const time=(value?:string)=>value?new Date(value).toLocaleString():"Never";
const short=(value:string)=>value.length>44?`${value.slice(0,41)}…`:value;

export default function IntegrationCommandCenter({api,projectId,releaseId,onBack}:{api:string;projectId:string;releaseId:string;onBack:()=>void}){
 const [data,setData]=useState<Overview>();const [error,setError]=useState("");const [busy,setBusy]=useState("");const [panel,setPanel]=useState<"identity"|"webhook">();const [reveal,setReveal]=useState<Reveal>();
 const load=useCallback(async()=>{try{const response=await fetch(`${api}/api/integrations/overview?projectId=${projectId}`);if(!response.ok)throw new Error("Integration telemetry is unavailable.");setData(await response.json());setError("")}catch(e){setError((e as Error).message)}},[api,projectId]);
 useEffect(()=>{load();const timer=setInterval(load,5000);return()=>clearInterval(timer)},[load]);
 const mutate=async(url:string,init:RequestInit,label:string)=>{setBusy(label);setError("");try{const response=await fetch(`${api}${url}`,init);if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.error||`${label} failed.`)}await load();return response}catch(e){setError((e as Error).message);return undefined}finally{setBusy("")}};
 const createIdentity=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const response=await mutate("/api/integrations/service-identities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,name:form.get("name"),scopes:form.getAll("scopes")})},"Creating machine identity");if(response){const item=await response.json();setReveal({title:"Machine identity created",value:item.apiKey,detail:"Copy this key into the calling system now. AeroLink stores only its SHA-256 hash."});setPanel(undefined)}};
 const createWebhook=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);const response=await mutate("/api/integrations/webhooks",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,name:form.get("name"),endpointUrl:form.get("endpointUrl"),eventTypes:String(form.get("eventTypes")||"").split(",").map(x=>x.trim()).filter(Boolean)})},"Creating webhook");if(response){const item=await response.json();setReveal({title:"Webhook signing secret",value:item.signingSecret,detail:"Use this secret to verify X-AeroLink-Signature. It is encrypted at rest and will not be displayed again."});setPanel(undefined)}};
 const sendTest=()=>mutate("/api/integrations/events/test",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,message:"Integration Command Center signed-delivery test"})},"Publishing test event");
 if(!data)return <main className="integrationCenter"><button className="back" onClick={onBack}>← Command Center</button><div className="integrationLoading"><i/><h1>Connecting the digital thread</h1><p>{error||"Loading API, webhook, and interchange telemetry…"}</p></div></main>;
 const eventName=new Map(data.events.map(x=>[x.id,x.eventType]));const hookName=new Map(data.webhooks.map(x=>[x.id,x.name]));
 return <main className="integrationCenter">
  <header className="integrationHeader"><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">AEROLINK 2.0 / OPEN DIGITAL THREAD</p><h1>Integration Command Center</h1><p>Connect AeroLink to the engineering ecosystem with governed machine access, signed events, and observable delivery.</p></div><div className="integrationHeaderActions"><button className="secondary" onClick={()=>sendTest()} disabled={!!busy}>Send test event</button><button className="primaryAction" onClick={()=>setPanel("identity")}>+ Machine identity</button></div></header>
  {error&&<div className="integrationAlert" role="alert"><b>Action needed</b><span>{error}</span><button onClick={()=>setError("")}>Dismiss</button></div>}
  <section className="integrationHero"><div className="apiPulse"><i/><div><span>PUBLIC API</span><b>{data.api.version} operational</b><small>{data.api.basePath} · scoped and rate limited</small></div></div><div className="threadFlow" aria-label="Connected engineering flow"><span>Engineering tools</span><i>→</i><strong>AeroLink control plane</strong><i>→</i><span>Delivery ecosystem</span></div><div className="heroTimestamp"><span>LIVE TELEMETRY</span><b>{time(data.generatedAt)}</b></div></section>
  <section className="integrationMetrics"><article><span>Active machine identities</span><b>{data.metrics.activeIdentities}</b><small>Scoped credentials</small></article><article><span>Enabled webhooks</span><b>{data.metrics.enabledWebhooks}</b><small>Signed destinations</small></article><article><span>Events · 24 hours</span><b>{data.metrics.events24h}</b><small>Transactional outbox</small></article><article className={data.metrics.deliverySuccess<95?"attention":"healthy"}><span>Delivery success</span><b>{data.metrics.deliverySuccess}%</b><small>{data.metrics.deadLetters?`${data.metrics.deadLetters} dead letter(s)`:"No dead letters"}</small></article></section>
  <section className="integrationGrid solo"><article className="integrationPanel identitiesPanel"><div className="integrationPanelHead"><div><span>ACCESS PLANE</span><h2>Machine identities</h2><p>API keys are shown once, hashed at rest, and limited to explicit project scopes.</p></div><button onClick={()=>setPanel("identity")}>Create identity</button></div>{data.identities.length?<div className="integrationTable"><div className="integrationTableHead identityColumns"><span>IDENTITY</span><span>SCOPES</span><span>LAST USED</span><span>STATE</span><span/></div>{data.identities.map(item=><div className="integrationTableRow identityColumns" key={item.id}><div><b>{item.name}</b><small>{item.clientId}</small></div><div className="scopeCloud">{item.scopes.map(x=><span key={x}>{x}</span>)}</div><time>{time(item.lastUsedAt)}</time><strong className={`status ${item.state.toLowerCase()}`}>{stateLabel(item.state)}</strong><button className="rowAction" disabled={item.state!=="Active"||!!busy} onClick={()=>mutate(`/api/integrations/service-identities/${item.id}/revoke`,{method:"POST"},"Revoking identity")}>Revoke</button></div>)}</div>:<Empty title="No machine access yet" detail="Create a scoped identity for CI, suppliers, test systems, or engineering tools." action="Create first identity" onAction={()=>setPanel("identity")}/>}</article></section>
  <section className="integrationPanel webhookPanel"><div className="integrationPanelHead"><div><span>EVENT PLANE</span><h2>Webhook destinations</h2><p>HMAC-SHA256 signatures, exponential retry, replay, and dead-letter visibility.</p></div><button onClick={()=>setPanel("webhook")}>+ Add destination</button></div>{data.webhooks.length?<div className="webhookCards">{data.webhooks.map(item=><article key={item.id}><div className={`hookState ${item.isEnabled?"on":"off"}`}><i/></div><div><b>{item.name}</b><code title={item.endpointUrl}>{short(item.endpointUrl)}</code><div className="eventCloud">{item.eventTypes.map(x=><span key={x}>{x}</span>)}</div></div><div><strong>{item.isEnabled?"Listening":"Paused"}</strong><small>Updated {time(item.updatedAt)}</small><button disabled={!!busy} onClick={()=>mutate(`/api/integrations/webhooks/${item.id}/state`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({enabled:!item.isEnabled})},item.isEnabled?"Pausing webhook":"Enabling webhook")}>{item.isEnabled?"Pause":"Enable"}</button></div></article>)}</div>:<Empty title="No event destinations" detail="Add a webhook destination to begin signed, observable delivery." action="Add first destination" onAction={()=>setPanel("webhook")}/>}</section>
  <section className="integrationGrid activityGrid"><article className="integrationPanel"><div className="integrationPanelHead"><div><span>DELIVERY OPERATIONS</span><h2>Recent delivery activity</h2></div><button onClick={load}>Refresh</button></div>{data.deliveries.length?<div className="deliveryList">{data.deliveries.slice(0,12).map(item=><div key={item.id}><i className={item.state.toLowerCase()}/><div><b>{eventName.get(item.integrationEventId)||"Integration event"}</b><small>to {hookName.get(item.subscriptionId)||"Webhook"} · attempt {item.attemptCount}</small>{item.lastError&&<em>{item.lastError}</em>}</div><div><strong className={`status ${item.state.toLowerCase()}`}>{item.state.replace(/([A-Z])/g," $1")}</strong><time>{time(item.deliveredAt||item.nextAttemptAt)}</time>{item.state==="DeadLettered"&&<button onClick={()=>mutate(`/api/integrations/deliveries/${item.id}/replay`,{method:"POST"},"Replaying delivery")}>Replay</button>}</div></div>)}</div>:<Empty title="The delivery stream is quiet" detail="Send a test event after adding a destination to prove the complete signed-delivery path." action="Send test event" onAction={sendTest}/>}</article>
   <JiraConnectorPanel api={api} projectId={projectId} onError={setError}/></section>
  <section className="integrationGrid activityGrid"><ReqIfExchangeCenter api={api} projectId={projectId} releaseId={releaseId} onError={setError}/></section>
  {panel&&<div className="integrationOverlay" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setPanel(undefined)}}><section role="dialog" aria-modal="true" aria-labelledby="integration-dialog-title"><button className="close" onClick={()=>setPanel(undefined)} aria-label="Close">×</button>{panel==="identity"?<form onSubmit={createIdentity}><p className="eyebrow">GOVERNED MACHINE ACCESS</p><h2 id="integration-dialog-title">Create machine identity</h2><p>Issue a project-scoped credential for one trusted integration. The secret is revealed exactly once.</p><label>Identity name<input name="name" placeholder="e.g. CI verification pipeline" required/></label><fieldset><legend>API scopes</legend><label><input type="checkbox" name="scopes" value="requirements:read" defaultChecked/> Read requirements</label><label><input type="checkbox" name="scopes" value="events:write"/> Publish integration events</label><label><input type="checkbox" name="scopes" value="integrations:read"/> Read integration health</label></fieldset><button className="primaryAction" disabled={!!busy}>{busy||"Create and reveal key"}</button></form>:<form onSubmit={createWebhook}><p className="eyebrow">SIGNED EVENT DELIVERY</p><h2 id="integration-dialog-title">Add webhook destination</h2><p>Every request carries an event name, delivery ID, timestamp, and HMAC-SHA256 signature.</p><label>Destination name<input name="name" placeholder="e.g. Supplier PLM gateway" required/></label><label>HTTPS endpoint<input name="endpointUrl" type="url" placeholder="https://integrations.example.com/aerolink" required/></label><label>Event types<input name="eventTypes" defaultValue="aerolink.integration.test" required/><small>Comma separated. Use * to subscribe to all events.</small></label><button className="primaryAction" disabled={!!busy}>{busy||"Add signed destination"}</button></form>}</section></div>}
  {reveal&&<div className="integrationOverlay secretOverlay"><section role="dialog" aria-modal="true" aria-labelledby="secret-title"><p className="eyebrow">ONE-TIME SECRET</p><h2 id="secret-title">{reveal.title}</h2><p>{reveal.detail}</p><div className="secretValue"><code>{reveal.value}</code><button onClick={()=>navigator.clipboard.writeText(reveal.value)}>Copy</button></div><button className="primaryAction" onClick={()=>setReveal(undefined)}>I have stored it securely</button></section></div>}
 </main>
}

function Empty({title,detail,action,onAction}:{title:string;detail:string;action:string;onAction:()=>void}){return <div className="integrationEmpty"><i>↗</i><b>{title}</b><p>{detail}</p><button onClick={onAction}>{action} →</button></div>}
