import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import type { AuthUser } from "./IdentityCenter";
import PersonPicker from "./PersonPicker";
import { PersonName } from "./People";
import { RichContentEditor, RichContentView } from "./RichContent";
import { emptyRichContent, toPlainText } from "./richContentModel";
import ControlledProblemReportEditor from "./ControlledProblemReportEditor";
import ProblemReportCategoryPicker, { CategoryTile } from "./ProblemReportCategoryPicker";
import { PROBLEM_REPORT_NARRATIVE } from "./problemReportFields";
import { useCategoryVocabulary, type SelectedCategory } from "./problemReportCategories";
import { artifactAcronym, artifactTypeLabel } from "./presentation";
import { AutosaveState, DraftRestore } from "./DraftNotice";
import { useLocalDraft } from "./autosave";
import "./ProblemReportCenter.css";

type Link={artifactType:string;artifactId:string;identifier?:string;relationship:string;addedBy:string;addedAt:string};
type Revision={id:string;revision:number;eventType:string;actor:string;detail?:string;rationale?:string;fromState?:string;toState?:string;evidenceJson?:string;eventSchemaVersion:number;snapshotSchemaVersion:number;snapshotHash:string;snapshotJson?:string;occurredAt:string};
type ClosureCandidate={id:string;reportRevision:number;sequence:number;reportSnapshotSchemaVersion:number;state:string;manifestHash:string;verificationExecutionId:string;selectedBy:string;selectedAt:string;invalidationReason?:string;invalidatedBy?:string;invalidatedAt?:string;approvedBy?:string;approvedAt?:string;packageProvenance?:string;closurePackageHash?:string;approvalAuthority?:string};
type ReleaseWaiver={id:string;blockerRevision:number;blockerVersion:number;rationale:string;approvedBy:string;approvalAuthority:string;signatureMeaning:string;createdAt:string;expiresAt:string;revokedAt?:string;revokedBy?:string;revocationReason?:string;active:boolean};
type DuplicateDiagnostic={status:string;message:string;canonicalTargetId?:string;canonicalTargetIdentifier?:string;canonicalTargetTitle?:string;canonicalTargetState?:string};
type TransitionCapability={state:string;requiresRationale:boolean};
type Report={id:string;projectId?:string;reportNumber:string;revision:number;displayNumber:string;title:string;problem?:string;problemRich?:string;additionalInformation?:string;additionalInformationRich?:string;analysis?:string;analysisRich?:string;rootCause?:string;rootCauseRich?:string;effects?:string;effectsRich?:string;containment?:string;containmentRich?:string;correctiveAction?:string;correctiveActionRich?:string;systemAircraftImpact?:string;systemAircraftImpactRich?:string;workaroundRich?:string;impactAssessmentJson?:string;state:string;disposition?:string;dispositionRationale?:string;duplicateDiagnostic?:DuplicateDiagnostic;category?:SelectedCategory|null;workaround?:string;severity:string;priority:string;classification:string;reportedBy:string;responsibleEngineerId:string;targetReleaseId?:string;isReleaseBlocker:boolean;releaseBlockerVersion:number;waived?:boolean;activeReleaseWaiver?:ReleaseWaiver;releaseWaivers?:ReleaseWaiver[];createdAt?:string;updatedAt:string;version:number;capabilities?:{canApproveSqaClosure:boolean;canApproveReleaseWaiver:boolean;releaseWaiverAuthority?:string;ownerEligible?:boolean;ownerAuthorityException?:string;canReassignOwner?:boolean;canRecoverOwner?:boolean;canRevive?:boolean;reviveTargetState?:string;availableTransitions?:TransitionCapability[]};links?:Link[];approvedCorrectiveActions?:Link[];testEvidence?:Link[];closureCandidates?:ClosureCandidate[];revisions?:Revision[]};
type Dashboard={summary:{total:number;active:number;closureAwaitingApproval:number;closed:number;releaseBlockers:number;waivedBlockers:number}};
type Release={id:string;version:string;isReleased:boolean};
type Props={api:string;projectId:string;releaseId:string;releases:Release[];user:AuthUser;initialReportId?:string;onSelected:(id?:string,targetBuild?:string)=>void;onBack:()=>void;onOpenVerification:(target?:{discipline:"system"|"software";problemReportId:string})=>void;onOpenArtifact:(kind:string,id:string,identifier?:string)=>void};
type ImpactValue="Unknown"|"No"|"Yes";
type ImpactMap=Record<string,ImpactValue>;
type Draft={title:string;problemRich:string;additionalInformationRich:string;category:string;severity:string;priority:string;impacts:ImpactMap}&Record<(typeof PROBLEM_REPORT_NARRATIVE)[number]["key"],string>;
type QueueFilters={state:string;severity:string;priority:string;owner:string;category:string;categoryFamily:string};

const impactFields=[
  ["SystemRequirements","System requirements"],["Hlr","HLR"],["Llr","LLR"],["Code","Code"],
  // "Airworthiness" rather than "Safety", which names what is actually being judged. Answers recorded under
  // the old key were carried across by the migration that renamed it.
  ["Tests","Tests"],["Documents","Documents"],["SystemAircraft","System / aircraft"],["Airworthiness","Airworthiness"],
] as const;
// The nine categories and their six families come from the server — see ProblemReportCategoryPicker.
const initialImpacts=()=>Object.fromEntries(impactFields.map(([key])=>[key,"Unknown"])) as ImpactMap;
const newDraft=():Draft=>({title:"",problemRich:emptyRichContent,additionalInformationRich:emptyRichContent,category:"",severity:"Major",priority:"High",impacts:initialImpacts(),
  ...Object.fromEntries(PROBLEM_REPORT_NARRATIVE.map(field=>[field.key,emptyRichContent]))} as Draft);
const lifecycle=["Draft","ReadyForSccb","Open","Implementing","Verifying","WaitingForSqaToClose","Closed","Rejected"];
const terminalDispositions=["Rejected"];
const queueStates=lifecycle;
const queuePageSize=10;
const call=async(api:string,path:string,method="GET",body?:unknown)=>{const response=await fetch(`${api}${path}`,{method,headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.error??"The controlled action could not be completed.");return data};
const destinationKind=(type:string)=>({ChangeRequest:"change-request",SystemChangeRequest:"change-request",SoftwareChangeRequest:"change-request",ProblemReport:"problem-report",Requirement:"requirement",TestExecution:"test-execution",TestProcedure:"test-procedure",Evidence:"evidence",Document:"document",Release:"release"} as Record<string,string>)[type];
const spaced=(value:string)=>value==="WaitingForSqaToClose"?"Waiting for SQA to Close":value==="ReadyForSccb"?"Ready for SCCB":value.replace(/([a-z])([A-Z])/g,"$1 $2").replace("Sqa","SQA").replace("Sccb","SCCB");
const transitionLabel=(state:string)=>({ReadyForSccb:"Ready for SCCB",Open:"Open",Implementing:"Start implementing",Verifying:"Move to Verifying",WaitingForSqaToClose:"Waiting for SQA to Close",Closed:"Close Problem Report",Rejected:"Reject Problem Report",Draft:"Return to Draft"}[state]??`Move to ${spaced(state)}`);
const parseImpacts=(value?:string):ImpactMap=>{try{return {...initialImpacts(),...JSON.parse(value??"{}")} as ImpactMap}catch{return initialImpacts()}};
const revisionEvidence=(revision:Revision):{type?:string;category?:string;workaround?:string;disposition?:string;dispositionRationale?:string}|undefined=>{
  if(revision.snapshotSchemaVersion<2||!revision.snapshotJson)return undefined;
  try{return JSON.parse(revision.snapshotJson) as {type?:string;category?:string;workaround?:string;disposition?:string;dispositionRationale?:string}}catch{return undefined}
};
const snapshotVersion=(revision:Revision):number|undefined=>{
  if(!revision.snapshotJson)return undefined;
  try{const value=JSON.parse(revision.snapshotJson) as {version?:unknown};return typeof value.version==="number"?value.version:undefined}catch{return undefined}
};

function ConnectedArtifact({link,onOpen}:{link:Link;onOpen:(kind:string,id:string,identifier?:string)=>void}){
  const kind=destinationKind(link.artifactType);
  const content=<><i>{artifactAcronym(link.identifier,link.artifactType)}</i><div><b>{spaced(link.relationship)}</b><span>{artifactTypeLabel(link.artifactType,link.identifier)}{link.identifier&&` · ${link.identifier}`}</span></div><small><PersonName userName={link.addedBy}/></small></>;
  return kind?<button type="button" className="artifactReferenceCard" onClick={()=>onOpen(kind,link.artifactId,link.identifier)}>{content}<em>Open →</em></button>:<article className="artifactUnavailable">{content}<em>Unavailable in this workspace</em></article>;
}

export default function ProblemReportCenter({api,projectId,releaseId,releases,user,initialReportId,onSelected,onBack,onOpenVerification,onOpenArtifact}:Props){
  const [reports,setReports]=useState<Report[]>([]),[page,setPage]=useState(1),[reportTotal,setReportTotal]=useState(0),[totalPages,setTotalPages]=useState(0),[dashboard,setDashboard]=useState<Dashboard>(),[selected,setSelected]=useState<Report>();
  const [search,setSearch]=useState(""),[stateFilter,setStateFilter]=useState(""),[severityFilter,setSeverityFilter]=useState(""),[priorityFilter,setPriorityFilter]=useState(""),[ownerFilter,setOwnerFilter]=useState(""),[categoryFilter,setCategoryFilter]=useState(""),[categoryFamilyFilter,setCategoryFamilyFilter]=useState("");
  const categories=useCategoryVocabulary(api);
  const [targetFilter,setTargetFilter]=useState(()=>new URLSearchParams(location.search).get("targetBuild")??"");
  const refreshSequence=useRef(0);
  // What the queue was actually asked for, as opposed to what is being typed. The dropdowns commit on
  // Apply filters; the search box commits itself a moment after typing stops.
  const [appliedSearch,setAppliedSearch]=useState("");
  const [appliedFilters,setAppliedFilters]=useState<QueueFilters>({state:"",severity:"",priority:"",owner:"",category:"",categoryFamily:""});
  const [showCreate,setShowCreate]=useState(false),[showEdit,setShowEdit]=useState(false),[tab,setTab]=useState<"record"|"history">("record"),[error,setError]=useState(""),[busy,setBusy]=useState(false),[create,setCreate]=useState<Draft>(newDraft()),[note,setNote]=useState("");
  const [showDisposition,setShowDisposition]=useState(false),[dispositionRationale,setDispositionRationale]=useState("");
  const [showReopen,setShowReopen]=useState(false),[reopenRationale,setReopenRationale]=useState("");
  const [showRevive,setShowRevive]=useState(false),[reviveRationale,setReviveRationale]=useState("");
  const [owner,setOwner]=useState({userId:"",name:""});
  const [waiverRationale,setWaiverRationale]=useState(""),[waiverExpiry,setWaiverExpiry]=useState(()=>new Date(Date.now()+7*86400000).toISOString().slice(0,10));
  const createDraft=useLocalDraft(`aerolink:new-problem-report:${projectId}`,create,{isEmpty:value=>!value.title.trim()&&!toPlainText(value.problemRich).trim()});
  const noteDraft=useLocalDraft(`aerolink:problem-report-note:${projectId}:${selected?.id??"none"}`,note,{enabled:!!selected,isEmpty:value=>!value.trim()});
  const isOwner=selected?.responsibleEngineerId===user.userName;
  const isFinished=selected?.state==="Closed"||terminalDispositions.includes(selected?.state??"");

  const refresh=async(selectId?:string,requestedPage=page)=>{const sequence=++refreshSequence.current;try{setError("");const params=new URLSearchParams({projectId,page:String(requestedPage),pageSize:String(queuePageSize)});if(appliedSearch.trim())params.set("search",appliedSearch.trim());if(appliedFilters.state)params.set("state",appliedFilters.state);if(appliedFilters.severity)params.set("severity",appliedFilters.severity);if(appliedFilters.priority)params.set("priority",appliedFilters.priority);if(appliedFilters.category)params.set("category",appliedFilters.category);if(appliedFilters.categoryFamily)params.set("categoryFamily",appliedFilters.categoryFamily);if(appliedFilters.owner.trim())params.set("owner",appliedFilters.owner.trim());const scope=new URLSearchParams({projectId});if(targetFilter==="unassigned"){params.set("targetUnassigned","true");scope.set("targetUnassigned","true")}else if(targetFilter){params.set("targetReleaseId",targetFilter);scope.set("targetReleaseId",targetFilter)}const [list,summary]=await Promise.all([call(api,`/api/problem-reports?${params}`),call(api,`/api/problem-reports/dashboard?${scope}`)]);if(sequence!==refreshSequence.current)return;setReports(list.items);setPage(list.page??requestedPage);setReportTotal(list.totalCount??list.items.length);setTotalPages(list.totalPages??(list.items.length?1:0));setDashboard(summary);const requested=selectId??selected?.id??initialReportId;let detail:Report|undefined;if(requested){const candidate=await call(api,`/api/problem-reports/${requested}`) as Report;const matchesTarget=!targetFilter||(targetFilter==="unassigned"?!candidate.targetReleaseId:candidate.targetReleaseId===targetFilter);if(matchesTarget)detail=candidate}if(!detail&&list.items[0])detail=await call(api,`/api/problem-reports/${list.items[0].id}`) as Report;if(sequence!==refreshSequence.current)return;const id=detail?.id;if(detail){setSelected(detail);setOwner({userId:detail.responsibleEngineerId,name:detail.responsibleEngineerId});
    // The record being read belongs in the address, or a refresh lands on whatever happens to be first.
    //
    // Opening a report from the queue already did this; creating one did not, and the gap was invisible while
    // the queue was filtered by build — the new report was usually the only row, so falling back to items[0]
    // picked it by luck. Project-scoped, the queue holds every report in the Project and that luck is gone:
    // a refresh after creating a report jumped to the lowest-numbered record in the database.
    if(selectId||(requested&&requested!==id))onSelected(id,targetFilter)}else{setSelected(undefined);if(requested)onSelected(undefined,targetFilter)}}catch(reason){if(sequence===refreshSequence.current)setError(reason instanceof Error?reason.message:"Unable to load problem reports.")}};
  // oxlint-disable-next-line react-hooks/exhaustive-deps -- filters are applied deliberately with Apply filters.
  useEffect(()=>{void refresh(undefined,page)},[api,projectId,releaseId,page,appliedSearch,appliedFilters,targetFilter]);// eslint-disable-line react-hooks/exhaustive-deps
  /**
   * The search box asks the queue itself, a moment after typing stops.
   *
   * Typing a number and then having to find a button to press is the sort of thing that makes a queue feel
   * like a form. The wait exists so a five-character number is one request rather than five, and the
   * dropdowns keep their button because changing three of them should ask once, not three times.
   */
  useEffect(()=>{
    if(search.trim()===appliedSearch.trim())return
    const timer=setTimeout(()=>{setPage(1);setAppliedSearch(search)},250)
    return ()=>clearTimeout(timer)
  },[search,appliedSearch]);
  useEffect(()=>{const restore=()=>{setPage(1);setTargetFilter(new URLSearchParams(location.search).get("targetBuild")??"")};addEventListener("popstate",restore);return()=>removeEventListener("popstate",restore)},[]);
  const changeTargetFilter=(value:string)=>{const url=new URL(location.href);if(value)url.searchParams.set("targetBuild",value);else url.searchParams.delete("targetBuild");history.pushState({},"",`${url.pathname}${url.search}`);setPage(1);setTargetFilter(value)};
  const applyFilters=()=>{setPage(1);setAppliedFilters({state:stateFilter,severity:severityFilter,priority:priorityFilter,owner:ownerFilter,category:categoryFilter,categoryFamily:categoryFamilyFilter})};
  const visible=useMemo(()=>reports,[reports]);
  const open=async(id:string)=>{try{const detail=await call(api,`/api/problem-reports/${id}`);setSelected(detail);setOwner({userId:detail.responsibleEngineerId,name:detail.responsibleEngineerId});setTab("record");onSelected(id,targetFilter)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to open report.")}};
  const action=async(path:string,payload:Record<string,unknown>={})=>{if(!selected)return false;try{setBusy(true);await call(api,`/api/problem-reports/${selected.id}/${path}`,"POST",{expectedVersion:selected.version,...payload});setNote("");noteDraft.clear();await refresh(selected.id);return true}catch(reason){setError(reason instanceof Error?reason.message:"Controlled action failed.");return false}finally{setBusy(false)}};
  const closeDisposition=()=>{setShowDisposition(false);setDispositionRationale("")};
  const submitDisposition=async(event:FormEvent)=>{event.preventDefault();if(!dispositionRationale.trim())return;if(await action("transition",{targetState:"Rejected",rationale:dispositionRationale.trim()}))closeDisposition()};
  const [transitionTarget,setTransitionTarget]=useState("");
  const requestTransition=(target:string,requiresRationale:boolean)=>{if(requiresRationale){setTransitionTarget(target);setReopenRationale("");setShowReopen(true)}else void action("transition",{targetState:target})};
  const submitReopen=async(event:FormEvent)=>{event.preventDefault();if(!reopenRationale.trim()||!transitionTarget)return;if(await action("transition",{targetState:transitionTarget,rationale:reopenRationale.trim()})){setShowReopen(false);setReopenRationale("");setTransitionTarget("")}};
  /**
   * Reviving a finished report is the reopen it always was, followed by the editor.
   *
   * Two gestures were one gesture in practice — nobody reopens a closed report to look at it — but they
   * are still two controlled acts, and the transition has to land before the editor opens or the lease
   * would be taken against a state the server refuses to check out. If the transition fails the editor
   * never opens and the dialog keeps the rationale that was typed.
   */
  const submitRevive=async(event:FormEvent)=>{event.preventDefault();
    const target=selected?.capabilities?.reviveTargetState;
    if(!reviveRationale.trim()||!target)return;
    if(await action("transition",{targetState:target,rationale:reviveRationale.trim()})){
      setShowRevive(false);setReviveRationale("");setShowEdit(true)}};
  const createReport=async(event:FormEvent)=>{event.preventDefault();const problem=toPlainText(create.problemRich).trim();if(!create.title.trim()||!problem){setError("Title and Problem Description are required for a Draft PR.");return}try{setBusy(true);const created=await call(api,"/api/problem-reports","POST",{projectId,releaseId,title:create.title.trim(),problem,problemRich:create.problemRich,additionalInformation:toPlainText(create.additionalInformationRich),additionalInformationRich:create.additionalInformationRich,severity:create.severity,priority:create.priority,category:create.category||null,classification:"Engineering anomaly",origin:"Manual report",impactAssessmentJson:JSON.stringify(create.impacts),
      ...Object.fromEntries(PROBLEM_REPORT_NARRATIVE.flatMap(field=>[[field.key,create[field.key]],[field.plain,toPlainText(create[field.key])]]))});setShowCreate(false);setCreate(newDraft());createDraft.clear();await refresh(created.id)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to create report.")}finally{setBusy(false)}};
  // Who holds the record right now. A Problem Report is edited under the same exclusive server lease as every
  // other controlled record, so the page has to be able to say "somebody else has this" rather than offering
  // a control whose check-in would be refused.
  const [lock,setLock]=useState<{editable:boolean;locked:boolean;mine:boolean;holder?:string}>();
  const readLock=useCallback(async(reportId:string)=>{try{setLock(await call(api,`/api/controlled-editing/status?artifactType=ProblemReport&artifactId=${reportId}`))}catch{setLock(undefined)}},[api]);
  useEffect(()=>{if(selected)void readLock(selected.id);else setLock(undefined)},[readLock,selected]);
  const openCorrectiveAction=async()=>{if(!selected)return;try{const target=await call(api,`/api/problem-reports/${selected.id}/corrective-action`);if(!target.available||!target.discipline){setError(target.reason);return}onOpenVerification({discipline:target.discipline,problemReportId:selected.id})}catch{onOpenVerification()}};
  const links=selected?.links??[];
  const generalLinks=links.filter(link=>link.relationship!=="ApprovedCorrectiveAction"&&link.relationship!=="ResolutionVerification");
  const impacts=parseImpacts(selected?.impactAssessmentJson);
  const latestClosureCandidate=selected?.closureCandidates?.[0];
  const closurePackages=(selected?.closureCandidates??[]).filter(candidate=>candidate.state==="Approved"||candidate.state==="LegacyUnavailable");
  const dispositionRevision=selected?.revisions?.find(revision=>revision.eventType==="DispositionRecorded");
  const pageStart=reportTotal?(page-1)*queuePageSize+1:0;
  const pageEnd=Math.min(page*queuePageSize,reportTotal);

  return <main className="problemReportsPage">
    <header className="prHeader"><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">ASSURANCE / PROBLEM REPORTS</p><h1>Problem Reports</h1></div><button className="primaryAction" onClick={()=>setShowCreate(true)}>+ Record problem</button></header>
    {error&&<div className="workspaceError" role="alert">{error}<button onClick={()=>setError("")}>Dismiss</button></div>}
    <section className="prMetrics">{[["Open work",dashboard?.summary.active??0,"blue"],["Release blockers",dashboard?.summary.releaseBlockers??0,"red"],["Waiting for SQA to Close",dashboard?.summary.closureAwaitingApproval??0,"amber"],["Closed records",dashboard?.summary.closed??0,"green"]].map(([label,value,tone])=><article className={String(tone)} key={String(label)}><span>{label}</span><b>{value}</b></article>)}</section>
    {/* No Refresh button. The queue is not a page somebody has to remind to look — the search box asks as it
        is typed into, and every other filter asks when it is applied. */}
    <section className="prWorkspace"><aside><div className="prListHead"><div><h2>Problem Report queue</h2><small>{pageStart}–{pageEnd} of {reportTotal} matching records</small></div></div>
      <div className="prFilters"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Number, title, description, root cause"/></label><label>Status<select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="">All</option>{queueStates.map(value=><option key={value} value={value}>{spaced(value)}</option>)}</select></label><label>Target build<select value={targetFilter} onChange={e=>changeTargetFilter(e.target.value)}><option value="">All target builds</option>{releases.map(value=><option key={value.id} value={value.id}>{value.version}{value.isReleased?" · released":""}</option>)}<option value="unassigned">Not assigned</option></select></label><label>Category<select aria-label="Category" value={categoryFilter} onChange={e=>setCategoryFilter(e.target.value)}><option value="">All</option>{categories.map(definition=><option key={definition.value} value={definition.value}>{definition.code} · {definition.label}</option>)}</select></label><label>Category family<select aria-label="Category family" value={categoryFamilyFilter} onChange={e=>setCategoryFamilyFilter(e.target.value)}><option value="">All</option>{[...new Set(categories.map(definition=>definition.family))].map(family=><option key={family}>{family}</option>)}</select></label><label>Severity<select value={severityFilter} onChange={e=>setSeverityFilter(e.target.value)}><option value="">All</option>{["Critical","High","Major","Minor","Trivial"].map(value=><option key={value}>{value}</option>)}</select></label><label>Priority<select value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">All</option>{["Urgent","High","Normal","Low"].map(value=><option key={value}>{value}</option>)}</select></label><label>Assigned user<input value={ownerFilter} onChange={e=>setOwnerFilter(e.target.value)} placeholder="User name"/></label><button type="button" onClick={applyFilters}>Apply filters</button></div>
      <div className="prList">{visible.map(report=><button key={report.id} onClick={()=>void open(report.id)} className={selected?.id===report.id?"selected":""}><i className={report.severity.toLowerCase()}>{report.severity.slice(0,1)}</i><div><small>{report.displayNumber} · {spaced(report.state)}</small><b>{report.title}</b><span><PersonName userName={report.responsibleEngineerId||report.reportedBy}/> · {new Date(report.updatedAt).toLocaleDateString()}</span></div>{report.isReleaseBlocker&&!report.waived&&<em>BLOCKER</em>}</button>)}{!visible.length&&<div className="prEmpty"><b>{search.trim()||stateFilter||severityFilter||priorityFilter||categoryFilter||categoryFamilyFilter||ownerFilter.trim()?"No Problem Reports match these filters.":"No Problem Reports are recorded for this Project."}</b></div>}</div>
      <nav className="prPager" aria-label="Problem Report queue pages"><button type="button" disabled={page<=1} onClick={()=>setPage(current=>Math.max(1,current-1))}>Previous</button><span>Page {page} of {Math.max(totalPages,1)}</span><button type="button" disabled={page>=Math.max(totalPages,1)} onClick={()=>setPage(current=>current+1)}>Next</button></nav>
    </aside><section className="prDetail">{selected?<><div className="prDetailHead"><div><p>{selected.displayNumber} · CONTROLLED RECORD</p><h2>{selected.title}</h2><div><span className={`prState ${selected.state.toLowerCase()}`}>{spaced(selected.state)}</span><span>{selected.severity} severity</span><span>{selected.priority} priority</span></div></div>{selected.isReleaseBlocker&&<div className="blockerFlag"><b>{selected.waived?"Controlled waiver active":"Release blocker"}</b><span>{selected.activeReleaseWaiver?`${selected.activeReleaseWaiver.rationale} · ${spaced(selected.activeReleaseWaiver.approvalAuthority)} ${selected.activeReleaseWaiver.approvedBy} · expires ${new Date(selected.activeReleaseWaiver.expiresAt).toLocaleDateString()}`:"Requires a separate independent release-waiver decision."}</span></div>}</div>
      <nav className="prTabs" aria-label="Problem Report sections"><button className={tab==="record"?"active":""} onClick={()=>setTab("record")}>Record</button><button className={tab==="history"?"active":""} onClick={()=>setTab("history")}>History <span>{selected.revisions?.length??0}</span></button></nav>
        {tab==="history"?<section className="prTimeline"><div><h3>Immutable lifecycle history</h3><span>Version {selected.version}</span></div>{(selected.releaseWaivers?.length??0)>0&&<div className="prClosurePackages"><h4>Controlled release-waiver history</h4>{selected.releaseWaivers?.map(waiver=><article key={waiver.id}><i>◇</i><div><b>{waiver.active?"Active waiver":"Historical waiver"} · revision {waiver.blockerRevision}</b><span><PersonName userName={waiver.approvedBy}/> · {spaced(waiver.approvalAuthority)} · expires {new Date(waiver.expiresAt).toLocaleString()}</span><small>{waiver.rationale}{waiver.revocationReason&&` · Revoked: ${waiver.revocationReason}`}</small></div></article>)}</div>}{closurePackages.length>0&&<div className="prClosurePackages"><h4>Controlled closure packages</h4>{closurePackages.map(candidate=><article key={candidate.id}><i>▣</i><div><b>Closure revision {candidate.reportRevision}{candidate.reportRevision<selected.revision?" · prior closure cycle":""}</b><span>{candidate.state==="LegacyUnavailable"?"Legacy closure · exact original package was not frozen":<><PersonName userName={candidate.approvedBy??""}/> · {candidate.approvalAuthority?spaced(candidate.approvalAuthority):"Authority not retained"} · {candidate.approvedAt&&new Date(candidate.approvedAt).toLocaleString()}</>}</span></div>{candidate.state==="Approved"&&candidate.closurePackageHash?<><code>{candidate.closurePackageHash.slice(0,12)}</code><a href={`${api}/api/problem-reports/${selected.id}/closure-package?candidateId=${candidate.id}`} target="_blank" rel="noreferrer">Open frozen closure package</a></>:<em>Historical evidence unavailable</em>}</article>)}</div>}{selected.revisions?.map(revision=>{const evidence=revisionEvidence(revision);const recordVersion=snapshotVersion(revision);return <article key={revision.id}><i>✓</i><div><b>{spaced(revision.eventType)} · revision {revision.revision}{recordVersion===undefined?"":` · record version ${recordVersion}`}</b>{revision.fromState&&revision.toState&&<strong>{spaced(revision.fromState)} → {spaced(revision.toState)}</strong>}<span><PersonName userName={revision.actor}/> · {new Date(revision.occurredAt).toLocaleString()}</span>{revision.rationale&&<p><b>Rationale:</b> {revision.rationale}</p>}{revision.detail&&revision.detail!==revision.rationale&&<p>{revision.detail}</p>}{evidence?.disposition&&<p><b>{spaced(evidence.disposition)}</b> · {evidence.dispositionRationale}</p>}{evidence?<small>Snapshot schema {revision.snapshotSchemaVersion} · Category {evidence.category??evidence.type??"Not recorded"} · Workaround {evidence.workaround||"None recorded"}</small>:<small>Legacy snapshot schema {revision.snapshotSchemaVersion} · exact fields were not recorded</small>}</div><code>{revision.snapshotHash.slice(0,12)}</code></article>})}</section>:<>
        <section className="prIdentity"><div><small>RAISED BY</small><b><PersonName userName={selected.reportedBy}/></b><span>{selected.createdAt&&new Date(selected.createdAt).toLocaleString()}</span></div><div><small>ASSIGNED USER</small><b><PersonName userName={selected.responsibleEngineerId}/></b></div><div className="prIdentityCategory"><small>CATEGORY</small>{selected.category?<CategoryTile definition={selected.category} provenance={selected.category.provenance} compact/>:<b className="prNoCategory">Not yet classified</b>}</div><div><small>TARGET BUILD</small><b>{releases.find(item=>item.id===selected.targetReleaseId)?.version??"Not assigned"}</b></div></section>
        {selected.capabilities?.ownerAuthorityException&&<div className="prClosureInvalidated" role="alert"><b>Owner no longer authorized</b><span>{selected.capabilities.ownerAuthorityException}{selected.capabilities.canRecoverOwner?" Select an eligible accountable owner to recover this record.":" Ask a Project Engineering Lead, Engineering Manager, or Program Manager to reassign it."}</span></div>}
        {!isFinished&&(selected.capabilities?.canReassignOwner??isOwner)&&<details className="prAdmin"><summary>Reassign or change target build</summary><div><label>Assigned user<PersonPicker api={api} projectId={projectId} value={owner.userId} name={owner.name} index={0} label="Assigned user" authority="ProblemReportOwner" onSelect={setOwner}/></label><button disabled={busy||!owner.userId||owner.userId===selected.responsibleEngineerId} onClick={()=>void action("owner",{responsibleEngineerId:owner.userId})}>Reassign</button>{isOwner&&<label>Target build<select value={selected.targetReleaseId??""} onChange={event=>void action("target-build",{targetReleaseId:event.target.value})}><option value="" disabled>Not assigned</option>{releases.map(item=><option key={item.id} value={item.id}>{item.version}{item.isReleased?" · released":""}</option>)}</select></label>}</div></details>}
        {/* Who may edit is the server's answer, not one recomputed here. The checkout status endpoint
            already weighs the state and the lease, so `editable` is the whole question — this used to add
            `isOwner` on top of it, which is why a report in Verifying showed nothing at all to the tester
            who found the mistake in it. A finished report offers the SQA reopen instead, and only to
            whoever the lifecycle policy says may perform it. */}
        {lock?.editable&&(lock.locked&&!lock.mine
          ? <p className="prCheckoutHeld"><b><PersonName userName={lock.holder??""}/> has this Problem Report checked out.</b> It is read-only until they check it in or their lease expires.</p>
          : <button type="button" className="prEditButton" onClick={()=>setShowEdit(true)}>Check out &amp; edit</button>)}
        {!lock?.editable&&selected.capabilities?.canRevive&&<button type="button" className="prEditButton prReviveButton" onClick={()=>setShowRevive(true)}>Revive &amp; edit</button>}
        <section className="prNarrative"><article><small>PROBLEM DESCRIPTION</small>{selected.problemRich?<RichContentView api={api} value={selected.problemRich} empty={selected.problem}/>:<p>{selected.problem}</p>}</article><article><small>ADDITIONAL INFORMATION</small>{selected.additionalInformationRich?<RichContentView api={api} value={selected.additionalInformationRich} empty={selected.additionalInformation}/>:<p>{selected.additionalInformation||"Not yet provided."}</p>}</article><article><small>ROOT CAUSE</small>{selected.rootCauseRich?<RichContentView api={api} value={selected.rootCauseRich} empty={selected.rootCause}/>:<p>{selected.rootCause||"Not yet determined."}</p>}</article><article><small>EFFECTS</small>{selected.effectsRich?<RichContentView api={api} value={selected.effectsRich} empty={selected.effects}/>:<p>{selected.effects||"Not yet recorded."}</p>}</article><article><small>CONTAINMENT</small>{selected.containmentRich?<RichContentView api={api} value={selected.containmentRich} empty={selected.containment}/>:<p>{selected.containment||"Not yet recorded."}</p>}</article><article><small>WORKAROUND</small>{selected.workaroundRich?<RichContentView api={api} value={selected.workaroundRich} empty={selected.workaround}/>:<p>{selected.workaround||"None recorded."}</p>}</article><article><small>HUMAN CORRECTIVE-ACTION NARRATIVE</small>{selected.correctiveActionRich?<RichContentView api={api} value={selected.correctiveActionRich} empty={selected.correctiveAction}/>:<p>{selected.correctiveAction||"Not yet recorded."}</p>}</article></section>
        {selected.disposition&&selected.disposition!=="Fixed"&&<section className="prDispositionDecision" aria-label="Controlled disposition"><div><small>CONTROLLED DISPOSITION</small><h3>{spaced(selected.disposition)}</h3><p>{selected.dispositionRationale}</p></div><div><span>{dispositionRevision?<><PersonName userName={dispositionRevision.actor}/> · {new Date(dispositionRevision.occurredAt).toLocaleString()}</>:"Recorded in controlled history"}</span>{selected.disposition==="Duplicate"&&selected.duplicateDiagnostic?.canonicalTargetIdentifier&&<><b>Canonical target {selected.duplicateDiagnostic.canonicalTargetIdentifier}</b><span>{selected.duplicateDiagnostic.canonicalTargetTitle} · {spaced(selected.duplicateDiagnostic.canonicalTargetState??"")}</span></>}</div></section>}
        <section className="prImpact"><div><h3>Impact assessment</h3><p>{selected.systemAircraftImpact||"No combined System / aircraft impact narrative has been recorded."}</p></div><div className="prImpactGrid">{impactFields.map(([key,label])=><span className={(impacts[key]??"Unknown").toLowerCase()} key={key}><b>{label}</b><em>{impacts[key]??"Unknown"}</em></span>)}</div></section>
        <section className="prFlow"><div><h3>Lifecycle action</h3><p>{spaced(selected.state)} · controlled version {selected.version}</p></div>{noteDraft.offered&&<DraftRestore savedAt={noteDraft.offered.savedAt} description="Unsubmitted notes are available in this browser." onRestore={()=>{setNote(noteDraft.offered!.value);noteDraft.restore()}} onDiscard={noteDraft.discard}/>} {note.trim()&&<AutosaveState status={noteDraft.status} savedAt={noteDraft.savedAt} where="this browser"/>}
          {selected.state==="Verifying"&&latestClosureCandidate?.state==="Invalidated"&&<div className="prClosureInvalidated" role="status"><b>Closure verification invalidated</b><span>{spaced(latestClosureCandidate.invalidationReason??"controlled change")} changed the reviewed closure basis. Record a new passing successor result before SQA closure.</span></div>}
          {selected.capabilities?.availableTransitions?.map(transition=><button key={transition.state} disabled={busy} onClick={()=>requestTransition(transition.state,transition.requiresRationale)}>{transitionLabel(transition.state)}{transition.requiresRationale?" …":" →"}</button>)}
          {selected.state==="Verifying"&&<button onClick={()=>void openCorrectiveAction()}>Select closure-supporting test result →</button>}
          {selected.capabilities?.availableTransitions?.some(transition=>transition.state==="Rejected")&&<button className="quiet" disabled={busy} onClick={()=>setShowDisposition(true)}>Reject…</button>}
          {selected.capabilities?.canApproveReleaseWaiver&&<details className="prAdmin"><summary>Approve independent release waiver</summary><div><label>Waiver rationale<textarea value={waiverRationale} onChange={event=>setWaiverRationale(event.target.value)} /></label><label>Expiry date<input type="date" value={waiverExpiry} onChange={event=>setWaiverExpiry(event.target.value)} /></label><button disabled={busy||!waiverRationale.trim()||!waiverExpiry} onClick={()=>void action("release-waiver",{rationale:waiverRationale,expiresAt:new Date(`${waiverExpiry}T23:59:59Z`).toISOString()})}>Approve controlled waiver</button></div></details>}
          {selected.activeReleaseWaiver&&selected.capabilities?.releaseWaiverAuthority&&<button className="quiet" disabled={busy} onClick={()=>void action(`release-waiver/${selected.activeReleaseWaiver!.id}/revoke`,{reason:"Waiver revoked by current release authority."})}>Revoke active waiver</button>}
          {selected.capabilities?.availableTransitions?.some(transition=>transition.state==="Draft"||transition.state==="Verifying")&&<button className="quiet" disabled={busy} onClick={()=>{const transition=selected.capabilities?.availableTransitions?.find(item=>item.state==="Draft"||item.state==="Verifying");if(transition)requestTransition(transition.state,true)}}>Move backward…</button>}
          {isOwner&&!["Closed",...terminalDispositions].includes(selected.state)&&<button className="quiet" disabled={busy} onClick={()=>void action("blocker",{isReleaseBlocker:!selected.isReleaseBlocker,waiverRationale:""})}>{selected.isReleaseBlocker?"Clear release blocker":"Raise release blocker"}</button>}
        </section>
        <section className="prCorrective"><div><h3>Approved linked change requests</h3><span>Automatically captured when linked CRs are approved</span></div>{selected.approvedCorrectiveActions?.length?<div className="prLinks">{selected.approvedCorrectiveActions.map(link=><ConnectedArtifact key={`${link.artifactId}-${link.relationship}`} link={link} onOpen={onOpenArtifact}/>)}</div>:<p className="muted">No linked change request has been approved yet.</p>}</section>
        <section className="prEvidence prTestEvidence"><div><h3>Test evidence supporting closure</h3><span>{selected.testEvidence?.length??0} selected passing results</span></div>{selected.testEvidence?.length?<div className="prLinks">{selected.testEvidence.map(link=><ConnectedArtifact key={`${link.artifactId}-${link.relationship}`} link={link} onOpen={onOpenArtifact}/>)}</div>:<p className="muted">No test result has been selected to support closure.</p>}</section>
        <section className="prEvidence"><div><h3>Connected engineering artifacts</h3><span>{generalLinks.length} controlled links</span></div>{generalLinks.length?<div className="prLinks">{generalLinks.map(link=><ConnectedArtifact key={`${link.artifactType}-${link.artifactId}-${link.relationship}`} link={link} onOpen={onOpenArtifact}/>)}</div>:<p className="muted">No related engineering artifacts have been linked.</p>}</section>
      </>}</>:<div className="prBlank"><span>◎</span><h2>Select a Problem Report</h2></div>}</section></section>
    {showCreate&&<div className="prModal" role="dialog" aria-label="Record a problem"><form className="prCreateWhole" onSubmit={createReport}><button type="button" className="close" aria-label="Close" onClick={()=>setShowCreate(false)}>×</button><p>NEW PROBLEM REPORT</p><h2>Save Draft PR</h2>{createDraft.offered&&<DraftRestore savedAt={createDraft.offered.savedAt} description="An unfinished Problem Report is available in this browser." onRestore={()=>{setCreate(createDraft.offered!.value);createDraft.restore()}} onDiscard={createDraft.discard}/>}<label>Title<input required value={create.title} onChange={e=>setCreate({...create,title:e.target.value})}/></label><RichContentEditor api={api} projectId={projectId} label="Problem Description" value={create.problemRich} placeholder="Describe the problem and its observed effect." onChange={value=>setCreate({...create,problemRich:value})}/><RichContentEditor api={api} projectId={projectId} label="Additional Information" value={create.additionalInformationRich} onChange={value=>setCreate({...create,additionalInformationRich:value})}/>{PROBLEM_REPORT_NARRATIVE.map(field=><RichContentEditor key={field.key} api={api} projectId={projectId} label={field.label} value={create[field.key]} onChange={value=>setCreate({...create,[field.key]:value})}/>)}<fieldset className="prImpactEditor"><legend>Impact matrix</legend>{impactFields.map(([key,label])=><label key={key}>{label}<select aria-label={label} value={create.impacts[key]} onChange={e=>setCreate({...create,impacts:{...create.impacts,[key]:e.target.value as ImpactValue}})}>{["Unknown","No","Yes"].map(value=><option key={value}>{value}</option>)}</select></label>)}</fieldset><label>Category<ProblemReportCategoryPicker api={api} value={create.category} required onChange={value=>setCreate({...create,category:value})}/></label><div className="prFormGrid"><label>Severity<select value={create.severity} onChange={e=>setCreate({...create,severity:e.target.value})}>{["Critical","High","Major","Minor","Trivial"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={create.priority} onChange={e=>setCreate({...create,priority:e.target.value})}>{["Urgent","High","Normal","Low"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="prCreateFoot"><AutosaveState status={createDraft.status} savedAt={createDraft.savedAt} where="this browser"/><button className="primaryAction" disabled={busy}>Save Draft PR →</button></div></form></div>}
    {showDisposition&&selected&&<div className="prModal" role="dialog" aria-label="Reject Problem Report"><form onSubmit={submitDisposition}><button type="button" className="close" aria-label="Close" onClick={closeDisposition}>×</button><p>CONTROLLED ENGINEERING DECISION</p><h2>Reject {selected.displayNumber}</h2><p>Rejection is retained in immutable lifecycle history and requires a rationale.</p><label>Rationale<textarea required value={dispositionRationale} onChange={event=>setDispositionRationale(event.target.value)} placeholder="Record why this Problem Report is rejected."/></label><button className="primaryAction" disabled={busy||!dispositionRationale.trim()}>Reject Problem Report →</button></form></div>}
    {showReopen&&selected&&<div className="prModal" role="dialog" aria-label="Backward Problem Report transition"><form onSubmit={submitReopen}><button type="button" className="close" aria-label="Close" onClick={()=>{setShowReopen(false);setTransitionTarget("")}}>×</button><p>CONTROLLED LIFECYCLE TRANSITION</p><h2>{transitionLabel(transitionTarget)} · {selected.displayNumber}</h2><p>Backward transitions require a nonblank rationale and are retained in immutable history.</p><label>Rationale<textarea required value={reopenRationale} onChange={event=>setReopenRationale(event.target.value)} placeholder="Explain the engineering basis for this transition."/></label><button className="primaryAction" disabled={busy||!reopenRationale.trim()}>{transitionLabel(transitionTarget)} →</button></form></div>}
    {showRevive&&selected&&<div className="prModal" role="dialog" aria-label="Revive Problem Report"><form onSubmit={submitRevive}><button type="button" className="close" aria-label="Close" onClick={()=>{setShowRevive(false);setReviveRationale("")}}>×</button><p>CONTROLLED LIFECYCLE TRANSITION</p><h2>Revive &amp; edit · {selected.displayNumber}</h2><p>This Problem Report is {spaced(selected.state)}. Reviving it returns it to <b>{spaced(selected.capabilities?.reviveTargetState??"")}</b>, creates revision {String((selected.revision??0)+1).padStart(2,"0")}, and opens the editor. Revision {String(selected.revision??0).padStart(2,"0")}, its approved closure package and its signatures are left exactly as they are.</p><label>Rationale<textarea required value={reviveRationale} onChange={event=>setReviveRationale(event.target.value)} placeholder="Explain why this finished Problem Report is being reopened."/></label><button className="primaryAction" disabled={busy||!reviveRationale.trim()}>Revive &amp; edit →</button></form></div>}
    {showEdit&&selected&&<ControlledProblemReportEditor api={api} projectId={projectId} report={selected} impactFields={impactFields} onClose={()=>setShowEdit(false)} onCommitted={async()=>{await refresh(selected.id);await readLock(selected.id)}}/>}
  </main>;
}
