import { useState } from 'react'
import type { FormEvent } from 'react'
import './ReleaseExecutionWorkbench.css'

type Gate={code:string;complete:boolean;completed:number;total:number}
type Change={id:string;displayNumber:string;title:string;type:string;state:string;authorId:string;requirementCount:number;included:boolean}
type Build={id:string;buildNumber:string;releaseId:string;baselineId:string;state:string}
type Detail={id:string;projectId:string;releaseId:string;release:string;baselineId:string;baseline:string;baselineState:string;requirementsHash?:string;softwareBuildId?:string;readiness:{gates:Gate[]};changes:Change[];impacts:{scrId:string;state:string}[];events:{eventType:string}[]}
type Props={api:string;detail:Detail;builds:Build[];onRefresh:()=>Promise<void>;onError:(message:string)=>void;onOpenScr:(id:string)=>void;onOpenVerification:()=>void;onOpenDocuments:()=>void}

export default function ReleaseExecutionWorkbench({api,detail,builds,onRefresh,onError,onOpenScr,onOpenVerification,onOpenDocuments}:Props){
 const [busy,setBusy]=useState(''),[selectedChange,setSelectedChange]=useState<Change>(),[rationale,setRationale]=useState(''),[manifest,setManifest]=useState<File>(),[evidence,setEvidence]=useState<File>(),[result,setResult]=useState('')
 const gate=(code:string)=>detail.readiness.gates.find(x=>x.code===code)
 const request=async(path:string,body:unknown,method='POST')=>{setBusy(path);onError('');const response=await fetch(`${api}${path}`,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){onError((await response.json()).error||'Release operation failed.');setBusy('');return undefined}const value=response.status===204?{}:await response.json();await onRefresh();setBusy('');return value}
 const freeze=()=>request(`/api/baselines/${detail.baselineId}/freeze`,{actorId:'configuration.manager'})
 const materialize=()=>request(`/api/baselines/${detail.baselineId}/materialize-requirements`,{actorId:'configuration.manager'})
 const reconcile=()=>request(`/api/release-campaigns/${detail.id}/reconcile-lifecycle-links`,{actorId:'development.assurance'}).then(x=>{if(x)setResult(`${x.traceLinksCreated} trace and ${x.coverageLinksCreated} coverage links carried forward; ${x.uncoveredRequirements} explicit coverage action remains.`)})
 const documents=()=>request(`/api/baselines/${detail.baselineId}/generate-documents`,{actorId:'configuration.manager'}).then(x=>{if(x){setResult(`${x.generated} controlled document types are now bound to ${detail.baseline}.`);onOpenDocuments()}})
 const createBuild=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const created=await request('/api/builds',{projectId:form.get('projectId'),releaseId:detail.releaseId,baselineId:detail.baselineId,buildNumber:form.get('buildNumber'),description:form.get('description'),recordedBy:form.get('recordedBy')});if(created)await request(`/api/release-campaigns/${detail.id}/verification-build`,{softwareBuildId:created.id,actorId:'release.manager'})}
 const bulkDisposition=async(state:'Addressed'|'NotApplicable')=>{if(!selectedChange||!rationale.trim())return;const response=await request(`/api/release-campaigns/${detail.id}/impact-dispositions`,{scrId:selectedChange.id,state,rationale,actorId:'release.manager'},'PUT');if(response){setResult(`${response.dispositioned} impacts dispositioned for ${selectedChange.displayNumber}.`);setSelectedChange(undefined);setRationale('')}}
 const importPackage=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!manifest||!evidence)return;setBusy('import');onError('');const body=new FormData();body.append('manifest',manifest);body.append('evidence',evidence);body.append('actorId','test.lead');const response=await fetch(`${api}/api/release-campaigns/${detail.id}/verification-package`,{method:'POST',body});if(!response.ok){onError((await response.json()).error||'Verification package import failed.');setBusy('');return}const value=await response.json();setResult(`${value.executionsRecorded} immutable results imported: ${value.passed} Pass, ${value.failed} Fail, ${value.blocked} Blocked. Evidence ${value.evidenceSha256.slice(0,16)}…`);setBusy('');await onRefresh()}
 const releaseBuilds=builds.filter(x=>x.releaseId===detail.releaseId),pendingFor=(id:string)=>detail.impacts.filter(x=>x.scrId===id&&x.state==='Pending').length
 const reconciled=detail.events.some(x=>x.eventType==='LifecycleLinksReconciled')
 return <section className="executionWorkbench"><div className="executionHeading"><div><p className="eyebrow">GOVERNED RELEASE EXECUTION</p><h2>Drive every blocker to evidence</h2><p>Each action writes authoritative records and immediately recalculates readiness.</p></div>{result&&<div className="executionResult">{result}</div>}</div>
 <div className="executionColumns"><section className="executionPanel changes"><div className="executionTitle"><div><h3>1 · Change inputs</h3><p>Approve, include, or formally defer every 1.6 request.</p></div><b>{gate('change_control')?.completed}/{gate('change_control')?.total}</b></div>{detail.changes.map(x=><article key={x.id}><button onClick={()=>onOpenScr(x.id)}>{x.displayNumber}</button><div><b>{x.title}</b><small>{x.type} · {x.state} · {x.requirementCount} change</small></div><i className={x.included?'included':x.state.toLowerCase()}>{x.included?'Included':x.state}</i>{pendingFor(x.id)>0&&<button className="impactAction" onClick={()=>{setSelectedChange(x);setRationale('')}}>{pendingFor(x.id)} impacts</button>}</article>)}</section>
 <div className="executionStack"><section className="executionPanel"><div className="executionTitle"><div><h3>2 · Exact baseline</h3><p>{detail.baseline} · {detail.baselineState}</p></div><b>{gate('baseline')?.complete?'Ready':'Blocked'}</b></div>{detail.baselineState==='Draft'&&<button disabled={!gate('change_control')?.complete||busy!==''} onClick={freeze}>Freeze exact SCR set</button>}{detail.baselineState==='Frozen'&&!detail.requirementsHash&&<button disabled={busy!==''} onClick={materialize}>Materialize 1.6 requirements</button>}{detail.requirementsHash&&<><code>{detail.requirementsHash.slice(0,24)}…</code>{!reconciled&&<button disabled={busy!==''} onClick={reconcile}>Carry forward versioned links</button>}<button className="outline" onClick={onOpenVerification}>Resolve coverage in Verification</button>{!gate('documents')?.complete&&<button disabled={busy!==''} onClick={documents}>Generate six controlled outputs</button>}</>}</section>
 <section className="executionPanel"><div className="executionTitle"><div><h3>3 · Verification build</h3><p>Bind results to one exact executable configuration.</p></div><b>{detail.softwareBuildId?'Selected':'Needed'}</b></div>{!detail.requirementsHash?<p className="executionHint">Materialize the baseline first.</p>:!releaseBuilds.length?<form className="buildForm" onSubmit={createBuild}><input type="hidden" name="projectId" value={detail.projectId}/><input name="buildNumber" defaultValue={`FMS-${detail.release}-RC1`} required/><input name="recordedBy" defaultValue="build.engineer" required/><textarea name="description" defaultValue="FMS release-candidate build for controlled verification." required/><button disabled={busy!==''}>Record immutable build</button></form>:<div className="buildChoices">{releaseBuilds.map(x=><button disabled={detail.softwareBuildId===x.id||busy!==''} key={x.id} onClick={()=>request(`/api/release-campaigns/${detail.id}/verification-build`,{softwareBuildId:x.id,actorId:'release.manager'})}>{x.buildNumber}<small>{detail.softwareBuildId===x.id?'Selected':x.state}</small></button>)}</div>}</section>
 <section className="executionPanel"><div className="executionTitle"><div><h3>4 · External verification package</h3><p>Import exact results and one checksummed campaign evidence package.</p></div><b>{gate('verification')?.completed}/{gate('verification')?.total}</b></div>{!detail.softwareBuildId?<p className="executionHint">Select the verification build first.</p>:<><a className="templateLink" href={`${api}/api/release-campaigns/${detail.id}/verification-template`}>Download exact JSON manifest template</a><form className="packageForm" onSubmit={importPackage}><label>Completed JSON manifest<input type="file" accept="application/json,.json" onChange={e=>setManifest(e.target.files?.[0])} required/></label><label>Signed evidence package<input type="file" onChange={e=>setEvidence(e.target.files?.[0])} required/></label><button disabled={!manifest||!evidence||busy!==''}>{busy==='import'?'Validating and importing…':'Import immutable results + evidence'}</button></form></>}</section></div></div>
 {selectedChange&&<div className="campaignModal"><div><p className="eyebrow">{selectedChange.displayNumber} / {pendingFor(selectedChange.id)} PENDING IMPACTS</p><h2>Disposition this change package</h2><p>One rationale will be recorded against every remaining requirement, traceability, verification, and document impact for this exact request.</p><textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Required review rationale and evidence reference"/><div><button className="outline" onClick={()=>setSelectedChange(undefined)}>Cancel</button>{selectedChange.state==='Deferred'&&<button disabled={!rationale.trim()} onClick={()=>bulkDisposition('NotApplicable')}>Mark deferred impacts N/A</button>}<button disabled={!rationale.trim()} onClick={()=>bulkDisposition('Addressed')}>Mark all addressed</button></div></div></div>}
 </section>
}
