import { useCallback, useEffect, useState } from 'react'
import './ReleaseCampaignCenter.css'
type Gate={code:string;name:string;complete:boolean;completed:number;total:number;detail:string;action:string}
type Impact={id:string;scrId:string;scr:string;title:string;kind:string;artifactReference:string;description:string;state:string;rationale:string}
type Approval={position:number;approverId:string;approverName:string;state:string;approvedAt?:string}
type Detail={id:string;name:string;state:string;projectId:string;releaseId:string;release:string;baselineId:string;baseline:string;baselineState:string;softwareBuildId?:string;releaseHash?:string;readiness:{percent:number;readyForRelease:boolean;gates:Gate[]};impacts:Impact[];approvals:Approval[];events:{eventType:string;actorId:string;detail:string;occurredAt:string}[]}
type Build={id:string;buildNumber:string;releaseId:string;baselineId:string;state:string}
type Comparison={fromRelease:string;toRelease:string;toMaterialized:boolean;summary:{added:number;modified:number;retired:number;unchanged:number;proposed:number};proposed:{scr:string;title:string;state:string;type:string;displayNumber:string;level:string;kind:string;statement:string}[]}
type Props={api:string;projectId:string;releases:{id:string;version:string}[];onBack:()=>void;onOpenScr:(id:string)=>void}
export default function ReleaseCampaignCenter({api,projectId,releases,onBack,onOpenScr}:Props){
 const [campaignId,setCampaignId]=useState(''),[detail,setDetail]=useState<Detail>(),[builds,setBuilds]=useState<Build[]>([]),[comparison,setComparison]=useState<Comparison>(),[impact,setImpact]=useState<Impact>(),[rationale,setRationale]=useState(''),[error,setError]=useState('')
 const load=useCallback(async()=>{const [campaignsResponse,buildsResponse]=await Promise.all([fetch(`${api}/api/release-campaigns?projectId=${projectId}`),fetch(`${api}/api/builds?projectId=${projectId}`)]);const campaigns=campaignsResponse.ok?await campaignsResponse.json():[];const id=campaignId||campaigns[0]?.id||'';if(!campaignId&&id)setCampaignId(id);if(buildsResponse.ok)setBuilds(await buildsResponse.json());if(id){const response=await fetch(`${api}/api/release-campaigns/${id}`);if(response.ok)setDetail(await response.json())}if(releases.length>=2){const response=await fetch(`${api}/api/release-comparison?projectId=${projectId}&fromReleaseId=${releases[0].id}&toReleaseId=${releases[releases.length-1].id}`);if(response.ok)setComparison(await response.json())}},[api,projectId,releases,campaignId])
 useEffect(()=>{load()},[load])
 const call=async(path:string,body:unknown)=>{setError('');const response=await fetch(`${api}/api/release-campaigns/${campaignId}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const result=await response.json();setError(result.error+(result.blockers?`: ${result.blockers.join(', ')}`:''));return}await load()}
 const disposition=async(state:'Addressed'|'NotApplicable')=>{if(!impact||!rationale.trim())return;const response=await fetch(`${api}/api/impact-dispositions/${impact.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state,rationale,actorId:'release.manager'})});if(!response.ok){setError((await response.json()).error);return}setImpact(undefined);setRationale('');await load()}
 const activeApproval=detail?.approvals.find(x=>x.state==='Active')
 return <main className="campaignPage"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">RELEASE CONTROL / FMS {detail?.release??''}</p><h1>{detail?.name??'Release Campaign'}</h1><p>Digital-thread readiness, impact closure, verification evidence, controlled outputs, and formal release.</p></div>{detail&&<div className={`campaignState ${detail.state.toLowerCase()}`}>{detail.state}</div>}</header>{error&&<div className="workspaceError">{error}</div>}
 {detail&&<><section className="readinessHero"><div className="readinessDial" style={{'--ready':`${detail.readiness.percent*3.6}deg`} as React.CSSProperties}><b>{detail.readiness.percent}%</b><span>ready</span></div><div><p className="eyebrow">TARGET RELEASE</p><h2>FMS {detail.release}</h2><p>{detail.baseline} · {detail.baselineState} · {detail.softwareBuildId?'verification build selected':'no 1.6 verification build selected'}</p></div><div className="readinessSummary"><b>{detail.readiness.gates.filter(x=>x.complete).length}/{detail.readiness.gates.length}</b><span>release gates complete</span></div>{detail.state==='Released'?<div className="releasedSeal">✓ RELEASED<br/><small>{detail.releaseHash?.slice(0,16)}…</small></div>:<button disabled={!detail.readiness.readyForRelease} onClick={()=>call('release',{actorId:'release.manager'})}>Release FMS {detail.release}</button>}</section>
 <section className="gateGrid">{detail.readiness.gates.map(g=><article className={g.complete?'complete':'blocked'} key={g.code}><div><span>{g.complete?'✓':'!'}</span><b>{g.name}</b></div><strong>{g.completed}/{g.total}</strong><p>{g.complete?'Gate complete.':g.detail}</p><small>{g.complete?'Configuration evidence is current.':g.action}</small></article>)}</section>
 <div className="campaignGrid"><section className="campaignCard impacts"><div className="campaignTitle"><div><h2>Change-impact closure</h2><p>Requirement, traceability, verification, and document dispositions</p></div><b>{detail.impacts.filter(x=>x.state==='Pending').length} pending</b></div>{detail.impacts.map(x=><article key={x.id}><div><span role="button" tabIndex={0} onClick={()=>onOpenScr(x.scrId)}>{x.scr}</span><i className={x.state.toLowerCase()}>{x.state}</i></div><b>{x.kind} · {x.artifactReference}</b><p>{x.description}</p>{x.rationale&&<small>{x.rationale}</small>}{x.state==='Pending'&&<button onClick={()=>setImpact(x)}>Disposition impact</button>}</article>)}</section>
 <aside><section className="campaignCard"><div className="campaignTitle"><div><h2>Verification build</h2><p>Exact build used for release evidence</p></div></div><select value={detail.softwareBuildId??''} onChange={e=>call('verification-build',{softwareBuildId:e.target.value,actorId:'release.manager'})}><option value="">Select FMS {detail.release} build…</option>{builds.filter(x=>x.releaseId===detail.releaseId).map(x=><option value={x.id} key={x.id}>{x.buildNumber}</option>)}</select></section>
 <section className="campaignCard"><div className="campaignTitle"><div><h2>Ordered release approval</h2><p>Unanimous authorization required</p></div></div>{detail.approvals.map(x=><div className="releaseApprover" key={x.position}><span>{x.position+1}</span><div><b>{x.approverName}</b><small>{x.approverId} · {x.state}</small></div></div>)}{!detail.approvals.length&&<button disabled={detail.readiness.gates.some(x=>x.code!=='release_approval'&&!x.complete)} onClick={()=>call('review',{actorId:'release.manager',approvers:[{userId:'systems.lead',name:'Systems Engineering Lead'},{userId:'software.lead',name:'Software Engineering Lead'},{userId:'program.manager',name:'Program Manager'}]})}>Start release review</button>}{activeApproval&&<button onClick={()=>call('approve',{actorId:activeApproval.approverId})}>Approve as {activeApproval.approverName}</button>}</section>
 <section className="campaignCard"><div className="campaignTitle"><div><h2>Campaign history</h2><p>Append-only release events</p></div></div>{detail.events.map((x,i)=><div className="campaignEvent" key={i}><i/><div><b>{x.eventType.replace(/([A-Z])/g,' $1').trim()}</b><p>{x.detail}</p><small>{x.actorId} · {new Date(x.occurredAt).toLocaleString()}</small></div></div>)}</section></aside></div>
 {comparison&&<section className="campaignCard comparison"><div className="campaignTitle"><div><h2>FMS {comparison.fromRelease} → {comparison.toRelease}</h2><p>{comparison.toMaterialized?'Effective baseline comparison':'Proposed change comparison while 1.6 remains in work'}</p></div></div><div className="comparisonStats">{Object.entries(comparison.summary).map(([k,v])=><article key={k}><b>{v}</b><span>{k}</span></article>)}</div>{comparison.proposed.map(x=><article className="proposedChange" key={`${x.scr}-${x.displayNumber}`}><span>{x.scr}</span><b>{x.displayNumber} · {x.kind}</b><p>{x.statement}</p><small>{x.type} · {x.level} · {x.state}</small></article>)}</section>}</>}
 {impact&&<div className="campaignModal"><div><p className="eyebrow">{impact.scr} / {impact.kind}</p><h2>Disposition {impact.artifactReference}</h2><p>{impact.description}</p><textarea value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Required rationale and evidence of disposition"/><div><button className="outline" onClick={()=>setImpact(undefined)}>Cancel</button><button disabled={!rationale.trim()} onClick={()=>disposition('NotApplicable')}>Not applicable</button><button disabled={!rationale.trim()} onClick={()=>disposition('Addressed')}>Mark addressed</button></div></div></div>}
 </main>}
