import { useCallback, useEffect, useRef, useState } from "react";
import { stateLabel } from './presentation'
import type { FormEvent } from "react";
import "./ReqIfExchangeCenter.css";

type Job={id:string;direction:"Import"|"Export";state:string;fileName:string;sha256:string;requirementCount:number;hierarchyCount:number;relationCount:number;attachmentCount:number;warningCount:number;errorCount:number;createdBy:string;createdAt:string;createdScrId?:string;downloadUrl:string};
type PreviewItem={externalId:string;identifier:string;level:string;statement:string;valid:boolean;errors:string[]};
type Preview={reqIfVersion:string;sourceTool:string;items:PreviewItem[];hierarchyCount:number;relationCount:number;attachmentCount:number;warnings:string[]};
type Overview={standard:string;profile:string;coverage:{key:string;label:string;state:string}[];metrics:{exchanges:number;exports:number;imports:number;ready:number;attention:number};jobs:Job[]};

const when=(value:string)=>new Date(value).toLocaleString();
export default function ReqIfExchangeCenter({api,projectId,releaseId,onError}:{api:string;projectId:string;releaseId:string;onError:(value:string)=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<Overview>(),[preview,setPreview]=useState<Preview>(),[selected,setSelected]=useState<Job>(),[busy,setBusy]=useState(""),[drag,setDrag]=useState(false);const file=useRef<HTMLInputElement>(null);
 const load=useCallback(async()=>{const response=await fetch(`${api}/api/reqif/overview?projectId=${projectId}`);if(response.ok)setData(await response.json())},[api,projectId]);useEffect(()=>{load()},[load]);
 const exportPackage=async()=>{setBusy("Building lossless package");onError("");try{const response=await fetch(`${api}/api/reqif/exports`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({projectId,releaseId})});const body=await response.json();if(!response.ok)throw new Error(body.error||"ReqIF export failed.");await load();location.href=`${api}${body.downloadUrl}`}catch(error){onError((error as Error).message)}finally{setBusy("")}};
 const upload=async(selectedFile?:File)=>{if(!selectedFile)return;setBusy("Inspecting package");setPreview(undefined);onError("");try{const form=new FormData();form.append("file",selectedFile);const response=await fetch(`${api}/api/reqif/imports/preview?projectId=${projectId}`,{method:"POST",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||"ReqIF preview failed.");setSelected(body.job);setPreview(body.preview);setOpen(true);await load()}catch(error){onError((error as Error).message)}finally{setBusy("")}};
 const inspect=async(job:Job)=>{setSelected(job);setPreview(undefined);setOpen(true);if(job.direction==="Import"){const response=await fetch(`${api}/api/reqif/jobs/${job.id}`);if(response.ok){const body=await response.json();setPreview(body.preview)}}};
 const commit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const form=new FormData(event.currentTarget);setBusy("Creating controlled Draft");onError("");try{const response=await fetch(`${api}/api/reqif/jobs/${selected.id}/commit`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({targetReleaseId:releaseId,title:form.get("title"),problem:"Requirements received through a governed ReqIF 1.2 exchange require configuration-controlled incorporation.",analysis:`Validated ${selected.requirementCount} requirements, ${selected.hierarchyCount} hierarchy nodes, and ${selected.relationCount} relations before controlled commit.`,solution:"Introduce the validated requirements through the normal AeroLink review, approval, baseline, and release lifecycle.",type:form.get("type")})});const body=await response.json();if(!response.ok)throw new Error(body.error||"Controlled commit failed.");setSelected({...selected,state:"Committed",createdScrId:body.id});await load()}catch(error){onError((error as Error).message)}finally{setBusy("")}};
 const latest=data?.jobs[0];
 return <>
  <aside className="integrationPanel reqifLaunch"><div className="integrationPanelHead"><div><span>REQIF 1.2 EXCHANGE</span><h2>Round-trip gateway</h2><p>Preserve structure and provenance while every inbound change stays governed.</p></div><button onClick={()=>setOpen(true)}>Open center</button></div>
   <div className="reqifLaunchPulse"><i>1.2</i><div><b>{data?.metrics.exchanges??0} governed exchanges</b><span>{data?.metrics.attention?`${data.metrics.attention} need reconciliation`:"All recorded packages are reconciled"}</span></div></div>
   <div className="reqifMiniCoverage">{data?.coverage.slice(0,4).map(item=><span key={item.key}>✓ {item.label}</span>)}</div>
   <div className="reqifLaunchActions"><button onClick={exportPackage} disabled={!!busy}>{busy||"Export .reqifz"}</button><button className="primary" onClick={()=>file.current?.click()} disabled={!!busy}>Preview import</button><input ref={file} hidden type="file" accept=".reqif,.reqifz" onChange={event=>upload(event.target.files?.[0])}/></div>
   {latest&&<button className="reqifLatest" onClick={()=>inspect(latest)}><span><b>{latest.fileName}</b><small>{latest.direction} · {when(latest.createdAt)}</small></span><strong>{latest.state} →</strong></button>}
  </aside>
  {open&&<div className="reqifOverlay" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><main role="dialog" aria-modal="true" aria-labelledby="reqif-title" className="reqifCenter">
   <header><div><p className="eyebrow">OPEN DIGITAL THREAD / CONTROLLED INTERCHANGE</p><h1 id="reqif-title">ReqIF Exchange Center</h1><p>Portable requirements without surrendering review, approval, traceability, or configuration control.</p></div><div><button onClick={exportPackage} disabled={!!busy}>↓ Export package</button><button className="close" onClick={()=>setOpen(false)} aria-label="Close ReqIF Exchange Center">×</button></div></header>
   <section className="reqifKpis"><article><span>EXCHANGES</span><b>{data?.metrics.exchanges??0}</b><small>Audited packages</small></article><article><span>EXPORTS</span><b>{data?.metrics.exports??0}</b><small>Portable baselines</small></article><article><span>READY</span><b>{data?.metrics.ready??0}</b><small>Validated actions</small></article><article className={(data?.metrics.attention??0)>0?"warn":"good"}><span>RECONCILIATION</span><b>{data?.metrics.attention??0}</b><small>{data?.metrics.attention?"Need decisions":"No blockers"}</small></article></section>
   <section className="reqifCoverage"><div><span>ROUND-TRIP CONTRACT</span><h2>AeroLink lossless profile</h2><p>The source package remains immutable while supported lifecycle content is mapped explicitly.</p></div><div>{data?.coverage.map(item=><article key={item.key}><i>✓</i><span>{item.label}</span><b>{stateLabel(item.state)}</b></article>)}</div></section>
   <section className="reqifWorkbench"><div className="reqifDrop" onDragEnter={event=>{event.preventDefault();setDrag(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={()=>setDrag(false)} onDrop={event=>{event.preventDefault();setDrag(false);upload(event.dataTransfer.files[0])}} data-drag={drag}><i>↥</i><h2>{busy||"Preview an inbound package"}</h2><p>Drop a .reqif or .reqifz file. XML entities, unsafe archive paths, expansion bombs, duplicates, and identifier collisions are checked before commit.</p><button onClick={()=>file.current?.click()} disabled={!!busy}>Choose ReqIF package</button></div>
    <div className="reqifHistory"><div className="reqifSectionHead"><div><span>EXCHANGE LEDGER</span><h2>Recent packages</h2></div><b>{data?.jobs.length??0}</b></div>{data?.jobs.length?data.jobs.slice(0,8).map(job=><button className={selected?.id===job.id?"selected":""} key={job.id} onClick={()=>inspect(job)}><i className={job.direction.toLowerCase()}>{job.direction==="Export"?"↓":"↑"}</i><span><b>{job.fileName}</b><small>{job.requirementCount} requirements · {job.relationCount} relations · {when(job.createdAt)}</small></span><strong className={job.errorCount?"attention":""}>{job.errorCount?`${job.errorCount} issue(s)`:job.state}</strong></button>):<p className="reqifEmpty">No exchange packages have been recorded.</p>}</div>
   </section>
   {selected&&<section className="reqifInspector"><div className="reqifSectionHead"><div><span>{selected.direction.toUpperCase()} INSPECTION</span><h2>{selected.fileName}</h2></div><a href={`${api}${selected.downloadUrl}`}>Download source ↓</a></div><div className="reqifInspectorStats"><span><b>{selected.requirementCount}</b> requirements</span><span><b>{selected.hierarchyCount}</b> hierarchy nodes</span><span><b>{selected.relationCount}</b> relations</span><span><b>{selected.attachmentCount}</b> attachments</span><span className={selected.errorCount?"attention":""}><b>{selected.errorCount}</b> errors</span></div>
    {preview&&<><div className="reqifWarnings">{preview.warnings.map(item=><p key={item}>△ {item}</p>)}</div><div className="reqifPreviewTable"><div><span>IDENTIFIER</span><span>LEVEL</span><span>STATEMENT</span><span>RESULT</span></div>{preview.items.slice(0,12).map((item,index)=><article key={`${item.externalId}-${index}`}><b>{item.identifier||"Unmapped"}</b><span>{item.level}</span><p>{item.statement||item.errors.join(" · ")}</p><strong className={item.valid?"valid":"invalid"}>{item.valid?"Ready":`${item.errors.length} issue(s)`}</strong></article>)}</div></>}
    {selected.direction==="Import"&&selected.state==="Ready"&&<form className="reqifCommit" onSubmit={commit}><div><span>CONTROLLED COMMIT</span><h3>Create a Draft change package</h3><p>Import never bypasses engineering review. It proposes requirements into the active release.</p></div><label>Change package title<input name="title" defaultValue={`Import ${selected.fileName}`} required/></label><label>Scope<select name="type" defaultValue="System"><option>System</option><option>Software</option></select></label><button disabled={!!busy}>{busy||`Create Draft with ${selected.requirementCount} requirements`}</button></form>}
    {selected.createdScrId&&<div className="reqifCommitted"><i>✓</i><div><b>Controlled Draft created</b><span>The exchange is locked to change request {selected.createdScrId}. Normal review and baseline controls now apply.</span></div></div>}
   </section>}
  </main></div>}
 </>;
}
