import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import type { AuthUser } from './IdentityCenter'
import ControlledAuthoringCenter from './ControlledAuthoringCenter'
import './RequirementsWorkspace.css'

type Field={id:string;key:string;label:string;type:string;isRequired:boolean;sortOrder:number;optionsJson:string}
type Schema={id:string;key:string;name:string;appliesTo:string;description:string;version:number;fields:Field[]}
type Section={id:string;heading:string;position:number;count:number}
type Specification={id:string;documentNumber:string;title:string;level:string;description:string;nodeCount:number;sections:Section[]}
type SavedView={id:string;name:string;queryJson:string;columnsJson:string;isShared:boolean;owned:boolean}
type Requirement={id:string;baseNumber:string;displayNumber:string;level:string;revisionId:string;revision:number;statement:string;rationale:string;verificationMethod:string;state:string;sourceScrId:string;createdAt:string;richText:string;attributesJson:string;tagsJson:string;commentCount:number;openCommentCount:number}
type Workspace={page:number;pageSize:number;totalCount:number;totalPages:number;queryElapsedMs:number;schemas:Schema[];specifications:Specification[];views:SavedView[];items:Requirement[]}
type History={id:string;revision:number;displayNumber:string;statement:string;rationale:string;verificationMethod:string;state:string;sourceScrId:string;sourceScr:string;createdAt:string;attributesJson:string;tagsJson:string}
type Detail={id:string;baseNumber:string;level:string;history:History[];placements:{id:string;documentNumber:string;title:string;section:string;position:number}[];traceCount:number;testCoverageCount:number}
type Comment={id:string;parentCommentId?:string;body:string;mentionsJson:string;state:string;createdBy:string;createdAt:string;resolvedBy?:string;resolvedAt?:string;disposition?:string}
type ImportRow={rowNumber:number;identifier:string;level:string;statement:string;rationale:string;verificationMethod:string;valid:boolean;errors:string[]}
type ImportPreview={id:string;fileName:string;sha256:string;total:number;validRows:number;invalidRows:number;rows:ImportRow[]}
type Release={id:string;version:string;isReleased:boolean}
type Props={api:string;projectId:string;releases:Release[];user:AuthUser;initialViewId?:string;onBack:()=>void;onOpenScr:(id:string)=>void}

const parseTags=(json:string)=>{try{return JSON.parse(json) as string[]}catch{return []}}

export default function RequirementsWorkspace({api,projectId,releases,user,initialViewId,onBack,onOpenScr}:Props){
 const appliedInitialView=useRef(false)
 const [data,setData]=useState<Workspace>(),[search,setSearch]=useState(''),[level,setLevel]=useState(''),[verification,setVerification]=useState(''),[tag,setTag]=useState(''),[stateFilter,setStateFilter]=useState(''),[owner,setOwner]=useState(''),[sourceScr,setSourceScr]=useState(''),[openComments,setOpenComments]=useState(false),[sort,setSort]=useState('identifier'),[showAdvanced,setShowAdvanced]=useState(false),[showControl,setShowControl]=useState(false),[specificationId,setSpecificationId]=useState(''),[page,setPage]=useState(1),[mode,setMode]=useState<'table'|'document'>('table'),[selectedIds,setSelectedIds]=useState<string[]>([]),[selected,setSelected]=useState<Requirement>(),[detail,setDetail]=useState<Detail>(),[comments,setComments]=useState<Comment[]>([]),[inspectorTab,setInspectorTab]=useState<'details'|'history'|'discussion'>('details'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[showImport,setShowImport]=useState(false),[importPreview,setImportPreview]=useState<ImportPreview>(),[showSave,setShowSave]=useState(false),[showSchema,setShowSchema]=useState(false),[bulkTag,setBulkTag]=useState(''),[bulkPreview,setBulkPreview]=useState<{id:string;requested:number;valid:number;rejected:number;operation:string}>(),[redline,setRedline]=useState<{from:number;to:number;statement:{kind:string;text:string}[];rationale:{kind:string;text:string}[];verificationChanged:boolean;fromVerification:string;toVerification:string}>()
 const params=useMemo(()=>{const p=new URLSearchParams({projectId,page:String(page),pageSize:'100',sort});if(search)p.set('search',search);if(level)p.set('level',level);if(verification)p.set('verification',verification);if(tag)p.set('tag',tag);if(stateFilter)p.set('state',stateFilter);if(owner)p.set('owner',owner);if(sourceScr)p.set('sourceScr',sourceScr);if(openComments)p.set('openComments','true');if(specificationId)p.set('specificationId',specificationId);return p},[projectId,page,search,level,verification,tag,stateFilter,owner,sourceScr,openComments,sort,specificationId])
 const load=useCallback(async()=>{const response=await fetch(`${api}/api/enterprise-requirements/workspace?${params}`);if(response.ok){setData(await response.json());setError('')}else setError((await response.json()).error||'Requirements workspace could not be loaded.')},[api,params])
 useEffect(()=>{const timer=setTimeout(load,180);return()=>clearTimeout(timer)},[load])
 const loadComments=async(artifactId:string)=>{const response=await fetch(`${api}/api/enterprise-requirements/${artifactId}/comments`);if(response.ok)setComments(await response.json())}
 const open=async(item:Requirement)=>{setSelected(item);setInspectorTab('details');const [a,b]=await Promise.all([fetch(`${api}/api/enterprise-requirements/${item.id}`),fetch(`${api}/api/enterprise-requirements/${item.id}/comments`)]);if(a.ok)setDetail(await a.json());if(b.ok)setComments(await b.json())}
 const toggle=(id:string)=>setSelectedIds(x=>x.includes(id)?x.filter(y=>y!==id):[...x,id])
 const clearFilters=()=>{setSearch('');setLevel('');setVerification('');setTag('');setStateFilter('');setOwner('');setSourceScr('');setOpenComments(false);setSort('identifier');setSpecificationId('');setPage(1)}
 const applyView=(view:SavedView)=>{try{const q=JSON.parse(view.queryJson);setSearch(q.search||'');setLevel(q.level||'');setVerification(q.verification||'');setTag(q.tag||'');setStateFilter(q.state||'');setOwner(q.owner||'');setSourceScr(q.sourceScr||'');setOpenComments(!!q.openComments);setSort(q.sort||'identifier');setSpecificationId(q.specificationId||'');setPage(1)}catch{setError('Saved view configuration is invalid.')}}
 useEffect(()=>{if(!appliedInitialView.current&&initialViewId&&data?.views.length){const view=data.views.find(x=>x.id===initialViewId);if(view){appliedInitialView.current=true;applyView(view)}}},[data?.views,initialViewId])
 const saveView=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const response=await fetch(`${api}/api/enterprise-requirements/views`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,name:f.get('name'),isShared:f.has('shared'),queryJson:JSON.stringify({search,level,verification,tag,state:stateFilter,owner,sourceScr,openComments,sort,specificationId}),columnsJson:'["identifier","statement","level","verification","state","comments"]'})});if(!response.ok){setError((await response.json()).error);return}setShowSave(false);await load()}
 const addComment=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!selected)return;const form=e.currentTarget;const artifactId=selected.id;const f=new FormData(form);const body=String(f.get('body'));const mentions=[...body.matchAll(/@([a-z0-9._-]+)/gi)].map(x=>x[1]);const response=await fetch(`${api}/api/enterprise-requirements/${artifactId}/comments`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({revisionId:selected.revisionId,body,mentions})});if(!response.ok){setError((await response.json()).error);return}form.reset();setInspectorTab('discussion');await loadComments(artifactId);await load()}
 const resolveComment=async(id:string)=>{const disposition=window.prompt('Disposition or resolution rationale (optional):')??'';const response=await fetch(`${api}/api/enterprise-requirements/comments/${id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({disposition})});if(response.ok&&selected){await open(selected);await load()}}
 const compare=async()=>{if(!selected||!detail||detail.history.length<2)return;const [to,from]=detail.history;const response=await fetch(`${api}/api/enterprise-requirements/${selected.id}/redline?fromRevisionId=${from.id}&toRevisionId=${to.id}`);if(response.ok)setRedline(await response.json())}
 const previewBulk=async()=>{if(!bulkTag.trim()||!selectedIds.length)return;const spec=data?.specifications.find(x=>x.id===specificationId);const response=await fetch(`${api}/api/enterprise-requirements/bulk/preview`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,artifactIds:selectedIds,tag:bulkTag,specificationId:spec?.id||null,sectionId:spec?.sections[0]?.id||null})});if(response.ok)setBulkPreview(await response.json());else setError((await response.json()).error)}
 const commitBulk=async()=>{if(!bulkPreview)return;setBusy(true);const response=await fetch(`${api}/api/enterprise-requirements/bulk/${bulkPreview.id}/commit`,{method:'POST'});setBusy(false);if(!response.ok){setError((await response.json()).error);return}setBulkPreview(undefined);setBulkTag('');setSelectedIds([]);await load()}
 const previewImport=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);const response=await fetch(`${api}/api/enterprise-requirements/import/preview?projectId=${projectId}`,{method:'POST',body:f});setBusy(false);if(!response.ok){setError((await response.json()).error);return}setImportPreview(await response.json())}
 const commitImport=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!importPreview)return;const f=new FormData(e.currentTarget);const body={targetReleaseId:f.get('targetReleaseId'),baseNumber:f.get('baseNumber'),title:f.get('title'),problem:f.get('problem'),analysis:f.get('analysis'),solution:f.get('solution'),type:f.get('type')};setBusy(true);const response=await fetch(`${api}/api/enterprise-requirements/import/${importPreview.id}/commit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});setBusy(false);if(!response.ok){setError((await response.json()).error);return}const result=await response.json();setShowImport(false);setImportPreview(undefined);onOpenScr(result.id)}
 const allSelected=data?.items.length&&data.items.every(x=>selectedIds.includes(x.id))
 return <main className="reqWorkspace">
  <header className="reqHeader"><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">ENTERPRISE REQUIREMENTS / CONTROLLED AUTHORING</p><h1>Requirements Workspace</h1><p>Structure, discover, collaborate on, and govern every requirement revision at scale.</p></div><div className="reqHeaderActions"><span className="activeAuthor">{user.displayName}<small>authenticated author</small></span><button className="secondary" onClick={()=>{setSelected(undefined);setShowControl(true)}}>◎ My work</button><button className="secondary" onClick={()=>setShowSchema(true)}>⚙ Schemas</button><button className="secondary" onClick={()=>setShowSave(true)}>☆ Save view</button><button onClick={()=>setShowImport(true)}>⇧ Import requirements</button></div></header>
  {error&&<div className="workspaceError">{error}</div>}
  <section className="reqCommand"><div className="reqSearch"><span>⌕</span><input aria-label="Search requirements" value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}} placeholder="Search identifier, statement, rationale…"/><kbd>/{data?.totalCount.toLocaleString()??0}</kbd></div><select aria-label="Level filter" value={level} onChange={e=>{setLevel(e.target.value);setPage(1)}}><option value="">All levels</option><option>System</option><option value="HighLevel">Software HLR</option><option value="LowLevel">Software LLR</option></select><select aria-label="Verification filter" value={verification} onChange={e=>{setVerification(e.target.value);setPage(1)}}><option value="">All verification</option><option>Test</option><option>Analysis</option><option>Inspection</option><option>Demonstration</option></select><input className="tagFilter" value={tag} onChange={e=>setTag(e.target.value)} placeholder="Filter tag"/><button className={showAdvanced?'advanced active':'advanced'} onClick={()=>setShowAdvanced(x=>!x)}>Advanced</button><button className="clear" onClick={clearFilters}>Clear</button><div className="modeSwitch"><button className={mode==='table'?'active':''} onClick={()=>setMode('table')}>▦</button><button className={mode==='document'?'active':''} onClick={()=>setMode('document')}>☷</button></div></section>
  {showAdvanced&&<section className="advancedQuery"><label>Lifecycle state<select value={stateFilter} onChange={e=>{setStateFilter(e.target.value);setPage(1)}}><option value="">Any state</option><option>Active</option><option>Superseded</option><option>Retired</option></select></label><label>Owner<input value={owner} onChange={e=>{setOwner(e.target.value);setPage(1)}} placeholder="username"/></label><label>Source SCR/SWCR<input value={sourceScr} onChange={e=>{setSourceScr(e.target.value);setPage(1)}} placeholder="SCR number or title"/></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="identifier">Identifier</option><option value="updated">Recently revised</option><option value="verification">Verification method</option><option value="state">Lifecycle state</option></select></label><label className="advancedCheck"><input type="checkbox" checked={openComments} onChange={e=>setOpenComments(e.target.checked)}/> Open discussions only</label><span>{data?.queryElapsedMs??0} ms server query</span></section>}
  <div className={`reqLayout ${selected?'inspecting':''}`}><aside className="specRail"><div className="railTitle"><b>Specifications</b><span>{data?.specifications.length??0}</span></div><button className={!specificationId?'active':''} onClick={()=>{setSpecificationId('');setPage(1)}}><i>◫</i><div><b>All requirements</b><small>{data?.totalCount.toLocaleString()??0} visible</small></div></button>{data?.specifications.map(spec=><div className="specGroup" key={spec.id}><button className={specificationId===spec.id?'active':''} onClick={()=>{setSpecificationId(spec.id);setLevel('');setPage(1)}}><i>{spec.level==='System'?'S':spec.level==='HighLevel'?'H':'L'}</i><div><b>{spec.documentNumber}</b><small>{spec.nodeCount.toLocaleString()} · {spec.title}</small></div></button>{specificationId===spec.id&&<div className="sectionTree">{spec.sections.map(x=><span key={x.id}><i/>{x.heading}<small>{x.count}</small></span>)}</div>}</div>)}<div className="savedViews"><div className="railTitle"><b>Saved views</b><span>{data?.views.length??0}</span></div>{data?.views.map(view=><button onClick={()=>applyView(view)} key={view.id}><i>{view.isShared?'◉':'○'}</i><div><b>{view.name}</b><small>{view.isShared?'Shared':'Personal'}</small></div></button>)}</div></aside>
   <section className="reqResults"><div className="resultSummary"><div><b>{data?.totalCount.toLocaleString()??0} requirements</b><span>Page {data?.page??1} of {data?.totalPages??1} · exact current revisions</span></div><div className="confidence"><i/> Permission-aware · Live index</div></div>
   {mode==='table'?<div className="reqTable"><div className="reqTableHead"><label><input type="checkbox" checked={!!allSelected} onChange={()=>setSelectedIds(allSelected?[]:data?.items.map(x=>x.id)??[])}/></label><span>Identifier & statement</span><span>Level</span><span>Verification</span><span>State</span><span>Discussion</span></div>{data?.items.map(item=><article className={selected?.id===item.id?'selected':''} key={item.id}><label><input type="checkbox" checked={selectedIds.includes(item.id)} onChange={()=>toggle(item.id)}/></label><button onClick={()=>open(item)}><b>{item.displayNumber}</b><p>{item.statement||'Retired requirement'}</p><div className="miniTags">{parseTags(item.tagsJson).slice(0,3).map(x=><small key={x}>{x}</small>)}</div></button><span>{item.level==='HighLevel'?'HLR':item.level==='LowLevel'?'LLR':'System'}</span><span>{item.verificationMethod}</span><i className={item.state.toLowerCase()}>{item.state}</i><span className={item.openCommentCount?'hasComments':''}>◌ {item.commentCount}{item.openCommentCount>0&&<em>{item.openCommentCount} open</em>}</span></article>)}</div>:<div className="documentMode">{data?.items.map(item=><article key={item.id} onClick={()=>open(item)}><div><b>{item.displayNumber}</b><span>{item.level} · Rev {item.revision}</span></div><p>{item.statement}</p><footer><span>Verification: {item.verificationMethod}</span><span>{item.commentCount} comments</span><span>{item.state}</span></footer></article>)}</div>}
   <div className="pager"><button disabled={(data?.page??1)<=1} onClick={()=>setPage(x=>x-1)}>← Previous</button><span>{((data?.page??1)-1)*(data?.pageSize??100)+1}–{Math.min((data?.page??1)*(data?.pageSize??100),data?.totalCount??0)} of {data?.totalCount.toLocaleString()??0}</span><button disabled={(data?.page??1)>=(data?.totalPages??1)} onClick={()=>setPage(x=>x+1)}>Next →</button></div></section>
   {selected&&<aside className="requirementInspector"><div className="inspectorTop"><div><span>{selected.level.toUpperCase()} REQUIREMENT</span><h2>{selected.displayNumber}</h2></div><button onClick={()=>{setSelected(undefined);setDetail(undefined)}}>×</button></div><div className="inspectorTabs"><button className={inspectorTab==='details'?'active':''} onClick={()=>setInspectorTab('details')}>Details</button><button className={inspectorTab==='history'?'active':''} onClick={()=>setInspectorTab('history')}>History</button><button className={inspectorTab==='discussion'?'active':''} onClick={()=>setInspectorTab('discussion')}>Discussion <span>{comments.length}</span></button></div>{inspectorTab==='details'&&<div className="inspectorBody"><div className="controlledBanner"><b>✓ Controlled revision</b><span>Content changes require an SCR/SWCR</span></div><button className="impactLaunch" onClick={()=>setShowControl(true)}>Analyze impact &amp; propose change →</button><h3>Requirement statement</h3><div className="richRequirement">{selected.statement}</div><dl><div><dt>Verification</dt><dd>{selected.verificationMethod}</dd></div><div><dt>State</dt><dd>{selected.state}</dd></div><div><dt>Source authority</dt><dd><button onClick={()=>onOpenScr(selected.sourceScrId)}>Open SCR →</button></dd></div><div><dt>Trace links</dt><dd>{detail?.traceCount??'—'}</dd></div><div><dt>Test coverage</dt><dd>{detail?.testCoverageCount??'—'} procedures</dd></div></dl><h3>Classification</h3><div className="tagCloud">{parseTags(selected.tagsJson).map(x=><span key={x}>{x}</span>)}{!parseTags(selected.tagsJson).length&&<small>No additional tags</small>}</div><h3>Specification placement</h3>{detail?.placements.map(x=><div className="placement" key={x.id}><b>{x.documentNumber}</b><span>{x.section}</span></div>)}</div>}{inspectorTab==='history'&&<div className="inspectorBody"><div className="historyLead"><div><b>{detail?.history.length??0} immutable revisions</b><span>Complete controlled history</span></div><button disabled={(detail?.history.length??0)<2} onClick={compare}>Compare latest</button></div>{detail?.history.map(x=><article className="revisionCard" key={x.id}><div><b>{x.displayNumber}</b><i>{x.state}</i></div><p>{x.statement}</p><small>{x.sourceScr} · {new Date(x.createdAt).toLocaleDateString()}</small></article>)}</div>}{inspectorTab==='discussion'&&<div className="discussionPane"><form onSubmit={addComment}><textarea name="body" placeholder="Add an attributable comment. Use @username to mention someone." required/><button>Add comment</button></form>{comments.map(c=><article key={c.id} className={c.state.toLowerCase()}><div><b>{c.createdBy}</b><span>{new Date(c.createdAt).toLocaleString()}</span></div><p>{c.body}</p>{c.disposition&&<small>Disposition: {c.disposition}</small>}<footer><i>{c.state}</i>{c.state==='Open'&&<button onClick={()=>resolveComment(c.id)}>Resolve / disposition</button>}</footer></article>)}</div>}</aside>}
  </div>
  {!!selectedIds.length&&<div className="bulkBar"><b>{selectedIds.length} selected</b><span>Apply one governed operation to exact artifacts</span><input value={bulkTag} onChange={e=>setBulkTag(e.target.value)} placeholder="Classification tag"/><button disabled={!bulkTag.trim()} onClick={previewBulk}>Preview bulk change</button><button className="quiet" onClick={()=>setSelectedIds([])}>Clear</button></div>}
  {bulkPreview&&<div className="reqModal"><div><p className="eyebrow">GOVERNED BULK OPERATION</p><h2>Review before commit</h2><p>{bulkPreview.operation}</p><div className="previewStats"><b>{bulkPreview.valid}<small>valid</small></b><b>{bulkPreview.rejected}<small>rejected</small></b><b>{bulkPreview.requested}<small>requested</small></b></div><div className="modalActions"><button className="secondary" onClick={()=>setBulkPreview(undefined)}>Cancel</button><button disabled={busy} onClick={commitBulk}>{busy?'Committing…':'Commit attributable change'}</button></div></div></div>}
  {showSave&&<div className="reqModal"><form onSubmit={saveView}><p className="eyebrow">PERSONAL & SHARED WORKLISTS</p><h2>Save current view</h2><p>The exact filters and columns become a reusable, permission-aware worklist.</p><label>View name<input name="name" required autoFocus/></label><label className="check"><input type="checkbox" name="shared"/> Share with authorized Program members</label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setShowSave(false)}>Cancel</button><button>Save view</button></div></form></div>}
  {showSchema&&<div className="reqModal schemaModal"><div><p className="eyebrow">PROGRAM CONFIGURATION</p><h2>Artifact schemas</h2><p>Versioned definitions describe fields and validation without changing the application database.</p>{data?.schemas.map(s=><article key={s.id}><div><b>{s.name}</b><span>{s.appliesTo} · v{s.version}</span></div><p>{s.description}</p><div>{s.fields.map(f=><small key={f.id}>{f.label}<i>{f.type}{f.isRequired?' · required':''}</i></small>)}</div></article>)}<div className="modalActions"><button onClick={()=>setShowSchema(false)}>Done</button></div></div></div>}
  {showImport&&<div className="reqModal importModal"><div><button className="modalClose" onClick={()=>{setShowImport(false);setImportPreview(undefined)}}>×</button><p className="eyebrow">GOVERNED INTERCHANGE CENTER</p><h2>Import requirements</h2><p>CSV and XLSX rows are mapped, validated, hashed, and previewed. Commit creates a Draft SCR/SWCR—never approved requirements.</p>{!importPreview?<form onSubmit={previewImport}><div className="dropZone"><span>⇧</span><b>Select CSV or XLSX</b><small>Columns: Identifier, Level, Statement, Rationale, VerificationMethod · 25 MB maximum</small><input aria-label="Requirements import file" type="file" name="file" accept=".csv,.xlsx" required/></div><button disabled={busy}>{busy?'Validating…':'Validate & preview'}</button></form>:<><div className="importIdentity"><div><b>{importPreview.fileName}</b><small>SHA-256 {importPreview.sha256.slice(0,20)}…</small></div><div><b>{importPreview.validRows}</b><span>valid</span><b className={importPreview.invalidRows?'bad':''}>{importPreview.invalidRows}</b><span>invalid</span></div></div><div className="importRows">{importPreview.rows.slice(0,10).map(r=><article className={r.valid?'valid':'invalid'} key={r.rowNumber}><span>{r.rowNumber}</span><div><b>{r.identifier||'Missing identifier'}</b><p>{r.statement||'Missing statement'}</p><small>{r.valid?`${r.level} · ${r.verificationMethod}`:r.errors.join(' · ')}</small></div></article>)}</div>{importPreview.invalidRows===0?<form className="commitImport" onSubmit={commitImport}><h3>Create controlled change package</h3><div className="importFields"><label>Type<select name="type"><option value="Software">SWCR</option><option value="System">SCR</option></select></label><label>Target release<select name="targetReleaseId" required>{releases.filter(x=>!x.isReleased).map(x=><option value={x.id} key={x.id}>{x.version}</option>)}</select></label><label>SCR/SWCR number<input name="baseNumber" pattern="[A-Z]+-[0-9]{8}" required/></label><label className="wide">Title<input name="title" required/></label><label>Problem<textarea name="problem" required/></label><label>Analysis<textarea name="analysis" required/></label><label>Solution<textarea name="solution" required/></label></div><button disabled={busy}>{busy?'Creating Draft…':`Create Draft with ${importPreview.validRows} changes`}</button></form>:<div className="importBlocked"><b>Import blocked</b><p>Correct the invalid rows in the source file and preview it again. No lifecycle data has been changed.</p></div>}</>}</div></div>}
  {redline&&<div className="reqModal redlineModal"><div><button className="modalClose" onClick={()=>setRedline(undefined)}>×</button><p className="eyebrow">CONTROLLED REDLINE / REV {redline.from} → {redline.to}</p><h2>Revision comparison</h2><h3>Statement</h3><div className="redlineText">{redline.statement.map((x,i)=><span className={x.kind} key={i}>{x.text} </span>)}</div><h3>Rationale</h3><div className="redlineText">{redline.rationale.map((x,i)=><span className={x.kind} key={i}>{x.text} </span>)}</div>{redline.verificationChanged&&<p className="verificationDiff">Verification changed: <del>{redline.fromVerification}</del> → <ins>{redline.toVerification}</ins></p>}</div></div>}
  {showControl&&<ControlledAuthoringCenter api={api} projectId={projectId} releases={releases} requirement={selected} onClose={()=>setShowControl(false)} onOpenScr={onOpenScr} onChanged={load}/>}
 </main>
}
