import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { SignatureDialog } from './IdentityCenter'
import type { AuthUser } from './IdentityCenter'
import ControlledRequirementEditor from './ControlledRequirementEditor'
import type { ControlledRequirementDraft } from './ControlledRequirementEditor'
import './ScrWorkspace.css'

type Requirement={id:string;displayNumber:string;level:'System'|'HighLevel'|'LowLevel';kind:'Introduce'|'Modify'|'Retire';statement:string;rationale:string;verificationMethod:string;richText:string;attributesJson:string;impactDispositionJson:string}
type Step={position:number;approverId:string;approverName:string;state:string;decidedAt?:string}
type Cycle={id:string;sequence:number;state:string;snapshotHash:string;startedAt:string;completedAt?:string;closureReason?:string;steps:Step[]}
type Audit={eventType:string;actorId:string;detail:string;occurredAt:string}
type ScrDetail={id:string;baseNumber:string;revision:number;displayNumber:string;type:string;title:string;problem:string;analysis:string;solution:string;authorId:string;version:number;state:string;createdAt:string;updatedAt:string;requirementChanges:Requirement[];reviewCycles:Cycle[];audit:Audit[]}
type DraftRequirement=ControlledRequirementDraft
type Approver={userId:string;name:string}
type Props={api:string;scrId:string;user:AuthUser;onBack:()=>void;onChanged:()=>Promise<void>}
const base=(display:string)=>display.replace(/\.\d{2}$/,'')
const revision=(display:string)=>Number(display.match(/\.(\d{2})$/)?.[1]??0)
const emptyRequirement=():DraftRequirement=>({baseNumber:'SWR-00000001',revision:0,level:'HighLevel',kind:'Introduce',statement:'',rationale:'',verificationMethod:'Test',richText:'',attributesJson:'{"criticality":"Normal","owner":""}',impactDispositionJson:'{"trace":"Pending","verification":"Pending","documents":"Pending","baseline":"Pending","collaboration":"Pending"}'})

export default function ScrWorkspace({api,scrId,user,onBack,onChanged}:Props){
 const [scr,setScr]=useState<ScrDetail>(),[mode,setMode]=useState<'view'|'edit'|'approvers'>('view'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[signing,setSigning]=useState(false)
 const [requirements,setRequirements]=useState<DraftRequirement[]>([]),[approvers,setApprovers]=useState<Approver[]>([{userId:'systems.reviewer',name:'Systems Engineer'},{userId:'software.lead',name:'Software Engineering Lead'},{userId:'engineering.manager',name:'Engineering Manager'}])
 const load=useCallback(async()=>{const response=await fetch(`${api}/api/scrs/${scrId}`);if(response.ok){const detail=await response.json();setScr(detail);setRequirements(detail.requirementChanges.map((x:Requirement)=>({baseNumber:base(x.displayNumber),revision:revision(x.displayNumber),level:x.level,kind:x.kind,statement:x.statement,rationale:x.rationale,verificationMethod:x.verificationMethod,richText:x.richText||x.statement,attributesJson:x.attributesJson||'{}',impactDispositionJson:x.impactDispositionJson&&x.impactDispositionJson!=='{}'?x.impactDispositionJson:emptyRequirement().impactDispositionJson}))) }},[api,scrId])
 useEffect(()=>{load()},[load])
 const call=async(path:string,body:unknown)=>{setBusy(true);setError('');const response=await fetch(`${api}/api/scrs/${scrId}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){setError((await response.json()).error||'The operation could not be completed.');setBusy(false);return false}await load();await onChanged();setBusy(false);setMode('view');return true}
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!scr)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');const response=await fetch(`${api}/api/scrs/${scr.id}/draft`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:scr.version,title:form.get('title'),problem:form.get('problem'),analysis:form.get('analysis'),solution:form.get('solution'),requirementChanges:requirements})});if(!response.ok){setError((await response.json()).error||'Draft could not be saved.');setBusy(false);return}await load();await onChanged();setBusy(false);setMode('view')}
 const updateRequirement=(index:number,key:keyof DraftRequirement,value:string|number)=>setRequirements(items=>items.map((x,i)=>i===index?{...x,[key]:value}:x))
 const move=(index:number,direction:number)=>setApprovers(items=>{const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next})
 if(!scr)return <main className="scrLoading">Loading controlled record…</main>
 const latest=[...scr.reviewCycles].sort((a,b)=>b.sequence-a.sequence)[0],active=latest?.steps.find(x=>x.state==='Active'),isAuthor=scr.authorId===user.userName||user.isAdministrator
 return <main className="scrPage">
  <header className="scrHeader"><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">CHANGE CONTROL / {scr.displayNumber}</p><h1>{scr.title}</h1><p>Revision-controlled change case and proposed lifecycle impact.</p></div><div className="headerState"><span className={`stateBadge ${scr.state.toLowerCase()}`}>{scr.state}</span><small>Record version {scr.version}</small></div></header>{error&&<div className="workspaceError">{error}</div>}
  {mode==='edit'?<form onSubmit={save} className="workspaceStack">
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Edit Draft</h2><p>Saving changes records an attributable audit event.</p></div></div><div className="editFields"><label>Title<input name="title" defaultValue={scr.title} required/></label><label>Problem<textarea name="problem" defaultValue={scr.problem} required/></label><label>Analysis<textarea name="analysis" defaultValue={scr.analysis} required/></label><label>Solution<textarea name="solution" defaultValue={scr.solution} required/></label></div></section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Controlled requirement authoring</h2><p>Rich content, schema fields, and impact dispositions are frozen into the exact SCR/SWCR review snapshot.</p></div><button type="button" className="outline" onClick={()=>setRequirements(x=>[...x,emptyRequirement()])}>+ Add requirement proposal</button></div>{requirements.map((item,index)=><ControlledRequirementEditor item={item} index={index} key={`${item.baseNumber}-${index}`} onChange={(key,value)=>updateRequirement(index,key,value)} onRemove={()=>setRequirements(x=>x.filter((_,i)=>i!==index))}/>)}</section>
   <div className="workspaceActions"><button type="button" className="outline" onClick={()=>setMode('view')}>Cancel</button><button disabled={busy}>{busy?'Saving…':'Save Draft'}</button></div>
  </form>:mode==='approvers'?<section className="workspaceCard approverSetup">
   <div className="workspaceTitle"><div><h2>Configure ordered approval</h2><p>Every selected active AeroLink user must approve in this order.</p></div></div>{approvers.map((person,index)=><div className="approverRow" key={index}><span>{index+1}</span><input aria-label={`Approver ${index+1} ID`} value={person.userId} onChange={e=>setApprovers(x=>x.map((a,i)=>i===index?{...a,userId:e.target.value}:a))}/><input aria-label={`Approver ${index+1} name`} value={person.name} readOnly/><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button className="remove" onClick={()=>setApprovers(x=>x.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className="outline addApprover" onClick={()=>setApprovers(x=>[...x,{userId:'',name:''}])}>+ Add approver</button><div className="snapshotNote"><b>Snapshot protection</b><p>Submission freezes the exact content hash. Each approver must re-authenticate to sign.</p></div><div className="workspaceActions"><button className="outline" onClick={()=>setMode('view')}>Cancel</button><button disabled={busy||!approvers.length||approvers.some(x=>!x.userId)} onClick={()=>call('submit',{expectedVersion:scr.version,approvers})}>{busy?'Submitting…':'Submit for Review'}</button></div>
  </section>:<div className="workspaceGrid"><div className="workspaceStack">
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Change case</h2><p>Problem, analysis, and proposed solution</p></div>{scr.state==='Draft'&&isAuthor&&<button className="outline" onClick={()=>setMode('edit')}>Edit Draft</button>}</div><div className="pasView">{[['P','Problem',scr.problem],['A','Analysis',scr.analysis],['S','Solution',scr.solution]].map(x=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]||'Not yet provided'}</p></div></article>)}</div></section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Requirement impact</h2><p>{scr.requirementChanges.length} proposed controlled change{scr.requirementChanges.length===1?'':'s'}</p></div></div>{scr.requirementChanges.map(item=><article className="requirementView" key={item.id}><div><b>{item.displayNumber}</b><span>{item.level} · {item.kind}</span></div><p>{item.kind==='Retire'&&!item.statement?'Requirement will be retired.':item.statement}</p><small>{item.verificationMethod} · {item.rationale||'No rationale recorded'}</small></article>)}</section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Audit history</h2><p>Append-only material events</p></div></div>{scr.audit.map((event,index)=><div className="auditRow" key={`${event.occurredAt}-${index}`}><i/><div><b>{event.eventType.replace(/([A-Z])/g,' $1').trim()}</b><p>{event.detail}</p><small>{event.actorId} · {new Date(event.occurredAt).toLocaleString()}</small></div></div>)}</section>
  </div><aside className="reviewRail"><section className="workspaceCard"><div className="workspaceTitle"><div><h2>Control status</h2><p>{scr.displayNumber}</p></div></div><dl><div><dt>State</dt><dd>{scr.state}</dd></div><div><dt>Author</dt><dd>{scr.authorId}</dd></div><div><dt>Revision</dt><dd>{scr.revision}</dd></div><div><dt>Updated</dt><dd>{new Date(scr.updatedAt).toLocaleDateString()}</dd></div></dl>{scr.state==='Draft'&&isAuthor&&<button className="primaryFull" onClick={()=>setMode('approvers')}>Configure & Submit Review</button>}</section>
   {latest&&<section className="workspaceCard"><div className="workspaceTitle"><div><h2>Review cycle {latest.sequence}</h2><p>{latest.state} · {latest.snapshotHash.slice(0,12)}…</p></div></div><div className="approvalPath">{latest.steps.map(step=><div className={`approvalStep ${step.state.toLowerCase()}`} key={step.position}><span>{step.state==='Approved'?'✓':step.position+1}</span><div><b>{step.approverName}</b><small>{step.approverId} · {step.state}</small></div></div>)}</div>{latest.closureReason&&<div className="closure"><b>Closure reason</b><p>{latest.closureReason}</p></div>}{scr.state==='InReview'&&active&&<div className="reviewActions"><p><b>{active.approverName}</b> is the active reviewer.</p>{active.approverId===user.userName?<><button disabled={busy} onClick={()=>setSigning(true)}>Review & electronically approve</button><textarea placeholder="Reason for requested changes" value={reason} onChange={e=>setReason(e.target.value)}/><button className="danger" disabled={busy||!reason.trim()} onClick={()=>call('request-changes',{expectedVersion:scr.version,reason})}>Request changes</button></>:<div className="snapshotNote"><b>Waiting for assigned reviewer</b><p>Only the assigned identity can act on this stage.</p></div>}</div>}</section>}
  </aside></div>}
  {signing&&<SignatureDialog title={`Approve ${scr.displayNumber}`} meaning="I approve this exact SCR revision and its proposed requirement changes as suitable for controlled progression." onCancel={()=>setSigning(false)} onSign={async(password,meaning)=>{const ok=await call('approve',{password,meaning,expectedVersion:scr.version});if(ok)setSigning(false)}}/>}
 </main>
}
