import { useCallback, useEffect, useRef, useState } from 'react'
import type { FormEvent } from 'react'
import { SignatureDialog } from './IdentityCenter'
import type { AuthUser } from './IdentityCenter'
import ControlledRequirementEditor from './ControlledRequirementEditor'
import type { ControlledRequirementDraft } from './ControlledRequirementEditor'
import './ScrWorkspace.css'
import './ReviewMode.css'
import PersonPicker from './PersonPicker'

type Requirement={id:string;displayNumber:string;level:'System'|'HighLevel'|'LowLevel';kind:'Introduce'|'Modify'|'Retire';statement:string;rationale:string;verificationMethod:string;richText:string;attributesJson:string;impactDispositionJson:string}
type Step={position:number;approverId:string;approverName:string;state:string;decidedAt?:string}
type Cycle={id:string;sequence:number;mode:'Sequential'|'Parallel';state:string;snapshotHash:string;startedAt:string;completedAt?:string;closureReason?:string;steps:Step[]}
type Audit={eventType:string;actorId:string;detail:string;occurredAt:string}
type ScrDetail={id:string;baseNumber:string;revision:number;displayNumber:string;projectId:string;type:string;title:string;problem:string;analysis:string;solution:string;authorId:string;version:number;state:string;createdAt:string;updatedAt:string;requirementChanges:Requirement[];reviewCycles:Cycle[];audit:Audit[]}
type DraftRequirement=ControlledRequirementDraft
type Approver={userId:string;name:string}
type EditLock={id:string;version:number;userName:string;openedAt:string;lastActivityAt:string;expiresAt:string;draftJson:string;resumed:boolean}
type LockStatus={editable:boolean;locked:boolean;sessionId?:string;holder?:string;openedAt?:string;lastActivityAt?:string;expiresAt?:string;mine?:boolean}
type ScrDraft={title:string;problem:string;analysis:string;solution:string}
type Props={api:string;scrId:string;user:AuthUser;onBack:()=>void;onChanged:()=>Promise<void>;onOpenScr:(id:string)=>void}
const base=(display:string)=>display.replace(/\.\d{2}$/,'')
const revision=(display:string)=>Number(display.match(/\.(\d{2})$/)?.[1]??0)
const emptyRequirement=():DraftRequirement=>({baseNumber:'SWR-00000001',revision:0,level:'HighLevel',kind:'Introduce',statement:'',rationale:'',verificationMethod:'Test',richText:'',attributesJson:'{"criticality":"Normal","owner":""}',impactDispositionJson:'{"trace":"Pending","verification":"Pending","documents":"Pending","baseline":"Pending","collaboration":"Pending"}'})

export default function ScrWorkspace({api,scrId,user,onBack,onChanged,onOpenScr}:Props){
 const [scr,setScr]=useState<ScrDetail>(),[mode,setMode]=useState<'view'|'edit'|'approvers'>('view'),[reviewMode,setReviewMode]=useState<'Sequential'|'Parallel'>('Sequential'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[signing,setSigning]=useState(false),[lock,setLock]=useState<EditLock>(),[lockStatus,setLockStatus]=useState<LockStatus>(),[autosaveStatus,setAutosaveStatus]=useState<'Saved'|'Saving'|'Error'|'Conflict'>('Saved'),[draft,setDraft]=useState<ScrDraft>({title:'',problem:'',analysis:'',solution:''})
 const [requirements,setRequirements]=useState<DraftRequirement[]>([]),[approvers,setApprovers]=useState<Approver[]>([{userId:'systems.reviewer',name:'Systems Engineer'},{userId:'software.lead',name:'Software Engineering Lead'},{userId:'engineering.manager',name:'Engineering Manager'}])
 const lockRef=useRef<EditLock|undefined>(undefined),draftRef=useRef(''),lastSavedRef=useRef(''),savingRef=useRef(false)
 const mapRequirements=(items:Requirement[])=>items.map((x:Requirement)=>({baseNumber:base(x.displayNumber),revision:revision(x.displayNumber),level:x.level,kind:x.kind,statement:x.statement,rationale:x.rationale,verificationMethod:x.verificationMethod,richText:x.richText||x.statement,attributesJson:x.attributesJson||'{}',impactDispositionJson:x.impactDispositionJson&&x.impactDispositionJson!=='{}'?x.impactDispositionJson:emptyRequirement().impactDispositionJson}))
 const loadStatus=useCallback(async()=>{const response=await fetch(`${api}/api/edit-sessions/status?artifactType=SCR&artifactId=${scrId}`);if(response.ok)setLockStatus(await response.json())},[api,scrId])
 const load=useCallback(async()=>{const response=await fetch(`${api}/api/scrs/${scrId}`);if(response.ok){const detail=await response.json();setScr(detail);if(mode!=='edit'){setDraft({title:detail.title,problem:detail.problem,analysis:detail.analysis,solution:detail.solution});setRequirements(mapRequirements(detail.requirementChanges))}}await loadStatus()},[api,scrId,loadStatus,mode])
 useEffect(()=>{load()},[load])
 useEffect(()=>{lockRef.current=lock},[lock])
 useEffect(()=>{draftRef.current=JSON.stringify({...draft,requirementChanges:requirements})},[draft,requirements])
 const beginEdit=async()=>{setBusy(true);setError('');const response=await fetch(`${api}/api/edit-sessions/checkout`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({artifactType:'SCR',artifactId:scrId,leaseMinutes:15})});setBusy(false);if(!response.ok){const body=await response.json();setError(body.error||'This Draft could not be checked out.');await loadStatus();return}const value:EditLock=await response.json();const recovered=JSON.parse(value.draftJson) as ScrDraft&{requirementChanges?:DraftRequirement[]};setLock(value);setDraft({title:recovered.title,problem:recovered.problem,analysis:recovered.analysis,solution:recovered.solution});if(recovered.requirementChanges)setRequirements(recovered.requirementChanges);lastSavedRef.current=value.draftJson;setAutosaveStatus('Saved');setMode('edit');await loadStatus()}
 const autosave=useCallback(async()=>{const currentLock=lockRef.current,currentDraft=draftRef.current;if(!currentLock||savingRef.current||!currentDraft||currentDraft===lastSavedRef.current)return;savingRef.current=true;setAutosaveStatus('Saving');try{const response=await fetch(`${api}/api/edit-sessions/${currentLock.id}/autosave`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:currentLock.version,draftJson:currentDraft,leaseMinutes:15})});if(!response.ok){setAutosaveStatus(response.status===409?'Conflict':'Error');setError((await response.json()).error||'Server autosave failed.');return}const value=await response.json();const next={...currentLock,version:value.version,lastActivityAt:value.updatedAt,expiresAt:value.expiresAt};setLock(next);lockRef.current=next;lastSavedRef.current=currentDraft;setAutosaveStatus('Saved')}catch{setAutosaveStatus('Error')}finally{savingRef.current=false}},[api])
 useEffect(()=>{if(mode!=='edit'||!lockRef.current)return;const saveTimer=setInterval(autosave,2500);const heartbeat=setInterval(async()=>{const current=lockRef.current;if(!current||savingRef.current)return;const response=await fetch(`${api}/api/edit-sessions/${current.id}/heartbeat`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:current.version,leaseMinutes:15})});if(response.ok){const value=await response.json();const next={...current,version:value.version,lastActivityAt:value.updatedAt,expiresAt:value.expiresAt};setLock(next);lockRef.current=next}else setAutosaveStatus('Conflict')},60000);return()=>{clearInterval(saveTimer);clearInterval(heartbeat)}},[api,autosave,mode])
 const discard=async()=>{const current=lockRef.current;if(current){const response=await fetch(`${api}/api/edit-sessions/${current.id}/discard`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:current.version,reason:'Author discarded the checked-out working copy.'})});if(!response.ok){setError((await response.json()).error||'The checkout could not be discarded.');return}}setLock(undefined);setMode('view');await load()}
 const call=async(path:string,body:unknown)=>{setBusy(true);setError('');const response=await fetch(`${api}/api/scrs/${scrId}/${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok){setError((await response.json()).error||'The operation could not be completed.');setBusy(false);return false}await load();await onChanged();setBusy(false);setMode('view');return true}
 const revise=async()=>{if(!scr)return;setBusy(true);setError('');const response=await fetch(`${api}/api/scrs/${scr.id}/next-revision`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:scr.version})});if(!response.ok){setError((await response.json()).error||'The next controlled revision could not be created.');setBusy(false);return}const next=await response.json();await onChanged();setBusy(false);onOpenScr(next.id)}
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!scr||!lockRef.current)return;setBusy(true);savingRef.current=true;setError('');const current=lockRef.current;const response=await fetch(`${api}/api/scrs/${scr.id}/draft`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:scr.version,...draft,requirementChanges:requirements,editSessionId:current.id,editSessionVersion:current.version})});savingRef.current=false;if(!response.ok){setError((await response.json()).error||'Draft could not be saved.');setBusy(false);return}setLock(undefined);await load();await onChanged();setBusy(false);setMode('view')}
 const updateRequirement=(index:number,key:keyof DraftRequirement,value:string|number)=>setRequirements(items=>items.map((x,i)=>i===index?{...x,[key]:value}:x))
 const move=(index:number,direction:number)=>setApprovers(items=>{const target=index+direction;if(target<0||target>=items.length)return items;const next=[...items];[next[index],next[target]]=[next[target],next[index]];return next})
 if(!scr)return <main className="scrLoading">Loading controlled record…</main>
 const latest=[...scr.reviewCycles].sort((a,b)=>b.sequence-a.sequence)[0],active=latest?.steps.find(x=>x.state==='Active'&&x.approverId===user.userName)??latest?.steps.find(x=>x.state==='Active'),isAuthor=scr.authorId===user.userName||user.isAdministrator
 return <main className="scrPage">
  <header className="scrHeader"><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">CHANGE CONTROL / {scr.displayNumber}</p><h1>{scr.title}</h1><p>Revision-controlled change case and proposed lifecycle impact.</p></div><div className="headerState"><span className={`stateBadge ${scr.state.toLowerCase()}`}>{scr.state}</span><small>Record version {scr.version}</small></div></header>{error&&<div className="workspaceError">{error}</div>}
  {mode==='edit'?<form onSubmit={save} className="workspaceStack">
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Edit checked-out Draft</h2><p>Exclusive server lock, recoverable snapshots, and attributable check-in.</p></div><div className={`autosaveState ${autosaveStatus.toLowerCase()}`}><i/>{autosaveStatus}{lock&&<small>Lock expires {new Date(lock.expiresAt).toLocaleTimeString()}</small>}</div></div><div className="checkoutBanner"><b>Checked out by {user.displayName}</b><span>Opened {lock&&new Date(lock.openedAt).toLocaleString()} · other users retain read-only access</span></div><div className="editFields"><label>Title<input name="title" value={draft.title} onChange={e=>setDraft(x=>({...x,title:e.target.value}))} required/></label><label>Problem<textarea name="problem" value={draft.problem} onChange={e=>setDraft(x=>({...x,problem:e.target.value}))} required/></label><label>Analysis<textarea name="analysis" value={draft.analysis} onChange={e=>setDraft(x=>({...x,analysis:e.target.value}))} required/></label><label>Solution<textarea name="solution" value={draft.solution} onChange={e=>setDraft(x=>({...x,solution:e.target.value}))} required/></label></div></section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Controlled requirement authoring</h2><p>Rich content, schema fields, and impact dispositions are frozen into the exact SCR/SWCR review snapshot.</p></div><button type="button" className="outline" onClick={()=>setRequirements(x=>[...x,emptyRequirement()])}>+ Add requirement proposal</button></div>{requirements.map((item,index)=><ControlledRequirementEditor item={item} index={index} key={`${item.baseNumber}-${index}`} onChange={(key,value)=>updateRequirement(index,key,value)} onRemove={()=>setRequirements(x=>x.filter((_,i)=>i!==index))}/>)}</section>
   <div className="workspaceActions"><button type="button" className="outline" onClick={discard}>Discard checkout</button><button type="button" className="outline" onClick={autosave} disabled={autosaveStatus==='Saving'}>Save recovery snapshot</button><button disabled={busy||autosaveStatus==='Conflict'}>{busy?'Checking in…':'Save & check in'}</button></div>
  </form>:mode==='approvers'?<section className="workspaceCard approverSetup">
   <div className="workspaceTitle"><div><h2>Configure review authority</h2><p>Every selected active AeroLink user must approve the exact snapshot.</p></div></div><div className="reviewModePicker"><button className={reviewMode==='Sequential'?'active':''} onClick={()=>setReviewMode('Sequential')}><b>Sequential</b><span>Notify one reviewer at a time in this order.</span></button><button className={reviewMode==='Parallel'?'active':''} onClick={()=>setReviewMode('Parallel')}><b>Parallel</b><span>Notify every reviewer when review starts.</span></button></div>{approvers.map((person,index)=><div className="approverRow" key={index}><span>{reviewMode==='Sequential'?index+1:'•'}</span><PersonPicker api={api} projectId={scr.projectId} value={person.userId} name={person.name} index={index} onSelect={selected=>setApprovers(items=>items.map((item,position)=>position===index?selected:item))}/><button disabled={reviewMode==='Parallel'} onClick={()=>move(index,-1)}>↑</button><button disabled={reviewMode==='Parallel'} onClick={()=>move(index,1)}>↓</button><button className="remove" onClick={()=>setApprovers(x=>x.filter((_,i)=>i!==index))}>Remove</button></div>)}<button className="outline addApprover" onClick={()=>setApprovers(x=>[...x,{userId:'',name:''}])}>+ Add approver</button><div className="snapshotNote"><b>Snapshot protection</b><p>Submission freezes the exact content hash. Each activated reviewer receives a My Work deep link and must re-authenticate to sign.</p></div><div className="workspaceActions"><button className="outline" onClick={()=>setMode('view')}>Cancel</button><button disabled={busy||!approvers.length||approvers.some(x=>!x.userId)} onClick={()=>call('submit',{expectedVersion:scr.version,approvers,mode:reviewMode})}>{busy?'Submitting…':'Submit for Review'}</button></div>
  </section>:<div className="workspaceGrid"><div className="workspaceStack">
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Change case</h2><p>Problem, analysis, and proposed solution</p></div>{scr.state==='Draft'&&isAuthor&&<button className="outline" disabled={busy||!!(lockStatus?.locked&&!lockStatus.mine)} onClick={beginEdit}>{busy?'Checking lock…':lockStatus?.locked&&!lockStatus.mine?`Read only · ${lockStatus.holder}`:'Check out & edit'}</button>}</div>{lockStatus?.locked&&!lockStatus.mine&&<div className="readOnlyLock"><b>Read-only while checked out</b><span>{lockStatus.holder} · active {lockStatus.lastActivityAt&&new Date(lockStatus.lastActivityAt).toLocaleString()} · expires {lockStatus.expiresAt&&new Date(lockStatus.expiresAt).toLocaleTimeString()}</span></div>}<div className="pasView">{[['P','Problem',scr.problem],['A','Analysis',scr.analysis],['S','Solution',scr.solution]].map(x=><article key={x[0]}><span>{x[0]}</span><div><b>{x[1]}</b><p>{x[2]||'Not yet provided'}</p></div></article>)}</div></section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Requirement impact</h2><p>{scr.requirementChanges.length} proposed controlled change{scr.requirementChanges.length===1?'':'s'}</p></div></div>{scr.requirementChanges.map(item=><article className="requirementView" key={item.id}><div><b>{item.displayNumber}</b><span>{item.level} · {item.kind}</span></div><p>{item.kind==='Retire'&&!item.statement?'Requirement will be retired.':item.statement}</p><small>{item.verificationMethod} · {item.rationale||'No rationale recorded'}</small></article>)}</section>
   <section className="workspaceCard"><div className="workspaceTitle"><div><h2>Audit history</h2><p>Append-only material events</p></div></div>{scr.audit.map((event,index)=><div className="auditRow" key={`${event.occurredAt}-${index}`}><i/><div><b>{event.eventType.replace(/([A-Z])/g,' $1').trim()}</b><p>{event.detail}</p><small>{event.actorId} · {new Date(event.occurredAt).toLocaleString()}</small></div></div>)}</section>
  </div><aside className="reviewRail"><section className="workspaceCard"><div className="workspaceTitle"><div><h2>Control status</h2><p>{scr.displayNumber}</p></div></div><dl><div><dt>State</dt><dd>{scr.state}</dd></div><div><dt>Author</dt><dd>{scr.authorId}</dd></div><div><dt>Revision</dt><dd>{scr.revision}</dd></div><div><dt>Updated</dt><dd>{new Date(scr.updatedAt).toLocaleDateString()}</dd></div></dl>{scr.state==='Draft'&&isAuthor&&<button className="primaryFull" onClick={()=>setMode('approvers')}>Configure & Submit Review</button>}{scr.state==='Approved'&&isAuthor&&<button className="primaryFull" disabled={busy} onClick={revise}>{busy?'Creating revision…':`Create ${scr.baseNumber}.${String(scr.revision+1).padStart(2,'0')} Draft`}</button>}{scr.state==='Approved'&&<p className="snapshotNote">The approved revision remains immutable. A new Draft copies its exact content into the next revision.</p>}</section>
   {latest&&<section className="workspaceCard"><div className="workspaceTitle"><div><h2>Review cycle {latest.sequence}</h2><p>{latest.state} · {latest.snapshotHash.slice(0,12)}…</p></div></div><div className="approvalPath">{latest.steps.map(step=><div className={`approvalStep ${step.state.toLowerCase()}`} key={step.position}><span>{step.state==='Approved'?'✓':step.position+1}</span><div><b>{step.approverName}</b><small>{step.approverId} · {step.state}</small></div></div>)}</div>{latest.closureReason&&<div className="closure"><b>Closure reason</b><p>{latest.closureReason}</p></div>}{scr.state==='InReview'&&active&&<div className="reviewActions"><p><b>{active.approverName}</b> is the active reviewer.</p>{active.approverId===user.userName?<><button disabled={busy} onClick={()=>setSigning(true)}>Review & electronically approve</button><textarea placeholder="Reason for requested changes" value={reason} onChange={e=>setReason(e.target.value)}/><button className="danger" disabled={busy||!reason.trim()} onClick={()=>call('request-changes',{expectedVersion:scr.version,reason})}>Request changes</button></>:<div className="snapshotNote"><b>Waiting for assigned reviewer</b><p>Only the assigned identity can act on this stage.</p></div>}</div>}</section>}
  </aside></div>}
  {signing&&<SignatureDialog title={`Approve ${scr.displayNumber}`} meaning="I approve this exact SCR revision and its proposed requirement changes as suitable for controlled progression." onCancel={()=>setSigning(false)} onSign={async(password,meaning)=>{const ok=await call('approve',{password,meaning,expectedVersion:scr.version});if(ok)setSigning(false)}}/>}
 </main>
}
