import { useCallback, useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import './VerificationCenter.css'
import './EvidenceUpload.css'

type Baseline={id:string;displayNumber:string;name:string;state:string;requirementsMaterializedAt?:string}
type Build={id:string;buildNumber:string;baselineId:string;version:string}
type Requirement={revisionId:string;displayNumber:string;statement:string}
type Procedure={id:string;revisionId:string;displayNumber:string;title:string;state:string;objective:string;requirementCount:number;lastOutcome?:string}
type Execution={id:string;procedureRevisionId:string;displayNumber:string;title:string;outcome:string;executedBy:string;determination:string;evidenceReference:string;executedAt:string;retestOfExecutionId?:string;evidence:{id:string;originalFileName:string;size:number;sha256:string}[]}
type Coverage={total:number;covered:number;verified:number;uncovered:number;items:{revisionId:string;displayNumber:string;statement:string;covered:boolean;verified:boolean;coveredBy:{revisionId:string;displayNumber:string;title:string;latestOutcome?:string;latestExecutionId?:string}[]}[]}
type Props={api:string;projectId:string;releaseId:string;onBack:()=>void}

export default function VerificationCenter({api,projectId,releaseId,onBack}:Props){
 const [baselines,setBaselines]=useState<Baseline[]>([]),[baselineId,setBaselineId]=useState(''),[builds,setBuilds]=useState<Build[]>([]),[buildId,setBuildId]=useState(''),[requirements,setRequirements]=useState<Requirement[]>([]),[procedures,setProcedures]=useState<Procedure[]>([]),[executions,setExecutions]=useState<Execution[]>([]),[coverage,setCoverage]=useState<Coverage>(),[creating,setCreating]=useState(false),[recording,setRecording]=useState<Procedure>(),[retest,setRetest]=useState<Execution>(),[error,setError]=useState('')
 const load=useCallback(async()=>{const [a,b,c,d]=await Promise.all([fetch(`${api}/api/baselines?projectId=${projectId}&releaseId=${releaseId}`),fetch(`${api}/api/builds?projectId=${projectId}`),fetch(`${api}/api/test-procedures?projectId=${projectId}`),fetch(`${api}/api/test-executions?projectId=${projectId}${buildId?`&buildId=${buildId}`:''}`)]);const bs:Baseline[]=a.ok?await a.json():[];setBaselines(bs.filter(x=>x.requirementsMaterializedAt));if(b.ok)setBuilds(await b.json());if(c.ok)setProcedures(await c.json());if(d.ok)setExecutions(await d.json());setBaselineId(current=>current||bs.find(x=>x.requirementsMaterializedAt)?.id||'')},[api,projectId,releaseId,buildId])
 const loadCoverage=useCallback(async()=>{if(!baselineId&&!buildId)return;const key=buildId?`buildId=${buildId}`:`baselineId=${baselineId}`;const [a,b]=await Promise.all([fetch(`${api}/api/verification-coverage?projectId=${projectId}&${key}`),fetch(`${api}/api/requirements?projectId=${projectId}&baselineId=${baselineId||builds.find(x=>x.id===buildId)?.baselineId}&includeRetired=false&page=1&pageSize=200`)]);if(a.ok)setCoverage(await a.json());if(b.ok)setRequirements((await b.json()).items)},[api,projectId,baselineId,buildId,builds])
 useEffect(()=>{load()},[load]);useEffect(()=>{loadCoverage()},[loadCoverage])
 const createProcedure=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget),ids=form.getAll('requirementIds');const response=await fetch(`${api}/api/test-procedures`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,baseNumber:form.get('baseNumber'),title:form.get('title'),ownerId:form.get('ownerId'),objective:form.get('objective'),preconditions:form.get('preconditions'),steps:form.get('steps'),expectedResult:form.get('expectedResult'),requirementRevisionIds:ids})});if(!response.ok){setError((await response.json()).error||'Procedure could not be created.');return}setCreating(false);await load();await loadCoverage()}
 const record=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!recording)return;const form=new FormData(e.currentTarget);const response=await fetch(`${api}/api/test-executions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({projectId,procedureRevisionId:recording.revisionId,softwareBuildId:buildId||null,retestOfExecutionId:retest?.id||null,outcome:form.get('outcome'),executedBy:form.get('executedBy'),configuration:form.get('configuration'),determination:form.get('determination'),evidenceReference:form.get('evidenceReference'),executedAt:new Date(String(form.get('executedAt'))).toISOString()})});if(!response.ok){setError((await response.json()).error||'Result could not be recorded.');return}setRecording(undefined);setRetest(undefined);await load();await loadCoverage()}
 const upload=async(execution:Execution,file:File)=>{const form=new FormData();form.append('file',file);form.append('projectId',projectId);form.append('uploadedBy','test.engineer');const response=await fetch(`${api}/api/evidence`,{method:'POST',body:form});if(!response.ok){setError((await response.json()).error);return}const evidence=await response.json();await fetch(`${api}/api/test-executions/${execution.id}/evidence/${evidence.id}`,{method:'POST'});await load();await loadCoverage()}
 return <main className="verificationPage"><header><div><button className="back" onClick={onBack}>← Command Center</button><p className="eyebrow">VERIFICATION CONTROL / EXTERNAL EXECUTION</p><h1>Verification & Evidence</h1><p>Control procedures, coverage, human result determinations, evidence, and retest history.</p></div><button onClick={()=>setCreating(true)}>+ New Test Procedure</button></header>{error&&<div className="workspaceError">{error}</div>}
 <section className="verificationContext"><label>Materialized baseline<select value={baselineId} onChange={e=>{setBaselineId(e.target.value);setBuildId('')}}><option value="">Select baseline…</option>{baselines.map(x=><option value={x.id} key={x.id}>{x.displayNumber} · {x.name}</option>)}</select></label><label>Software build (optional result context)<select value={buildId} onChange={e=>{setBuildId(e.target.value);if(e.target.value)setBaselineId(builds.find(x=>x.id===e.target.value)?.baselineId||'')}}><option value="">Baseline-wide coverage</option>{builds.map(x=><option value={x.id} key={x.id}>{x.buildNumber}</option>)}</select></label></section>
 {coverage&&<section className="coverageMetrics"><article><b>{coverage.total}</b><span>Effective requirements</span></article><article><b>{coverage.covered}</b><span>With procedure coverage</span></article><article><b>{coverage.verified}</b><span>Latest result Pass</span></article><article className={coverage.uncovered?'warning':''}><b>{coverage.uncovered}</b><span>Coverage gaps</span></article></section>}
 {creating&&<form className="procedureForm" onSubmit={createProcedure}><div><h2>Create approved test procedure revision</h2><p>One procedure can cover multiple exact requirement revisions.</p></div><label>Procedure identifier<input name="baseNumber" defaultValue="SWTP-00000001" pattern="[A-Z]+-[0-9]{8}" required/></label><label>Owner<input name="ownerId" defaultValue="test.engineer" required/></label><label className="wide">Title<input name="title" required/></label><label className="wide">Objective<textarea name="objective" required/></label><label>Preconditions<textarea name="preconditions"/></label><label>Expected result<textarea name="expectedResult" required/></label><label className="wide">Procedure steps<textarea name="steps" required/></label><fieldset className="wide"><legend>Exact requirements covered</legend>{requirements.map(x=><label className="reqCheck" key={x.revisionId}><input type="checkbox" name="requirementIds" value={x.revisionId}/><span><b>{x.displayNumber}</b>{x.statement}</span></label>)}</fieldset><div><button type="button" className="outline" onClick={()=>setCreating(false)}>Cancel</button><button>Create Procedure</button></div></form>}
 {recording&&<form className="resultForm" onSubmit={record}><div><h2>{retest?'Record retest':'Record external test result'}</h2><p>{recording.displayNumber} · {recording.title}</p></div><label>Outcome<select name="outcome"><option>Pass</option><option>Fail</option><option>Blocked</option></select></label><label>Executed by / human determination owner<input name="executedBy" defaultValue="test.engineer" required/></label><label>Execution time<input type="datetime-local" name="executedAt" defaultValue={new Date().toISOString().slice(0,16)} required/></label><label>Configuration<textarea name="configuration" placeholder="Hardware, software build, tools, environment…"/></label><label>Evidence reference<input name="evidenceReference" placeholder="File path, evidence ID, repository URL…"/></label><label className="wide">Human determination<textarea name="determination" placeholder="Why this run passed, failed, or was blocked" required/></label><div><button type="button" className="outline" onClick={()=>{setRecording(undefined);setRetest(undefined)}}>Cancel</button><button>Record immutable result</button></div></form>}
 <div className="verificationGrid"><section className="verificationCard"><div className="cardTitle"><h2>Requirement coverage</h2><p>Exact, version-aware links</p></div>{coverage?.items.map(x=><article className="coverageRow" key={x.revisionId}><div><b>{x.displayNumber}</b><i className={x.verified?'pass':x.covered?'covered':'gap'}>{x.verified?'Verified':x.covered?'Covered':'Gap'}</i></div><p>{x.statement}</p>{x.coveredBy.map(p=><small key={p.revisionId}>{p.displayNumber} · {p.title} · {p.latestOutcome||'Not executed'}</small>)}</article>)}</section>
 <aside><section className="verificationCard"><div className="cardTitle"><h2>Test procedures</h2><p>Reusable controlled revisions</p></div>{procedures.map(x=><article className="procedureRow" key={x.id}><div><b>{x.displayNumber}</b><i>{x.lastOutcome||'Not run'}</i></div><p>{x.title}</p><small>{x.requirementCount} exact requirement links · {x.state}</small><button onClick={()=>setRecording(x)}>Record result</button></article>)}</section><section className="verificationCard"><div className="cardTitle"><h2>Execution history</h2><p>Evidence and retest chain</p></div>{executions.map(x=><article className="executionRow" key={x.id}><div><b>{x.displayNumber}</b><i className={x.outcome.toLowerCase()}>{x.outcome}</i></div><p>{x.determination}</p><small>{x.executedBy} · {new Date(x.executedAt).toLocaleString()}</small><small>Reference: {x.evidenceReference||'Blocked before evidence produced'}</small>{x.evidence.map(e=><small key={e.id}>✓ {e.originalFileName} · SHA-256 {e.sha256.slice(0,12)}…</small>)}<label className="evidenceUpload">Upload evidence<input type="file" onChange={e=>{const file=e.target.files?.[0];if(file)upload(x,file)}}/></label>{x.outcome!=='Pass'&&<button onClick={()=>{setRetest(x);setRecording(procedures.find(p=>p.revisionId===x.procedureRevisionId))}}>Record retest</button>}</article>)}</section></aside></div>
 </main>
}
