using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

if (args.Length is < 1 or > 2)
    throw new ArgumentException("Supply the destination ProblemReportSourceIdentityTableV1.g.cs path and optional frozen PostgreSQL function SQL path.");
if (args.Length == 2 && Path.GetFullPath(args[0]) == Path.GetFullPath(args[1]))
    throw new ArgumentException("The table and PostgreSQL function require separate destination paths.");

// The oracle is the actual comparer, not a Unicode casing approximation. Numeric scalar order gives
// each equivalence class its least scalar representative. Only non-identity mappings need storage.
var classes = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
var changes = new SortedDictionary<int, int>();
var scalarCount = 0;
for (var scalar = 0; scalar <= 0x10ffff; scalar++)
{
    if (!Rune.IsValid(scalar)) continue;
    scalarCount++;
    var value = new Rune(scalar).ToString();
    if (classes.TryGetValue(value, out var representative)) changes.Add(scalar, representative);
    else classes.Add(value, scalar);
}
var trim = Enumerable.Range(0, 0x10000).Where(character => ((char)character + "x" + (char)character).Trim() == "x").ToArray();
var canonical = JsonSerializer.Serialize(new { schemaVersion = 1, changes = changes.Select(pair => new[] { pair.Key, pair.Value }), trim }) + "\n";
var digest = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(canonical)));
var source = new StringBuilder("// <auto-generated />\n// Generated by AeroLink.SourceIdentityTable from real StringComparer.OrdinalIgnoreCase classes.\n")
    .AppendLine("using System.Collections.ObjectModel;")
    .AppendLine().AppendLine("namespace AeroLink.Infrastructure.Persistence;")
    .AppendLine().AppendLine("internal static class ProblemReportSourceIdentityTableV1")
    .AppendLine("{")
    .AppendLine("    internal const string Version = \"ordinal-ignore-case-v1\";")
    .AppendLine($"    internal const string ClassTableSha256 = \"{digest}\";")
    .AppendLine("    internal static readonly IReadOnlyDictionary<int, int> CaseMappings = new ReadOnlyDictionary<int, int>(new Dictionary<int, int>")
    .AppendLine("    {");
foreach (var (scalar, representative) in changes)
    source.AppendLine($"        [0x{scalar:X}] = 0x{representative:X},");
source.AppendLine("    });")
    .AppendLine($"    internal static readonly IReadOnlyList<int> TrimCharacters = Array.AsReadOnly<int>([{string.Join(", ", trim.Select(character => $"0x{character:X}"))}]);")
    .AppendLine("}");
// Freeze the emitted SQL in a versioned migration/resource at authoring time. A historical migration
// must not invoke this generator or consult the active runtime's comparer/table when it is applied.
var sql = new StringBuilder($"-- Generated frozen ordinal-ignore-case-v1; class table SHA256 {digest}.\n")
    .AppendLine("CREATE FUNCTION aerolink_source_identity_v1(value text, fold boolean) RETURNS bytea LANGUAGE plpgsql IMMUTABLE STRICT AS $body$")
    .AppendLine("DECLARE first_index integer:=1; last_index integer:=char_length(value); codepoint integer; result bytea:=''::bytea;")
    .AppendLine("BEGIN")
    .AppendLine($"  WHILE first_index<=last_index AND ascii(substring(value FROM first_index FOR 1))=ANY(ARRAY[{string.Join(",", trim)}]) LOOP first_index:=first_index+1; END LOOP;")
    .AppendLine($"  WHILE first_index<=last_index AND ascii(substring(value FROM last_index FOR 1))=ANY(ARRAY[{string.Join(",", trim)}]) LOOP last_index:=last_index-1; END LOOP;")
    .AppendLine("  WHILE first_index<=last_index LOOP")
    .AppendLine("    codepoint:=ascii(substring(value FROM first_index FOR 1));")
    .AppendLine("    IF fold THEN codepoint:=CASE codepoint");
foreach (var (scalar, representative) in changes)
    sql.AppendLine($"      WHEN {scalar} THEN {representative}");
sql.AppendLine("      ELSE codepoint END; END IF;")
    .AppendLine("    result:=result||decode(lpad(to_hex(codepoint),8,'0'),'hex'); first_index:=first_index+1;")
    .AppendLine("  END LOOP;")
    .AppendLine("  RETURN result;")
    .AppendLine("END $body$;");
var generated = Stable(source);
var generatedSql = Stable(sql);
RefuseChangedOutput(args[0], generated);
if (args.Length == 2) RefuseChangedOutput(args[1], generatedSql);
File.WriteAllText(Path.GetFullPath(args[0]), generated, new UTF8Encoding(false));
if (args.Length == 2) File.WriteAllText(Path.GetFullPath(args[1]), generatedSql, new UTF8Encoding(false));
Console.WriteLine(JsonSerializer.Serialize(new { runtime = Environment.Version.ToString(),
    sortVersion = CultureInfo.InvariantCulture.CompareInfo.Version.FullVersion,
    sortId = CultureInfo.InvariantCulture.CompareInfo.Version.SortId, scalarCount, classCount = classes.Count,
    mappings = changes.Count, trimCharacters = trim.Length, classTableSha256 = digest,
    postgresFunctionSha256 = Convert.ToHexStringLower(SHA256.HashData(Encoding.UTF8.GetBytes(generatedSql))) }));

// Stable line endings and no BOM make repeatability independent of the generating machine.
static string Stable(StringBuilder value) => value.ToString().Replace("\r\n", "\n");
static void RefuseChangedOutput(string path, string generated)
{
    var destination = Path.GetFullPath(path);
    if (File.Exists(destination) && File.ReadAllText(destination).Replace("\r\n", "\n") != generated)
        throw new InvalidOperationException($"The frozen v1 source identity output at {destination} differs from this runtime. " +
            "Its existing contents are preserved; qualify an explicit versioned transition before generating a new artifact.");
}
