import { expect, test } from '@playwright/test'
import { apiBase, apiLogin } from './auth'

test('acceptance closure proves governed revisioning, direct review work, publications, full trace and historical discovery',async({request,playwright})=>{
 test.setTimeout(180_000)
 await apiLogin(request)
 const workspaces=await (await request.get(`${apiBase}/api/workspaces`)).json()
 const fms=workspaces.find((x:any)=>x.program.name==='Flight Management System Live Program')
 expect(fms).toBeTruthy()
 const project=fms.projects[0].project
 const releases=fms.projects[0].releases
 const released=releases.find((x:any)=>x.version==='1.5')
 const active=releases.find((x:any)=>x.version==='1.6')
 expect(released.isReleased).toBeTruthy()
 expect(active.isReleased).toBeFalsy()

 const systemDraftResponse=await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'System',title:'Introduce authenticated system acceptance requirement',problem:'Acceptance authority must be explicit',analysis:'A controlled System requirement is needed',solution:'Introduce the requirement through an SCR',requirementChanges:[{level:'System',kind:'Introduce',statement:'The FMS shall retain authenticated acceptance authority.',rationale:'Supports controlled acceptance.',verificationMethod:'Inspection'}]}})
 expect(systemDraftResponse.status(),await systemDraftResponse.text()).toBe(201)
 const systemDraft=await systemDraftResponse.json()
 expect(systemDraft.baseNumber).toMatch(/^SCR-\d{8}$/)
 expect(systemDraft.authorId).toBe('admin')
 expect(systemDraft.requirementChanges[0].displayNumber).toMatch(/^SYSR-\d{6}\.00$/)
 const partialLookup=await request.get(`${apiBase}/api/authoring/requirements?projectId=${project.id}&scope=System&search=0150&limit=8`)
 expect(partialLookup.ok(),await partialLookup.text()).toBeTruthy()
 const existingSystem=(await partialLookup.json())[0]
 expect(existingSystem.baseNumber).toContain('0150')
 const modifiedSystem=await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'System',title:'Modify a requirement found by identifier suffix',problem:'The selected behavior needs clarification',analysis:'Suffix lookup resolved the authoritative requirement',solution:'Propose the next exact revision',requirementChanges:[{baseNumber:existingSystem.baseNumber,level:'System',kind:'Modify',statement:existingSystem.statement+' The behavior shall remain deterministic.',rationale:'Clarifies deterministic behavior.',verificationMethod:existingSystem.verificationMethod}]}})
 expect(modifiedSystem.status(),await modifiedSystem.text()).toBe(201)
 expect((await modifiedSystem.json()).requirementChanges[0].displayNumber).toBe(`${existingSystem.baseNumber}.${String(existingSystem.nextRevision).padStart(2,'0')}`)
 const systemCandidates=await (await request.get(`${apiBase}/api/authoring/requirements?projectId=${project.id}&scope=System&search=SYSR-&limit=3`)).json()
 const publicationDraft=await (await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'System',title:'Publication category acceptance',problem:'All change categories need an explicit publication',analysis:'Introduced, old/new modified, and retired records must remain reviewable',solution:'Render each category in the exact SCR',requirementChanges:[{level:'System',kind:'Introduce',statement:'The FMS shall publish every controlled change category.',rationale:'Publication completeness.',verificationMethod:'Inspection'},{baseNumber:systemCandidates[0].baseNumber,level:'System',kind:'Modify',statement:systemCandidates[0].statement+' The published wording shall show this proposed revision.',rationale:'Old and new comparison.',verificationMethod:systemCandidates[0].verificationMethod},{baseNumber:systemCandidates[1].baseNumber,level:'System',kind:'Retire',statement:'',rationale:'The obsolete behavior is retired while history remains.',verificationMethod:systemCandidates[1].verificationMethod}]}})).json()
 const publicationPdf=await request.get(`${apiBase}/api/scrs/${publicationDraft.id}/download?format=pdf`)
 expect(publicationPdf.ok(),await publicationPdf.text()).toBeTruthy()
 const publicationText=(await publicationPdf.body()).toString('latin1')
 expect(publicationText).toContain('NEW REQUIREMENTS')
 expect(publicationText).toContain('MODIFIED REQUIREMENTS - OLD AND NEW')
 expect(publicationText).toContain('RETIRED REQUIREMENTS')
 const mixedSoftware=await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'Software',title:'Allocate HLR and LLR changes together',problem:'Both software levels require coordinated change',analysis:'The allocation crosses high and low level software requirements',solution:'Review both exact proposals in one SWCR',requirementChanges:[{level:'HighLevel',kind:'Introduce',statement:'The software shall coordinate acceptance state.',rationale:'High-level allocation.',verificationMethod:'Test'},{level:'LowLevel',kind:'Introduce',statement:'The acceptance component shall persist the coordinated state.',rationale:'Low-level implementation.',verificationMethod:'Test'}]}})
 expect(mixedSoftware.status(),await mixedSoftware.text()).toBe(201)
 const mixed=await mixedSoftware.json()
 expect(mixed.baseNumber).toMatch(/^SWCR-\d{8}$/)
 expect(mixed.requirementChanges.map((x:any)=>x.level)).toEqual(['HighLevel','LowLevel'])

 const reviewDraftResponse=await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'Software',title:'Sequential activation acceptance',problem:'Ordered authority must be proven',analysis:'Only the current reviewer may act',solution:'Exercise two controlled stages',requirementChanges:[{level:'HighLevel',kind:'Introduce',statement:'The software shall activate one sequential reviewer at a time.',rationale:'Prevents out-of-order approval.',verificationMethod:'Test'}]}})
 const reviewDraft=await reviewDraftResponse.json()
 const sequentialResponse=await request.post(`${apiBase}/api/scrs/${reviewDraft.id}/submit`,{data:{expectedVersion:reviewDraft.version,mode:'Sequential',approvers:[{userId:'systems.reviewer',name:'Systems Engineer'},{userId:'assurance.reviewer',name:'Development Assurance Reviewer'}]}})
 expect(sequentialResponse.ok(),await sequentialResponse.text()).toBeTruthy()
 const sequential=await sequentialResponse.json()
 expect(sequential.reviewCycles.at(-1).steps.map((x:any)=>x.state)).toEqual(['Active','Pending'])
 const r1=await playwright.request.newContext(),r2=await playwright.request.newContext()
 for(const [context,userName] of [[r1,'systems.reviewer'],[r2,'assurance.reviewer']] as const){const response=await context.post(`${apiBase}/api/auth/login`,{data:{userName,password:'AeroLink!2026'}});expect(response.ok(),await response.text()).toBeTruthy()}
 const r1Queue=await (await r1.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`)).json()
 const r2QueueBefore=await (await r2.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`)).json()
 expect(r1Queue.notifications.some((x:any)=>x.artifactId===reviewDraft.id)).toBeTruthy()
 expect(r2QueueBefore.notifications.some((x:any)=>x.artifactId===reviewDraft.id)).toBeFalsy()
 const stageOne=await r1.post(`${apiBase}/api/scrs/${reviewDraft.id}/approve`,{data:{password:'AeroLink!2026',meaning:'Approve stage one.',expectedVersion:sequential.version}})
 expect(stageOne.ok(),await stageOne.text()).toBeTruthy()
 const afterStageOne=await stageOne.json()
 expect(afterStageOne.reviewCycles.at(-1).steps.map((x:any)=>x.state)).toEqual(['Approved','Active'])
 const r2QueueAfter=await (await r2.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`)).json()
 expect(r2QueueAfter.notifications.some((x:any)=>x.artifactId===reviewDraft.id)).toBeTruthy()
 const returned=await r2.post(`${apiBase}/api/scrs/${reviewDraft.id}/request-changes`,{data:{reason:'Clarify the activation timing.',expectedVersion:afterStageOne.version}})
 expect(returned.ok(),await returned.text()).toBeTruthy()
 const returnedDraft=await returned.json()
 expect(returnedDraft.state).toBe('Draft')
 expect(returnedDraft.revision).toBe(reviewDraft.revision)

 const parallelDraft=await (await request.post(`${apiBase}/api/scr-drafts`,{data:{projectId:project.id,targetReleaseId:active.id,type:'Software',title:'Parallel unanimity acceptance',problem:'Independent reviews must run concurrently',analysis:'Both signatures remain mandatory',solution:'Activate all parallel reviewers',requirementChanges:[{level:'LowLevel',kind:'Introduce',statement:'The component shall require unanimous parallel review.',rationale:'Independent assurance.',verificationMethod:'Inspection'}]}})).json()
 const parallelResponse=await request.post(`${apiBase}/api/scrs/${parallelDraft.id}/submit`,{data:{expectedVersion:parallelDraft.version,mode:'Parallel',approvers:[{userId:'systems.reviewer',name:'Systems Engineer'},{userId:'assurance.reviewer',name:'Development Assurance Reviewer'}]}})
 expect(parallelResponse.ok(),await parallelResponse.text()).toBeTruthy()
 expect((await parallelResponse.json()).reviewCycles.at(-1).steps.map((x:any)=>x.state)).toEqual(['Active','Active'])
 const [parallelQueue1,parallelQueue2]=await Promise.all([r1.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`).then(x=>x.json()),r2.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`).then(x=>x.json())])
 expect(parallelQueue1.notifications.some((x:any)=>x.artifactId===parallelDraft.id)).toBeTruthy()
 expect(parallelQueue2.notifications.some((x:any)=>x.artifactId===parallelDraft.id)).toBeTruthy()
 await r1.dispose();await r2.dispose()

 const invalidDerived=await request.post(`${apiBase}/api/scr-drafts`,{data:{
  projectId:project.id,targetReleaseId:active.id,type:'Software',title:'Invalid derived proposal',problem:'Rationale omitted',analysis:'Derived classification needs justification',solution:'Reject incomplete proposal',
  requirementChanges:[{level:'HighLevel',kind:'Introduce',statement:'The software shall reject incomplete derived proposals.',rationale:'',verificationMethod:'Test',isDerived:true}]
 }})
 expect(invalidDerived.status()).toBe(400)
 expect(await invalidDerived.text()).toContain('explicit engineering rationale')

 const suffix=Date.now().toString().slice(-6)
 const draftResponse=await request.post(`${apiBase}/api/scr-drafts`,{data:{
  projectId:project.id,targetReleaseId:active.id,type:'Software',title:`Derived guidance continuity ${suffix}`,problem:'Guidance continuity needs an internal safety monitor',analysis:'The behavior is derived from software architecture rather than a direct system allocation',solution:'Introduce a derived HLR with explicit rationale',
  requirementChanges:[{level:'HighLevel',kind:'Introduce',statement:'The software shall monitor derived guidance continuity.',rationale:'Architecture safety analysis requires an independent continuity monitor.',verificationMethod:'Test',isDerived:true}]
 }})
 expect(draftResponse.status(),await draftResponse.text()).toBe(201)
 const draft=await draftResponse.json()
 expect(draft.baseNumber).toMatch(/^SWCR-\d{8}$/)
 expect(draft.authorId).toBe('admin')
 expect(draft.requirementChanges[0].displayNumber).toMatch(/^HLR-\d{6}\.00$/)

 const submitted=await request.post(`${apiBase}/api/scrs/${draft.id}/submit`,{data:{expectedVersion:draft.version,mode:'Sequential',approvers:[{userId:'systems.reviewer',name:'Systems Engineer'}]}})
 expect(submitted.ok(),await submitted.text()).toBeTruthy()
 const inReview=await submitted.json()
 expect(inReview.state).toBe('InReview')
 const crPdf=await request.get(`${apiBase}/api/scrs/${draft.id}/download?format=pdf`)
 expect(crPdf.ok(),await crPdf.text()).toBeTruthy()
 expect((await crPdf.body()).subarray(0,4).toString()).toBe('%PDF')

 const reviewer=await playwright.request.newContext()
 const reviewerLogin=await reviewer.post(`${apiBase}/api/auth/login`,{data:{userName:'systems.reviewer',password:'AeroLink!2026'}})
 expect(reviewerLogin.ok(),await reviewerLogin.text()).toBeTruthy()
 const queueResponse=await reviewer.get(`${apiBase}/api/enterprise-requirements/work-queue?projectId=${project.id}`)
 expect(queueResponse.ok(),await queueResponse.text()).toBeTruthy()
 const queue=await queueResponse.json()
 const notification=queue.notifications.find((x:any)=>x.artifactId===draft.id)
 expect(notification).toMatchObject({route:`scr:${draft.id}`,type:'ReviewActivated'})
 const approvedResponse=await reviewer.post(`${apiBase}/api/scrs/${draft.id}/approve`,{data:{password:'AeroLink!2026',meaning:'Approved as the exact reviewed software change snapshot.',expectedVersion:inReview.version}})
 expect(approvedResponse.ok(),await approvedResponse.text()).toBeTruthy()
 expect((await approvedResponse.json()).state).toBe('Approved')
 await reviewer.dispose()

 const current=await (await request.get(`${apiBase}/api/scrs/${draft.id}`)).json()
 const nextResponse=await request.post(`${apiBase}/api/scrs/${draft.id}/next-revision`,{data:{actorId:'admin',expectedVersion:current.version}})
 expect(nextResponse.status(),await nextResponse.text()).toBe(201)
 const next=await nextResponse.json()
 expect(next.baseNumber).toBe(draft.baseNumber)
 expect(next.revision).toBe(1)
 expect(next.state).toBe('Draft')
 expect(current.state).toBe('Approved')

 const baselines=await (await request.get(`${apiBase}/api/baselines?projectId=${project.id}&releaseId=${released.id}`)).json()
 const baseline=baselines.find((x:any)=>x.requirementsMaterializedAt)
 expect(baseline).toBeTruthy()
 const traceResponse=await request.get(`${apiBase}/api/traceability?projectId=${project.id}&baselineId=${baseline.id}&page=1&pageSize=200`)
 expect(traceResponse.ok(),await traceResponse.text()).toBeTruthy()
 const trace=await traceResponse.json()
 expect(trace.totalCount).toBeGreaterThan(1000)
 expect(trace.items.some((x:any)=>x.parents.length||x.children.length)).toBeTruthy()
 const verified=trace.items.find((x:any)=>x.tests.some((t:any)=>t.executions.length))
 expect(verified).toBeTruthy()
 expect(verified.tests.some((t:any)=>t.executions.some((e:any)=>['Pass','Fail'].includes(e.outcome)))).toBeTruthy()
 const executions=trace.items.flatMap((x:any)=>x.tests.flatMap((t:any)=>t.executions))
 expect(executions.some((x:any)=>x.evidenceReference.startsWith('evidence/fms-1.5/'))).toBeTruthy()
 const failed=executions.find((x:any)=>x.outcome==='Fail')
 expect(failed).toBeTruthy()
 expect(executions.some((x:any)=>x.outcome==='Pass'&&x.retestOfExecutionId===failed.id)).toBeTruthy()

 for(const format of ['pdf','docx']){
  const output=await request.get(`${apiBase}/api/traceability/${baseline.id}/download?format=${format}`)
  expect(output.ok(),await output.text()).toBeTruthy()
  expect((await output.body()).subarray(0,format==='pdf'?4:2).toString()).toBe(format==='pdf'?'%PDF':'PK')
 }
 const documents=await (await request.get(`${apiBase}/api/documents?projectId=${project.id}`)).json()
 expect(documents.map((x:any)=>x.type)).toEqual(expect.arrayContaining(['Sysrd','SwrdHighLevel','SwrdLowLevel','SystemTestProcedures','HighLevelTestProcedures','LowLevelTestProcedures']))
 for(const document of documents.filter((x:any)=>['Sysrd','SwrdHighLevel','SwrdLowLevel'].includes(x.type))){
  const output=await request.get(`${apiBase}/api/documents/${document.id}/download?format=pdf`)
  expect(output.ok(),await output.text()).toBeTruthy()
  const bytes=await output.body()
  expect(bytes.subarray(0,4).toString()).toBe('%PDF')
  expect(bytes.toString('latin1')).toContain('DOCUMENT CONTROL')
  expect(bytes.toString('latin1')).toContain('APPROVAL REGISTER')
  expect(bytes.toString('latin1')).toContain('ANNEX A - UPWARD REQUIREMENT TRACEABILITY')
 }

 const searchKinds=new Set<string>()
 for(const query of ['SCR','SWCR','SYSR','SWBL','SYSRD','1.5','FMS-1.5.0','SYSTP-000001','evidence/fms-1.5']){
  const response=await request.get(`${apiBase}/api/search?projectId=${project.id}&query=${encodeURIComponent(query)}&limit=50`)
  expect(response.ok(),await response.text()).toBeTruthy()
  for(const item of (await response.json()).items)searchKinds.add(item.kind)
 }
 expect([...searchKinds]).toEqual(expect.arrayContaining(['change-request','requirement','baseline','build','test-procedure','test-execution','document','release']))
 const blockedSuccessor=await request.post(`${apiBase}/api/releases`,{data:{projectId:project.id,version:'1.7',predecessorReleaseId:released.id}})
 expect(blockedSuccessor.status()).toBe(409)
 expect(await blockedSuccessor.text()).toContain('1.6 is still in work')
})
