import {expect,test} from '@playwright/test'
import {login,openNavigationGroup,selectProgram} from './auth'

test('enterprise control exposes governed product-line reuse and evidence-based operations assurance',async({page})=>{
 await login(page, 'admin', { openProject: false });await selectProgram(page,'Flight Management System Live Program');await openNavigationGroup(page,'ADMINISTRATION');await page.getByRole('link',{name:/Enterprise Control/}).click()
 await page.getByRole('button',{name:'Product line'}).click();await expect(page.getByRole('heading',{name:'Configuration intelligence'})).toBeVisible();await expect(page.getByText('Guidance computation core')).toBeVisible();await expect(page.getByText('Released FMS 1.5 configuration')).toBeVisible();await expect(page.getByText('Navigation integrity assurance')).toBeVisible();await expect(page.getByText('Deferred',{exact:true})).toBeVisible();await expect(page.getByText('Current',{exact:true})).toBeVisible();await expect(page.getByText('LIB-SYSR-00001.00')).toBeVisible();await expect(page.getByText(/CCS-00001.*Propagate round-robin guidance/)).toBeVisible()
 await page.getByRole('button',{name:'FMS-1.5'}).click();await expect(page.getByText(/within 2 seconds/)).toBeVisible();await page.getByRole('button',{name:'FMS-1.6'}).click();await expect(page.getByText(/within 1 second/)).toBeVisible();await expect(page.getByText('Navigation integrity allocation')).toBeVisible()
 await page.getByRole('button',{name:'Assurance'}).click();await expect(page.getByRole('heading',{name:'Production assurance'})).toBeVisible();await expect(page.getByText('WORKLOAD TARGET NOT MET')).toBeVisible();await expect(page.getByText('Production workload is not yet qualified')).toBeVisible();await expect(page.getByText(/permission scoped/).first()).toBeVisible()
})
