import { expect, test } from '@playwright/test'

test('author creates, edits, submits, and sequentially approves an SCR', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Program name').fill('Browser Workflow Program')
  await page.getByLabel('Program code').fill('BWP')
  await page.getByLabel('Project name').fill('Workflow Software')
  await page.getByLabel('Software product').fill('Workflow Management Software')
  await page.getByLabel('Initial release or baseline').fill('1.0')
  await page.getByRole('button', { name: /Create program workspace/ }).click()

  await page.getByRole('button', { name: /Create first SCR/ }).click()
  await page.getByLabel('Title').fill('Introduce controlled browser workflow')
  await page.getByLabel('Problem').fill('The workflow is not yet controlled end to end.')
  await page.getByLabel('Analysis', { exact: true }).fill('SCR content, reviewers, and history must remain attributable.')
  await page.getByLabel('Solution').fill('Add an ordered and auditable approval workflow.')
  await page.getByLabel('Requirement statement').fill('The software shall enforce ordered SCR approval.')
  await page.getByRole('button', { name: 'Save SCR Draft' }).click()

  await expect(page.getByRole('heading', { name: 'Introduce controlled browser workflow' })).toBeVisible()
  await page.getByRole('button', { name: 'Edit Draft' }).click()
  await page.getByLabel('Title').fill('Introduce controlled approval workflow')
  await page.getByRole('button', { name: 'Save Draft' }).click()
  await expect(page.getByRole('heading', { name: 'Introduce controlled approval workflow' })).toBeVisible()

  await page.getByRole('button', { name: 'Configure & Submit Review' }).click()
  await page.getByLabel('Approver 1 name').fill('Reviewer One')
  await page.getByLabel('Approver 2 name').fill('Reviewer Two')
  await page.getByLabel('Approver 3 name').fill('Reviewer Three')
  await page.getByRole('button', { name: 'Submit for Review' }).click()
  await expect(page.getByText('InReview', { exact: true }).first()).toBeVisible()

  await expect(page.getByText('Reviewer One is the active reviewer.')).toBeVisible()
  await page.getByPlaceholder('Reason for requested changes').fill('Clarify the approval evidence retained by the workflow.')
  await page.getByRole('button', { name: 'Request changes' }).click()
  await expect(page.getByText('Draft', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Clarify the approval evidence retained by the workflow.', { exact: true })).toBeVisible()

  await page.getByRole('button', { name: 'Edit Draft' }).click()
  await page.getByRole('textbox', { name: 'Solution', exact: true }).fill('Add ordered approval with retained reviewer decisions and evidence.')
  await page.getByRole('button', { name: 'Save Draft' }).click()
  await page.getByRole('button', { name: 'Configure & Submit Review' }).click()
  await page.getByRole('button', { name: 'Submit for Review' }).click()
  await expect(page.getByRole('heading', { name: 'Review cycle 2' })).toBeVisible()
  await expect(page.getByText('Reviewer One is the active reviewer.')).toBeVisible()
  await page.getByRole('button', { name: 'Approve current stage' }).click()
  await expect(page.getByText('Reviewer Two is the active reviewer.')).toBeVisible()
  await page.getByRole('button', { name: 'Approve current stage' }).click()
  await expect(page.getByText('Reviewer Three is the active reviewer.')).toBeVisible()
  await page.getByRole('button', { name: 'Approve current stage' }).click()
  await expect(page.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Scr Approved')).toBeVisible()
})
