import { expect, test } from '@playwright/test'
import { login } from './auth'

test('author creates, edits, submits, and sequentially approves an SCR', async ({ page }) => {
  await login(page)
  await page.getByLabel('Program name').fill('Browser Workflow Program')
  await page.getByLabel('Program code').fill('BWP')
  await page.getByLabel('Project name').fill('Workflow Software')
  await page.getByLabel('Software product').fill('Workflow Management Software')
  await page.getByLabel('Initial release or baseline').fill('1.0')
  await page.getByRole('button', { name: /Create program workspace/ }).click()

  await page.getByRole('button', { name: /Create first SCR/ }).click()
  await page.getByLabel('Title').fill('Introduce controlled browser workflow')
  await page.getByLabel('Problem').fill('The workflow is not yet controlled end to end.')
  await page.getByLabel('Analysis', { exact: true }).fill('SCR content, reviewers, and history must remain attributable.')
  await page.getByLabel('Solution').fill('Add an ordered and auditable approval workflow.')
  await page.getByLabel('Requirement statement').fill('The software shall enforce ordered SCR approval.')
  await page.getByRole('button', { name: 'Save SCR Draft' }).click()

  await expect(page.getByRole('heading', { name: 'Introduce controlled browser workflow' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download DOCX' })).toHaveAttribute('href', /\/api\/scrs\/.+\/download\?format=docx/)
  await expect(page.getByRole('link', { name: 'Download PDF' })).toHaveAttribute('href', /\/api\/scrs\/.+\/download\?format=pdf/)
  await page.getByRole('button', { name: 'Edit Draft' }).click()
  await page.getByLabel('Title').fill('Introduce controlled approval workflow')
  const impactDispositions=page.locator('.editorColumns aside select')
  expect(await impactDispositions.count()).toBe(5)
  for(let i=0;i<5;i++)await impactDispositions.nth(i).selectOption('Not Affected')
  await page.getByRole('button', { name: 'Save Draft' }).click()
  await expect(page.getByRole('heading', { name: 'Introduce controlled approval workflow' })).toBeVisible()

  await page.getByRole('button', { name: 'Configure & Submit Review' }).click()
  await page.getByLabel('Approver 1 ID').fill('admin')
  await page.getByRole('button', { name: 'Remove' }).nth(2).click()
  await page.getByRole('button', { name: 'Remove' }).nth(1).click()
  await page.getByRole('button', { name: 'Submit for Review' }).click()
  await expect(page.getByText('InReview', { exact: true }).first()).toBeVisible()

  await expect(page.getByText('AeroLink Administrator is the active reviewer.')).toBeVisible()
  await page.getByRole('button', { name: 'Review & electronically approve' }).click()
  await page.getByLabel('Re-enter your password').fill('AeroLink!2026')
  await page.getByRole('button', { name: 'Sign & approve' }).click()
  await expect(page.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Scr Approved')).toBeVisible()

  await page.getByRole('button', { name: /Command Center/ }).click()
  await page.getByRole('button', { name: /Baselines/ }).click()
  await page.getByRole('button', { name: '+ New Candidate' }).click()
  await page.getByLabel('Baseline name').fill('Workflow Software 1.0 Controlled Candidate')
  await page.getByRole('button', { name: 'Create Candidate Baseline' }).click()
  await expect(page.getByText('SCR-00000001.00')).toBeVisible()
  await page.getByRole('button', { name: '+ Select exact revision' }).click()
  await expect(page.getByText('1 exact SCR revision')).toBeVisible()
  await expect(page.getByText('The software shall enforce ordered SCR approval.')).toBeVisible()
  await page.getByRole('button', { name: 'Freeze Baseline' }).click()
  await expect(page.getByText('Frozen', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('SHA-256 CONTENT HASH')).toBeVisible()
  await page.getByRole('button', { name: 'Materialize SWRD' }).click()
  await expect(page.getByText('SWRD materialized')).toBeVisible()
  await expect(page.getByText('Software Requirements Document')).toBeVisible()
  await expect(page.getByText('REQUIREMENT MANIFEST SHA-256')).toBeVisible()
  await expect(page.getByText('SWR-00000001.00').last()).toBeVisible()

  await page.getByRole('button', { name: /Command Center/ }).click()
  await page.getByRole('button', { name: /Verification/ }).click()
  await expect(page.getByRole('heading', { name: 'Verification & Evidence' })).toBeVisible()
  await expect(page.getByText('1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'New Test Procedure' }).click()
  await page.getByLabel('Title').fill('Verify ordered approval workflow')
  await page.getByLabel('Objective').fill('Verify the approved software behavior.')
  await page.getByLabel('Expected result').fill('The ordered workflow is enforced.')
  await page.getByLabel('Procedure steps').fill('Configure, stimulate, and observe the workflow.')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Create Procedure' }).click()
  await expect(page.getByText('SWTP-00000001.00', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Record result' }).click()
  await page.getByLabel('Outcome').selectOption('Fail')
  await page.getByPlaceholder('File path, evidence ID, repository URL…').fill('evidence/workflow-fail-001.json')
  await page.getByPlaceholder('Why this run passed, failed, or was blocked').fill('The second approval stage did not activate.')
  await page.getByRole('button', { name: 'Record immutable result' }).click()
  await expect(page.getByText('Fail', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: 'Record retest' }).click()
  await page.getByLabel('Outcome').selectOption('Pass')
  await page.getByPlaceholder('File path, evidence ID, repository URL…').fill('evidence/workflow-pass-002.json')
  await page.getByPlaceholder('Why this run passed, failed, or was blocked').fill('All ordered approval stages activated correctly after correction.')
  await page.getByRole('button', { name: 'Record immutable result' }).click()
  await expect(page.getByText('Verified', { exact: true })).toBeVisible()
})
