import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { apiBase, login, openNavigationGroup } from './auth'

async function openPageFromPalette(page:Page,label:string){
  await page.getByRole('button',{name:/Search & navigate/}).click()
  const palette=page.getByRole('dialog',{name:'Quick navigation'})
  await palette.getByPlaceholder(/Search pages/).fill(label)
  await palette.getByRole('link',{name:new RegExp(label)}).click()
}

test('author creates, edits, submits, and sequentially approves an SCR', async ({ page,playwright }) => {
  test.setTimeout(60_000)
  await login(page)
  const suffix=Date.now().toString().slice(-7),programName=`Browser Workflow ${suffix}`
  if(await page.getByLabel('Program name').count()){
    await page.getByLabel('Program name').fill(programName)
    await page.getByLabel('Program code').fill(`BW${suffix}`)
    await page.getByLabel('Project name').fill('Workflow Software')
    await page.getByLabel('Software product').fill('Workflow Management Software')
    await page.getByLabel('Initial release or baseline').fill('1.0')
    await page.getByRole('button', { name: /Create program workspace/ }).click()
  }else{
    const created=await page.request.post(`${apiBase}/api/workspaces`,{data:{programName,programCode:`BW${suffix}`,projectName:'Workflow Software',softwareProduct:'Workflow Management Software',initialRelease:'1.0',initialReleaseIsReleased:false}})
    expect(created.ok(),await created.text()).toBeTruthy()
    await page.reload()
    await page.locator('.program > select:not(.releaseSelector)').selectOption({label:programName})
  }

  await openPageFromPalette(page,'New Software SWCR')
  await expect(page.getByRole('navigation', { name: 'Change authoring progress' })).toBeVisible()
  await expect(page.getByLabel('Identifier')).toHaveValue(/^HLR-\d{8}$/)
  await expect(page.getByLabel('Identifier')).not.toBeEditable()
  await expect(page.getByLabel('Revision')).toHaveValue('00')
  await expect(page.getByLabel('Revision')).not.toBeEditable()
  await expect(page.getByRole('textbox',{name:'Level',exact:true})).toHaveValue('Software HLR')
  await expect(page.getByRole('textbox',{name:'Level',exact:true})).not.toBeEditable()
  await expect(page.getByLabel('Change type')).toHaveValue('Introduce')
  await expect(page.getByLabel('Change type')).not.toBeEditable()
  await expect(page.getByText('SWR-00000001')).toHaveCount(0)
  await page.getByLabel('Title').fill('Introduce controlled browser workflow')
  await page.getByLabel('Problem').fill('The workflow is not yet controlled end to end.')
  await page.getByLabel('Analysis', { exact: true }).fill('SCR content, reviewers, and history must remain attributable.')
  await page.getByLabel('Solution').fill('Add an ordered and auditable approval workflow.')
  await page.getByLabel('Requirement statement').fill('The software shall enforce ordered SCR approval.')
  await page.getByRole('button', { name: 'Save SWCR Draft' }).click()

  await expect(page.getByRole('heading', { name: 'Introduce controlled browser workflow' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download DOCX' })).toHaveAttribute('href', /\/api\/scrs\/.+\/download\?format=docx/)
  await expect(page.getByRole('link', { name: 'Download PDF' })).toHaveAttribute('href', /\/api\/scrs\/.+\/download\?format=pdf/)
  await page.getByRole('button', { name: 'Check out & edit' }).click()
  await page.getByLabel('Title').fill('Introduce controlled approval workflow')
  const impactDispositions=page.locator('.editorColumns aside select')
  expect(await impactDispositions.count()).toBe(5)
  for(let i=0;i<5;i++)await impactDispositions.nth(i).selectOption('Not Affected')
  await page.getByRole('button', { name: 'Save & check in' }).click()
  await expect(page.getByRole('heading', { name: 'Introduce controlled approval workflow' })).toBeVisible()

  await page.getByRole('button', { name: 'Configure & Submit Review' }).click()
  await expect(page.getByText('No reviewers selected')).toBeVisible()
  await page.getByRole('button', { name: '+ Add approver' }).click()
  await page.getByLabel('Approver 1 search').fill('AeroLink Administrator')
  await page.getByRole('button', { name: /AeroLink Administrator.*Administrator/ }).click()
  await page.getByRole('button', { name: 'Submit for Review' }).click()
  await expect(page.getByText('InReview', { exact: true }).first()).toBeVisible()

  await expect(page.getByText('AeroLink Administrator is the active reviewer.')).toBeVisible()
  await page.getByRole('button', { name: 'Review & electronically approve' }).click()
  await page.getByLabel('Re-enter your password').fill('AeroLink!2026')
  await page.getByRole('button', { name: 'Sign & approve' }).click()
  await expect(page.getByText('Approved', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('Scr Approved')).toBeVisible()

  await page.getByRole('link', { name: /Command Center/ }).first().click()
  await openNavigationGroup(page,'RELEASE & CONFIGURATION')
  await page.getByRole('link', { name: /Baselines/ }).click()
  await page.getByRole('button', { name: '+ New Candidate' }).click()
  await page.getByLabel('Baseline name').fill('Workflow Software 1.0 Controlled Candidate')
  await page.getByRole('button', { name: 'Create Candidate Baseline' }).click()
  await expect(page.getByText(/SWCR-\d{8}\.00/)).toBeVisible()
  await page.getByRole('button', { name: '+ Select exact revision' }).click()
  await expect(page.getByText('1 exact SCR revision')).toBeVisible()
  await expect(page.getByText('The software shall enforce ordered SCR approval.')).toBeVisible()
  await page.getByRole('button', { name: 'Freeze Baseline' }).click()
  await expect(page.getByText('Frozen', { exact: true }).first()).toBeVisible()
  await expect(page.getByText('SHA-256 CONTENT HASH')).toBeVisible()
  await page.getByRole('button', { name: 'Materialize SWRD' }).click()
  await expect(page.getByText('SWRD materialized')).toBeVisible()
  await expect(page.getByText('Software Requirements Document')).toBeVisible()
  await expect(page.getByText('REQUIREMENT MANIFEST SHA-256')).toBeVisible()
  await expect(page.getByText(/HLR-\d{8}\.00/).last()).toBeVisible()

  await page.getByRole('link', { name: /Command Center/ }).first().click()
  await openPageFromPalette(page,'Software Verification')
  await expect(page.getByRole('heading', { name: 'Verification & Evidence' })).toBeVisible()
  await expect(page.getByText('1', { exact: true }).first()).toBeVisible()
  await page.getByRole('button', { name: 'New Test Procedure' }).click()
  await page.getByLabel('Title').fill('Verify ordered approval workflow')
  await page.getByLabel('Objective').fill('Verify the approved software behavior.')
  await page.getByLabel('Expected result').fill('The ordered workflow is enforced.')
  await page.getByLabel('Procedure steps').fill('Configure, stimulate, and observe the workflow.')
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Create Procedure' }).click()
  await expect(page.getByText(/(?:HLRTP|LLRTP)-\d{8}\.00/, { exact: true }).last()).toBeVisible()
  const workspacesResponse=await page.request.get(`${apiBase}/api/workspaces`);expect(workspacesResponse.ok(),await workspacesResponse.text()).toBeTruthy();const workspaces=await workspacesResponse.json();const workspace=workspaces.find((x:{program:{name:string}})=>x.program.name===programName);const projectId=workspace.projects[0].project.id
  const usersResponse=await page.request.get(`${apiBase}/api/admin/users`);expect(usersResponse.ok(),await usersResponse.text()).toBeTruthy();const reviewer=(await usersResponse.json()).find((x:{userName:string})=>x.userName==='systems.reviewer')
  const grant=await page.request.post(`${apiBase}/api/admin/users/${reviewer.id}/memberships`,{data:{programId:workspace.program.id,role:'Approver'}});expect(grant.ok(),await grant.text()).toBeTruthy()
  const proceduresResponse=await page.request.get(`${apiBase}/api/test-procedures?projectId=${projectId}&scope=Software`);expect(proceduresResponse.ok(),await proceduresResponse.text()).toBeTruthy();const procedure=(await proceduresResponse.json()).find((x:{title:string})=>x.title==='Verify ordered approval workflow')
  const approver=await playwright.request.newContext();const approverLogin=await approver.post(`${apiBase}/api/auth/login`,{data:{userName:'systems.reviewer',password:'AeroLink!2026'}});expect(approverLogin.ok(),await approverLogin.text()).toBeTruthy();const approval=await approver.post(`${apiBase}/api/test-procedures/${procedure.revisionId}/approve`,{data:{password:'AeroLink!2026',meaning:'Approved after independent review for controlled verification use.'}});expect(approval.ok(),await approval.text()).toBeTruthy();await approver.dispose()
  await page.reload();await expect(page.getByRole('heading', { name: 'Verification & Evidence' })).toBeVisible()
  await page.getByRole('button', { name: /Test procedures/ }).click()
  await page.getByRole('button', { name: 'Record result' }).click()
  await page.getByLabel('Outcome').selectOption('Fail')
  await page.getByLabel('Evidence reference').fill('evidence/workflow-fail-001.json')
  await page.getByPlaceholder('Why this run passed, failed, or was blocked').fill('The second approval stage did not activate.')
  await page.getByRole('button', { name: 'Record immutable result' }).click()
  await expect(page.getByText('Fail', { exact: true }).last()).toBeVisible()
  await page.getByRole('button', { name: 'Record retest' }).click()
  await page.getByLabel('Outcome').selectOption('Pass')
  await page.getByLabel('Evidence reference').fill('evidence/workflow-pass-002.json')
  await page.getByPlaceholder('Why this run passed, failed, or was blocked').fill('All ordered approval stages activated correctly after correction.')
  await page.getByRole('button', { name: 'Record immutable result' }).click()
  await page.getByRole('button', { name: /Requirement coverage/ }).click()
  await expect(page.getByText('Verified', { exact: true })).toBeVisible()
})
