import { expect, test } from '@playwright/test'
import { apiLogin, login, openNavigationGroup, showcaseSeed } from './auth'

test('downstream assessment actions follow authority and submit without a form-navigation no-op', async ({page,request,browser}) => {
  const showcase=await showcaseSeed(request)
  await apiLogin(request)
  const apiResponse=await request.get(`${process.env.AEROLINK_E2E_API_BASE}/api/downstream-assessments?projectId=${showcase.projectId}&releaseId=${showcase.activeReleaseId}`)
  expect(apiResponse.ok(),await apiResponse.text()).toBeTruthy()
  expect((await apiResponse.json()).length).toBeGreaterThan(0)

  const unauthorizedContext=await browser.newContext()
  const unauthorized=await unauthorizedContext.newPage()
  await login(unauthorized,'systems.reviewer')
  await openNavigationGroup(unauthorized,'SOFTWARE ENGINEERING')
  await unauthorized.getByRole('link',{name:'Software Change Requests'}).click()
  const unauthorizedQueue=unauthorized.locator('.downstreamQueue')
  await expect(unauthorizedQueue.getByRole('button',{name:'Take it on'})).toHaveCount(0)
  await expect(unauthorizedQueue).toContainText('Software engineering authority is required')
  await unauthorizedContext.close()

  await login(page)
  await openNavigationGroup(page,'SOFTWARE ENGINEERING')
  await page.getByRole('link',{name:'Software Change Requests'}).click()

  await expect(page.getByRole('heading',{name:'Downstream change assessments'})).toBeVisible()
  const queue=page.locator('.downstreamQueue')
  await expect(queue.getByText('SCR-00031.00')).toBeVisible()
  await expect(queue.getByText('HLR assessment').first()).toBeVisible()
  await expect(queue.getByRole('button',{name:'Take it on'}).first()).toBeVisible()
  await expect(queue).toContainText('One Draft may answer several assessments')
  await expect(page.getByRole('heading',{name:'Software Change Requests'})).toBeVisible()

  const assessment=queue.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await assessment.getByRole('button',{name:'Take it on'}).click()
  await expect(assessment.getByRole('button',{name:'No change required'})).toBeVisible()
  await assessment.getByRole('button',{name:'No change required'}).click()
  const noChangeDialog=page.getByRole('dialog',{name:'Record no-change conclusion for SCR-00031.00'})
  await expect(noChangeDialog).toBeVisible()
  await expect(noChangeDialog.getByRole('button',{name:'Record no-change conclusion'})).toBeDisabled()
  await noChangeDialog.getByLabel('Decision rationale').fill('No software requirement change is required for this build.')
  await noChangeDialog.getByRole('button',{name:'Record no-change conclusion'}).click()
  await expect(noChangeDialog).toBeHidden()
  const approver=assessment.getByLabel(/Approver for SCR-00031\.00/)
  await approver.fill('software.lead')
  await assessment.locator('.personSuggestions button[data-user-name="software.lead"]').click()
  await assessment.getByRole('button',{name:'Send for approval'}).click()
  await expect(assessment).toContainText('HLR assessment in review')
  await page.reload()
  const persisted=page.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await expect(persisted).toContainText('HLR assessment in review')
  await expect(persisted.locator('.personName[title="software.lead"]')).toBeVisible()

  const approverContext=await browser.newContext()
  const approverPage=await approverContext.newPage()
  await login(approverPage,'software.lead')
  await openNavigationGroup(approverPage,'SOFTWARE ENGINEERING')
  await approverPage.getByRole('link',{name:'Software Change Requests'}).click()
  const approvalAssessment=approverPage.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await approvalAssessment.getByRole('button',{name:'Return'}).click()
  const returnDialog=approverPage.getByRole('dialog',{name:'Return SCR-00031.00 assessment'})
  await expect(returnDialog).toBeVisible()
  await expect(returnDialog.getByRole('button',{name:'Return assessment'})).toBeDisabled()
  await returnDialog.getByLabel('Decision rationale').fill('Clarify the software-level allocation before approval.')
  await returnDialog.getByRole('button',{name:'Return assessment'}).click()
  await expect(returnDialog).toBeHidden()
  await expect(approvalAssessment).toContainText('HLR no impact — ready for review')
  await expect(approvalAssessment).toContainText('Clarify the software-level allocation before approval.')
  await approverContext.close()
})

test('an assessment deep link explains impact and a required change creates and links the correct Draft SWCR',async({page,request})=>{
  test.setTimeout(90_000)
  const showcase=await showcaseSeed(request)
  await apiLogin(request)
  const response=await request.get(`${process.env.AEROLINK_E2E_API_BASE}/api/downstream-assessments?projectId=${showcase.projectId}&releaseId=${showcase.activeReleaseId}&targetLevel=HighLevel`)
  expect(response.ok(),await response.text()).toBeTruthy()
  const rows=await response.json()
  const candidates=rows.filter((row:{state:string;capabilities:{canAssign:boolean;canEdit:boolean}})=>row.state==='Open'&&(row.capabilities.canAssign||row.capabilities.canEdit))
  expect(candidates.length,'An actionable HLR assessment').toBeGreaterThan(0)
  let candidate=candidates[0]
  for(const row of candidates){
    const impacts=await Promise.all(row.sourceChanges.map((change:{displayNumber:string})=>request.get(`${process.env.AEROLINK_E2E_API_BASE}/api/authoring/impact?projectId=${showcase.projectId}&baseNumber=${change.displayNumber.replace(/\.\d{2}$/,'')}`).then(result=>result.json())))
    if(impacts.every(impact=>impact.derivedRequirements.length===0)){candidate=row;break}
  }

  await login(page)
  await page.goto(`/programs/${showcase.programId}/projects/${showcase.projectId}/releases/${showcase.activeReleaseId}/software/change-requests?level=HLR&assessment=${candidate.id}`)
  const drawer=page.getByRole('dialog',{name:`${candidate.sourceChangeRequestNumber} downstream impact`})
  await expect(drawer).toBeVisible({timeout:30_000})
  await expect(drawer.getByRole('heading',{name:'Source change request'})).toBeVisible()
  await expect(drawer.getByText(candidate.sourceProblem).first()).toBeVisible()
  await page.reload()
  await expect(drawer).toBeVisible()
  expect(page.url()).toContain(`assessment=${candidate.id}`)
  if(candidate.sourceChanges.length)await expect(drawer.getByRole('heading',{name:'Approved requirement changes'})).toBeVisible()
  const emptyTrace=drawer.getByText('No current downward requirement trace is recorded for the changed requirements.')
  if(await emptyTrace.count())await expect(emptyTrace).toBeVisible()
  await drawer.getByRole('button',{name:new RegExp(candidate.sourceChangeRequestNumber)}).click()
  await expect(page).toHaveURL(new RegExp(`/systems/change-requests/${candidate.sourceChangeRequestId}$`))
  await page.goBack()
  await expect(drawer).toBeVisible()
  await drawer.getByRole('button',{name:'Close downstream assessment'}).click()
  await expect(page).not.toHaveURL(/assessment=/)

  const assessment=page.locator('.downstreamAssessment').filter({hasText:candidate.sourceChangeRequestNumber}).first()
  if(await assessment.getByRole('button',{name:'Take it on'}).count())await assessment.getByRole('button',{name:'Take it on'}).click()
  await assessment.getByRole('button',{name:'Change required',exact:true}).click()
  await expect(assessment).toContainText('HLR change required — SWCR pending')
  await assessment.getByRole('button',{name:'Create Draft HLR SWCR'}).click()
  await expect(page.getByRole('heading',{name:'Create HLR Change Request'})).toBeVisible()
  await page.getByLabel('Title').fill(`Implement ${candidate.sourceChangeRequestNumber} downstream impact`)
  let failLinkOnce=true
  await page.route('**/api/downstream-assessments/*/change-requests',route=>{
    if(failLinkOnce){failLinkOnce=false;return route.fulfill({status:500,contentType:'application/json',body:JSON.stringify({error:'Simulated recoverable link outage.'})})}
    return route.continue()
  })
  await page.getByRole('button',{name:'Save SWCR Draft'}).click()
  await expect(page).toHaveURL(/\/software\/change-requests\/[0-9a-f-]+$/i)
  const createdId=page.url().split('/').pop()!
  const recovery=page.getByRole('alert').filter({hasText:'Downstream assessment link needs attention'})
  await expect(recovery).toBeVisible()
  await recovery.getByRole('button',{name:'Retry assessment link'}).click()
  await expect(recovery).toBeHidden()
  const persisted=await (await request.get(`${process.env.AEROLINK_E2E_API_BASE}/api/downstream-assessments?projectId=${showcase.projectId}&releaseId=${showcase.activeReleaseId}&targetLevel=HighLevel`)).json()
  const updated=persisted.find((row:{id:string})=>row.id===candidate.id)
  expect(updated.outcome).toBe('ChangeRequestsLinked')
  expect(updated.linkedChangeRequests.some((link:{changeRequestId:string})=>link.changeRequestId===createdId)).toBeTruthy()
})
