import { expect, test } from '@playwright/test'
import { apiLogin, login, openNavigationGroup, showcaseSeed } from './auth'

test('downstream assessment actions follow authority and submit without a form-navigation no-op', async ({page,request,browser}) => {
  const showcase=await showcaseSeed(request)
  await apiLogin(request)
  const apiResponse=await request.get(`${process.env.AEROLINK_E2E_API_BASE}/api/downstream-assessments?projectId=${showcase.projectId}&releaseId=${showcase.activeReleaseId}`)
  expect(apiResponse.ok(),await apiResponse.text()).toBeTruthy()
  expect((await apiResponse.json()).length).toBeGreaterThan(0)

  const unauthorizedContext=await browser.newContext()
  const unauthorized=await unauthorizedContext.newPage()
  await login(unauthorized,'systems.reviewer')
  await openNavigationGroup(unauthorized,'SOFTWARE ENGINEERING')
  await unauthorized.getByRole('link',{name:'Software Change Requests'}).click()
  const unauthorizedQueue=unauthorized.locator('.downstreamQueue')
  await expect(unauthorizedQueue.getByRole('button',{name:'Take it on'})).toHaveCount(0)
  await expect(unauthorizedQueue).toContainText('Software engineering authority is required')
  await unauthorizedContext.close()

  await login(page)
  await openNavigationGroup(page,'SOFTWARE ENGINEERING')
  await page.getByRole('link',{name:'Software Change Requests'}).click()

  await expect(page.getByRole('heading',{name:'Downstream change assessments'})).toBeVisible()
  const queue=page.locator('.downstreamQueue')
  await expect(queue.getByText('SCR-00031.00')).toBeVisible()
  await expect(queue.getByText('HLR assessment').first()).toBeVisible()
  await expect(queue.getByRole('button',{name:'Take it on'}).first()).toBeVisible()
  await expect(queue).toContainText('One Draft may answer several assessments')
  await expect(page.getByRole('heading',{name:'Software Change Requests'})).toBeVisible()

  const assessment=queue.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await assessment.getByRole('button',{name:'Take it on'}).click()
  await expect(assessment.getByRole('button',{name:'No change required'})).toBeVisible()
  await assessment.getByRole('button',{name:'No change required'}).click()
  const noChangeDialog=page.getByRole('dialog',{name:'Record no-change conclusion for SCR-00031.00'})
  await expect(noChangeDialog).toBeVisible()
  await expect(noChangeDialog.getByRole('button',{name:'Record no-change conclusion'})).toBeDisabled()
  await noChangeDialog.getByLabel('Decision rationale').fill('No software requirement change is required for this build.')
  await noChangeDialog.getByRole('button',{name:'Record no-change conclusion'}).click()
  await expect(noChangeDialog).toBeHidden()
  const approver=assessment.getByLabel(/Approver for SCR-00031\.00/)
  await approver.fill('software.lead')
  await assessment.locator('.personSuggestions button[data-user-name="software.lead"]').click()
  await assessment.getByRole('button',{name:'Send for approval'}).click()
  await expect(assessment).toContainText('Awaiting approval')
  await page.reload()
  const persisted=page.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await expect(persisted).toContainText('Awaiting approval')
  await expect(persisted.locator('.personName[title="software.lead"]')).toBeVisible()

  const approverContext=await browser.newContext()
  const approverPage=await approverContext.newPage()
  await login(approverPage,'software.lead')
  await openNavigationGroup(approverPage,'SOFTWARE ENGINEERING')
  await approverPage.getByRole('link',{name:'Software Change Requests'}).click()
  const approvalAssessment=approverPage.locator('.downstreamAssessment').filter({hasText:'SCR-00031.00'}).first()
  await approvalAssessment.getByRole('button',{name:'Return'}).click()
  const returnDialog=approverPage.getByRole('dialog',{name:'Return SCR-00031.00 assessment'})
  await expect(returnDialog).toBeVisible()
  await expect(returnDialog.getByRole('button',{name:'Return assessment'})).toBeDisabled()
  await returnDialog.getByLabel('Decision rationale').fill('Clarify the software-level allocation before approval.')
  await returnDialog.getByRole('button',{name:'Return assessment'}).click()
  await expect(returnDialog).toBeHidden()
  await expect(approvalAssessment).toContainText('Open')
  await expect(approvalAssessment).toContainText('Clarify the software-level allocation before approval.')
  await approverContext.close()
})
