import { expect, renderedTest as test, type Page } from './isolated-client-test'

// The FMS test bench is self-contained: the scripted CMA-9000 runs in the page, so this needs no backend.
// Engine rules are proved in fms-cdu-engine.spec.ts; this proves the rendered panel wires them to real
// pointer, touch-style hold and keyboard input, and that a hardware variation relabels the physical keys.
const open = async (page: Page) => {
  await page.addInitScript(() => { try { window.localStorage.clear() } catch { /* private mode */ } })
  await page.goto('/tests/fixtures/fms-cdu.html')
  await expect(page.locator('.fmsCdu')).toBeVisible()
}
// The bench's tools sit in tabs under the cockpit (Scenarios first).
const tab = (page: Page, name: string) => page.getByRole('tab', { name, exact: true }).click()
const key = (page: Page, id: string) => page.locator(`.fmsCduKey[data-key="${id}"]`)
const screenLines = async (page: Page) => ((await page.locator('.fmsCduScreen').getAttribute('aria-label')) ?? '').split('\n')
const expectLine = async (page: Page, line: number, pattern: RegExp) =>
  expect.poll(async () => (await screenLines(page))[line] ?? '').toMatch(pattern)

test('keys on the rendered panel enter data, make a modification and execute it', async ({ page }) => {
  await open(page)
  await expectLine(page, 0, /^IDENT/)
  await key(page, 'RTE').click()
  await expectLine(page, 0, /^ACT RTE 1/)
  for (const letter of 'CYYZ') await key(page, letter).click()
  await expectLine(page, 13, /^CYYZ/)
  await key(page, 'LSK1R').click()
  await expectLine(page, 0, /^MOD RTE 1/)
  await expect(page.locator('.fmsCduLamp[data-lamp="EXEC_LIGHT"]')).toHaveClass(/\blit\b/)
  await key(page, 'EXEC').click()
  await expectLine(page, 0, /^ACT RTE 1/)
  await expectLine(page, 2, /CYYZ\s*$/)
  await expect(page.locator('.fmsCduLamp[data-lamp="EXEC_LIGHT"]')).not.toHaveClass(/\blit\b/)
  await tab(page, 'Lighting and keys')
  await expect(page.locator('.fmsBenchLog li').first()).toContainText('EXEC')
})

test('a held key shows the pressed render, and CLR held for a second clears the whole scratchpad', async ({ page }) => {
  await open(page)
  for (const letter of 'ABC') await key(page, letter).click()
  const clr = key(page, 'CLR')
  const box = (await clr.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await expect(clr).toHaveClass(/\bpressed\b/)
  expect(await clr.evaluate(element => getComputedStyle(element).backgroundImage)).toContain('pressed.webp')
  await expectLine(page, 13, /^\s*$/)
  await page.mouse.up()
  await expect(clr).not.toHaveClass(/\bpressed\b/)
  await expectLine(page, 13, /^\s*$/)

  for (const letter of 'ABC') await key(page, letter).click()
  await clr.click()
  await expectLine(page, 13, /^AB\s*$/)
})

test('choosing a hardware variation relabels the same physical keys and annunciators', async ({ page }) => {
  await open(page)
  await expect(key(page, 'F2_2')).toHaveAttribute('aria-label', 'FUEL')
  await expect(page.locator('.fmsCduLamp').nth(5)).toHaveText('GSM')
  await page.getByRole('combobox', { name: 'Hardware variation' }).selectOption('030/430')
  await expect(key(page, 'F2_2')).toHaveAttribute('aria-label', 'TPDR')
  await expect(page.locator('.fmsCduLamp').nth(5)).toHaveText('TX1')
  await key(page, 'F2_2').click()
  await expectLine(page, 0, /^RADIO\s+2\/2$/)
})

test('the physical keyboard drives the focused panel', async ({ page }) => {
  await open(page)
  await page.locator('.fmsCdu').focus()
  await page.keyboard.type('cyyz')
  await expectLine(page, 13, /^CYYZ/)
  await page.keyboard.press('Backspace')
  await expectLine(page, 13, /^CYY\s*$/)
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Backspace')
  await key(page, 'RTE').click()
  await page.keyboard.press('F1')
  await expectLine(page, 13, /^CYOW/)
})

// R18: a press the panel loses (focus moves away, the pointer is cancelled) is abandoned; its CLR hold never fires later.
test('a CLR hold interrupted by leaving the panel or a cancelled pointer never clears the scratchpad later (R18)', async ({ page }) => {
  await open(page)
  const panel = page.locator('.fmsCdu')
  const clrEvents = () => page.locator('.fmsBenchLog li', { hasText: 'CLR' }).count()
  await panel.focus()
  await page.keyboard.type('abc')
  await expectLine(page, 13, /^ABC\s*$/)
  const before = await clrEvents()

  // Hold Backspace (CLR), move focus to the heading field before the one-second hold completes, release it there.
  await page.keyboard.down('Backspace')
  await page.waitForTimeout(150)
  await page.getByLabel('Selected heading').focus()
  await page.keyboard.up('Backspace')
  await page.waitForTimeout(1300)
  expect((await screenLines(page))[13]).toMatch(/^ABC\s*$/)
  expect(await clrEvents()).toBe(before)
  await expect(key(page, 'CLR')).not.toHaveClass(/\bpressed\b/)

  // A pointer press on CLR that the browser cancels neither completes as a short press nor as a hold.
  const clr = key(page, 'CLR')
  const box = (await clr.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await clr.dispatchEvent('pointercancel', { pointerId: 1, bubbles: true })
  await page.waitForTimeout(1300)
  await page.mouse.up()
  expect((await screenLines(page))[13]).toMatch(/^ABC\s*$/)
  expect(await clrEvents()).toBe(before)
  await expect(clr).not.toHaveClass(/\bpressed\b/)
})

test('an alert raised from the bench lights MSG until CLR on the panel acknowledges it', async ({ page }) => {
  await open(page)
  const msg = page.locator('.fmsCduLamp[data-lamp="MSG"]')
  await expect(msg).not.toHaveClass(/\blit\b/)
  await tab(page, 'Conditions')
  await page.getByLabel('Alert message to raise').fill('unable rnp')
  await page.getByRole('button', { name: 'Raise alert' }).click()
  await expect(msg).toHaveClass(/\blit\b/)
  await expectLine(page, 13, /^UNABLE RNP/)
  await key(page, 'CLR').click()
  await expect(msg).not.toHaveClass(/\blit\b/)
})

test('every physical key on the rendered panel can be clicked and reaches the simulation', async ({ page }) => {
  await open(page)
  await page.getByRole('combobox', { name: 'Hardware variation' }).selectOption('050')
  const keys = page.locator('.fmsCduKey')
  const count = await keys.count()
  expect(count).toBe(68)
  // A real pointer click at each key's centre. force skips only Playwright's per-click readiness waits: a key covered by
  // anything else would take no click, and the count below would say so.
  for (let i = 0; i < count; i += 1) await keys.nth(i).click({ force: true })
  await tab(page, 'Lighting and keys')
  await expect(page.locator('.fmsBenchLog h2 small')).toHaveText(String(count))
})

test('conditions from the bench light the panel annunciators, and FMS failure blanks the display', async ({ page }) => {
  await open(page)
  const lamp = (code: string) => page.locator(`.fmsCduLamp[data-lamp="${code}"]`)
  // With GPS lost the FMS updates from radio; only with the DMEs lost as well does it dead reckon and light POS.
  await tab(page, 'Conditions')
  await page.getByRole('checkbox', { name: /^GPS lost sensor/ }).check()
  await expectLine(page, 13, /^GPS NAV LOST/)
  await expect(lamp('POS')).not.toHaveClass(/\blit\b/)
  await page.getByRole('checkbox', { name: /^DME outage/ }).check()
  await expect(lamp('POS')).toHaveClass(/\blit\b/)
  await page.getByLabel('Subsystem request').check()
  await expect(lamp('MENU_LIGHT')).toHaveClass(/\blit\b/)

  await page.getByLabel('FMS failure').check()
  await expect(lamp('FAIL')).toHaveClass(/\blit\b/)
  await expect(lamp('POS')).not.toHaveClass(/\blit\b/)
  await expect.poll(async () => (await screenLines(page)).join('').trim()).toBe('')
  await key(page, 'RTE').click()
  await expect.poll(async () => (await screenLines(page)).join('').trim()).toBe('')
  await page.getByLabel('FMS failure').uncheck()
  await expectLine(page, 0, /^IDENT/)
})

test('a library alert and a sequenced waypoint reach the panel', async ({ page }) => {
  await open(page)
  await tab(page, 'Conditions')
  await page.getByRole('combobox', { name: 'Alert from the manual' }).selectOption('TIMER ALARM')
  await page.getByRole('button', { name: 'Raise', exact: true }).click()
  await expectLine(page, 13, /^TIMER ALARM/)
  await expect(page.locator('.fmsCduLamp[data-lamp="MSG"]')).toHaveClass(/\blit\b/)
  await expect(page.locator('.fmsBench')).toContainText('Active waypoint MUN')
  await page.getByRole('button', { name: 'Jump to next waypoint' }).click()
  await expect(page.locator('.fmsBench')).toContainText('Active waypoint RDG')
  await key(page, 'LEGS').click()
  await expectLine(page, 2, /^RDG/)
})

test('NVG lighting backlights the legends green and holds the display in the NVG range; ambient light moves it', async ({ page }) => {
  await open(page)
  const panel = page.locator('.fmsCdu')
  const luminance = async () => Number(await panel.getAttribute('data-luminance'))
  const day = await luminance()
  await tab(page, 'Lighting and keys')
  await page.getByText('NVG', { exact: true }).click()
  await expect(panel).toHaveClass(/\bmode-nvg\b/)
  expect(await luminance()).toBeLessThanOrEqual(3)
  const legend = await key(page, 'A').evaluate(element => getComputedStyle(element).color)
  expect(legend).toBe('rgb(140, 245, 106)')
  const dim = await luminance()
  await page.getByRole('slider', { name: 'Ambient light' }).fill('100')
  await expect.poll(luminance).toBeGreaterThan(dim)
  expect(await luminance()).toBeLessThanOrEqual(3)
  await page.getByText('Day', { exact: true }).click()
  await expect.poll(luminance).toBe(day)
})

test('Fly moves the aircraft along the route on the map at the chosen rate, and Pause stops it', async ({ page }) => {
  await open(page)
  // The engineering map shares the lower display beside the CDU with the ND; the ND is shown first.
  await expect(page.getByRole('img', { name: /^Navigation display/ })).toBeVisible()
  await page.getByRole('radiogroup', { name: 'Lower display' }).getByText('Engineering map').click()
  const map = page.getByRole('img', { name: /^Navigation map/ })
  await expect(map).toHaveAttribute('aria-label', /LNAV mode, active waypoint MUN/)
  const readout = page.locator('.fmsBench').getByText(/^Active waypoint/)
  const toGo = async () => Number((await readout.innerText()).match(/([\d.]+) NM/)?.[1] ?? NaN)
  const start = await toGo()
  await page.getByLabel('Simulation rate').selectOption('64')
  await page.getByRole('button', { name: 'Fly' }).click()
  // At 64 times real time the aircraft closes on MUN at about two nautical miles a second (sequencing past a
  // waypoint is proved in the logic tier).
  await expect.poll(toGo).toBeLessThan(start - 2)
  await expect(map).toHaveAttribute('aria-label', /LNAV mode, active waypoint MUN/)
  await expect(page.getByLabel('Guidance')).toContainText('LNAV')
  await page.getByRole('button', { name: 'Pause' }).click()
  const paused = await readout.innerText()
  // Unpaused, a second at 64 times would move the aircraft about two miles.
  await page.waitForTimeout(1000)
  await expect(page.locator('.fmsBench').getByText(/^Active waypoint/)).toHaveText(paused)
  await page.getByLabel('Map range').selectOption('80')
  await expect(map).toHaveAttribute('aria-label', /80 NM range/)
})

test('IDENT shows both database cycles, and the maintenance page follows a self test and independent operation', async ({ page }) => {
  await open(page)
  await expectLine(page, 4, /^DEMO-2609\s+03SEP-30SEP$/)
  await expectLine(page, 6, /^DEMO-2610\s+01OCT-28OCT$/)
  await key(page, 'INIT_REF').click()
  await key(page, 'LSK6L').click()
  await expectLine(page, 0, /^MAINTENANCE/)
  await page.getByLabel('Simulation rate').selectOption('64')
  await key(page, 'LSK2L').click()
  await expectLine(page, 4, /(IN PROG|PASS)$/)
  // The self test runs for five seconds of simulation time: flying at 64 times, a fraction of a second.
  await page.getByRole('button', { name: 'Fly' }).click()
  await expect.poll(async () => (await screenLines(page))[4] ?? "").toMatch(/PASS$/)
  await page.getByRole('button', { name: 'Pause' }).click()
  await expectLine(page, 6, /^DUAL SYNC\s+RTE MATCH$/)
  await tab(page, 'Conditions')
  await page.getByLabel('Independent operation').check()
  await expectLine(page, 6, /^INDEPENDENT\s+RTE MATCH$/)
  await expectLine(page, 8, /^\d{4}Z X-SIDE SYNC LOST/)
})

test('a built-in scenario runs on the bench with its steps checked live, and gives a report and procedure text', async ({ page }) => {
  await open(page)
  const card = page.getByRole('region', { name: 'Scenarios' })
  await page.getByLabel('Simulation rate').selectOption('64')
  await card.getByLabel('Scenario', { exact: true }).selectOption({ label: 'Crew RNP the navigation cannot meet' })
  await card.getByRole('button', { name: 'Run the scenario' }).click()
  await expectLine(page, 0, /PROGRESS/)
  await expect(card.getByRole('status').filter({ hasText: /^PASS/ })).toBeVisible({ timeout: 30_000 })
  await expect(card.getByRole('list', { name: 'Scenario steps' }).locator('li[data-status="pass"]')).toHaveCount(5)
  const [report] = await Promise.all([page.waitForEvent('download'), card.getByRole('button', { name: 'Download run report' }).click()])
  expect(report.suggestedFilename()).toBe('crew-rnp-the-navigation-cannot-meet-run.md')
  await card.getByRole('button', { name: 'Test procedure text' }).click()
  await expect(card.getByLabel('Test procedure text')).toHaveValue(/Steps:\n1\. At the start, press PROG\.\n2\. Then type \.01 into the scratchpad\./)
})

test('a recording of panel keys and a screen check plays back as a scenario and passes', async ({ page }) => {
  await open(page)
  const card = page.getByRole('region', { name: 'Scenarios' })
  await card.getByRole('button', { name: 'Record' }).click()
  await card.getByLabel('Recording name').fill('Open PROG')
  await key(page, 'PROG').click()
  await expectLine(page, 0, /PROGRESS/)
  await card.getByLabel('Screen line to check').selectOption('0')
  await card.getByRole('button', { name: 'Add screen check' }).click()
  await card.getByRole('button', { name: 'Stop recording' }).click()
  await expect(card.getByRole('status').filter({ hasText: 'Recorded 2 steps as “Open PROG”.' })).toBeVisible()
  await expect(card.getByLabel('Scenario', { exact: true })).toHaveValue(/^recorded-/)
  await card.getByRole('button', { name: 'Run the scenario' }).click()
  await expect(card.getByRole('status').filter({ hasText: /^PASS/ })).toBeVisible({ timeout: 15_000 })
})

test('an FMS failure in flight reverts the flight modes, and Pause still works (R02)', async ({ page }) => {
  await open(page)
  await page.getByLabel('Simulation rate').selectOption('16')
  await page.getByRole('button', { name: 'Fly' }).click()
  const modes = page.getByRole('status', { name: 'Flight modes' })
  await expect(modes).toContainText('LNAV')
  await tab(page, 'Conditions')
  await page.getByLabel('FMS failure').check()
  await expect(modes).toContainText('HDG HOLD')
  await expect(modes).toContainText('ALT HOLD')
  await expect(page.getByText(/^Last mode change: FMS FAILURE/)).toBeVisible()
  // Pause is a bench control: it stays usable whatever has failed in the simulated aircraft.
  const pause = page.getByRole('button', { name: 'Pause' })
  await expect(pause).toBeEnabled()
  await pause.click()
  await expect(page.getByRole('button', { name: 'Fly' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'LNAV', exact: true })).toBeDisabled()
})

test('the EFIS shows the FMS modes, route and TO waypoint, and flags them when the FMS fails', async ({ page }) => {
  await open(page)
  const efis = page.getByRole('region', { name: 'EFIS' })
  await expect(efis.getByTestId('fma-lateral')).toHaveText('LNAV')
  await expect(efis.getByTestId('nd-to-wpt')).toContainText('MUN')
  await expect(efis.getByTestId('nd-route')).toBeVisible()
  await expect(efis.getByTestId('nav-source')).toHaveText(/^FMS1 TERM$/)
  await tab(page, 'Conditions')
  await page.getByLabel('FMS failure').check()
  await page.getByLabel('Simulation rate').selectOption('4')
  await page.getByRole('button', { name: 'Fly' }).click()
  await expect(efis.getByTestId('pfd-fms-flag')).toHaveText('FMS FAIL')
  await expect(efis.getByTestId('nd-map-flag')).toHaveText('MAP')
  await expect(efis.getByTestId('nd-route')).toHaveCount(0)
  await expect(efis.getByTestId('fma-lateral')).toHaveText('HDG HOLD')
  await expect(efis.getByTestId('fma-vertical')).toHaveText('ALT HOLD')
})

test('the bench tools are tabs under the cockpit, keyboard-navigable, and the chosen one is remembered', async ({ page }) => {
  // A fresh context starts with no remembered tab; this test keeps what it stores across the reload.
  await page.goto('/tests/fixtures/fms-cdu.html')
  await expect(page.locator('.fmsCdu')).toBeVisible()
  const tabs = page.getByRole('tablist', { name: 'Bench tools' }).getByRole('tab')
  await expect(tabs).toHaveText(['Scenarios', 'Conditions', 'GPS sensors', 'Nav data', 'Lighting and keys'])
  await expect(page.getByRole('tab', { name: 'Scenarios' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('region', { name: 'Scenarios' })).toBeVisible()
  await tab(page, 'GPS sensors')
  await expect(page.getByRole('tab', { name: 'GPS sensors' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('region', { name: 'GPS 1', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'GPS 2', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Scenarios' })).toBeHidden()
  await page.reload()
  await expect(page.getByRole('tab', { name: 'GPS sensors' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('region', { name: 'Sensor routing' })).toBeVisible()
  await page.getByRole('tab', { name: 'GPS sensors' }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: 'Nav data' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByLabel('ARINC 424 navigation data file')).toBeVisible()
})

test('the GPS sensors tab drives the FMS receivers: a fault on GPS 1 moves the FMS to GPS 2, both give GPS NAV LOST', async ({ page }) => {
  // The bench starts its simulated time at the wall clock, and the sky moves with it: pin it, so the geometry is the same
  // whenever the test runs.
  await page.clock.setFixedTime(new Date('2026-09-28T14:00:00Z'))
  await open(page)
  await tab(page, 'GPS sensors')
  const gps1 = page.getByRole('region', { name: 'GPS 1', exact: true })
  const gps2 = page.getByRole('region', { name: 'GPS 2', exact: true })
  const routing = page.getByRole('img', { name: /^Sensor routing/ })
  // The FMS's receivers start warm, navigating; the FMS is on GPS 1.
  await expect(gps1.getByTestId('gps-mode')).toHaveText(/^(NAV|SBAS NAV)$/)
  await expect(gps2.getByTestId('gps-mode')).toHaveText(/^(NAV|SBAS NAV)$/)
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS1$/)
  await expect(page.getByTestId('route-link-gps1')).not.toHaveClass(/dashed/)
  await expect(gps1.getByTestId('gps-in-use')).toBeVisible()

  const used = async () => Number(((await gps1.getByTestId('gps-used').innerText()).split('/'))[0])
  const before = await used()
  // Mask one satellite GPS 1 is using: whatever the sky, it is then used one fewer.
  const prn = await gps1.getByRole('list', { name: 'Signal strength, dB-Hz' }).locator('li:has(.bar.used) small').first().innerText()
  await page.getByRole('group', { name: 'GPS 1 mask satellites' }).getByRole('button', { name: prn, exact: true }).click()
  await expect.poll(used).toBe(before - 1)
  await expect(gps1.getByRole('list', { name: 'GPS 1 active faults' })).toContainText('1 MASKED')

  // A GPS 1 receiver fault reaches the FMS at once: it navigates on GPS 2, and the strip shows it.
  await page.getByLabel('GPS 1 Receiver fault').check()
  await expect(gps1.getByTestId('gps-mode')).toHaveText('FAULT')
  await expect(gps1.getByRole('list', { name: 'GPS 1 active faults' })).toContainText('RECEIVER FAULT')
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS2$/)
  await expect(page.getByTestId('route-link-gps1')).toHaveClass(/dashed/)
  await expect(page.getByTestId('route-link-gps2')).not.toHaveClass(/dashed/)
  await expect(gps2.getByTestId('gps-in-use')).toBeVisible()
  // Its bus: position words Failure Warning, the status word still Normal.
  await page.getByText('GPS 1 bus monitor').click()
  const monitor = page.getByRole('table', { name: 'GPS 1 bus monitor' })
  await expect(monitor.locator('tr[data-label="110"] .fmsGpsSsm')).toHaveText('FW')
  await expect(monitor.locator('tr[data-label="273"] .fmsGpsSsm')).toHaveText('NORMAL')

  // Both faulted: the FMS has no GPS and says so on the CDU.
  await page.getByLabel('GPS 2 Receiver fault').check()
  await expectLine(page, 13, /^GPS NAV LOST/)
  await expect(routing).not.toHaveAttribute('aria-label', /FMS on GPS/)

  // The product's 12 px text floor (tests/production) holds across the tab, open monitor and chips included.
  const small = await page.locator('.fmsGps').evaluate(root => [...root.querySelectorAll('*')]
    .filter(element => element.children.length === 0 && (element.textContent ?? '').trim() && parseFloat(getComputedStyle(element).fontSize) < 12)
    .map(element => `${element.tagName}.${element.getAttribute('class') ?? ''} ${getComputedStyle(element).fontSize}`))
  expect(small).toEqual([])
})

test('the FMS GPS selection is set from the routing strip, and the integrity condition holds the satellite masking', async ({ page }) => {
  await open(page)
  await tab(page, 'GPS sensors')
  const routing = page.getByRole('img', { name: /^Sensor routing/ })
  // In use and standby are the FMS's own judgement of each receiver: GPS 2 usable, so an eligible standby.
  await expect(page.getByTestId('route-gps1')).toContainText('in use')
  await expect(page.getByTestId('route-gps2')).toContainText('standby')
  // GPS 1's HIL forced to 99 NM: still navigating internally, but the FMS rejects it for integrity and says why.
  await page.getByText('GPS 1 bus monitor').click()
  const hil = page.getByRole('table', { name: 'GPS 1 bus monitor' }).locator('tr[data-label="130"]')
  await hil.getByLabel('Override 130', { exact: true }).selectOption('FORCE')
  await hil.getByLabel('Override 130 amount').fill('99')
  await hil.getByRole('button', { name: 'Set' }).click()
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS2$/)
  await expect(page.getByTestId('route-gps1')).toContainText('not usable · HIL over limit')
  await expect(page.getByTestId('route-gps1')).not.toContainText('standby')
  await expect(page.getByTestId('route-gps2')).toContainText('in use')
  await hil.getByRole('button', { name: 'Clear' }).click()
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS1$/)
  await page.getByLabel('FMS GPS selection').selectOption('GPS2')
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS2$/)
  await page.getByLabel('FMS GPS selection').selectOption('OFF')
  await expect(routing).not.toHaveAttribute('aria-label', /FMS on GPS/)
  await page.getByLabel('FMS GPS selection').selectOption('AUTO')
  await expect(routing).toHaveAttribute('aria-label', /FMS on GPS1$/)
  const faults = page.getByRole('region', { name: 'GPS 1 faults' })
  await expect(faults.getByRole('button', { name: /^Mask low satellites/ })).toBeEnabled()
  await tab(page, 'Conditions')
  await page.getByRole('checkbox', { name: /^GPS integrity lost/ }).check()
  await tab(page, 'GPS sensors')
  await expect(faults.getByRole('note')).toContainText('GPS integrity lost condition holds')
  await expect(faults.getByRole('button', { name: /^Mask low satellites/ })).toBeDisabled()
})

test('a status word is overridden field by field from the bus monitor: what is transmitted changes, not what the receiver knows', async ({ page }) => {
  await open(page)
  await tab(page, 'GPS sensors')
  const gps1 = page.getByRole('region', { name: 'GPS 1', exact: true })
  await page.getByLabel('Simulation rate').selectOption('64')
  await page.getByRole('button', { name: 'Fly' }).click()
  await expect(gps1.getByTestId('gps-mode')).toHaveText(/^(NAV|SBAS NAV)$/, { timeout: 20_000 })
  await page.getByRole('button', { name: 'Pause' }).click()
  await page.getByText('GPS 1 bus monitor').click()
  const monitor = page.getByRole('table', { name: 'GPS 1 bus monitor' })
  const row = monitor.locator('tr[data-label="273"]')
  await row.getByLabel('Status field 273').selectOption('mode')
  await row.getByLabel('Status value 273').selectOption('FAULT')
  await row.getByRole('button', { name: 'Set' }).click()
  await expect(row.locator('td.value')).toContainText('mode FAULT')
  await expect(row).toContainText('FORCE mode')
  // The card shows the receiver itself, still navigating; the scaling word has no approach to scale.
  await expect(gps1.getByTestId('gps-mode')).toHaveText(/^(NAV|SBAS NAV)$/)
  await expect(monitor.locator('tr[data-label="scale"] .fmsGpsSsm')).toHaveText('NCD')
  await row.getByRole('button', { name: 'Clear' }).click()
  await expect(row.locator('td.value')).not.toContainText('mode FAULT')
})

test('GPS faults and overrides survive leaving the tab: shown, cleared one at a time, and an unrelated change leaves them alone', async ({ page }) => {
  await open(page)
  await tab(page, 'GPS sensors')
  const gps1 = page.getByRole('region', { name: 'GPS 1', exact: true })
  const stopped = page.getByLabel('GPS 1 Stop transmitting')
  await stopped.check()
  await expect(gps1).toContainText('NOT TRANSMITTING')
  await page.getByText('GPS 2 bus monitor').click()
  const hil = page.getByRole('table', { name: 'GPS 2 bus monitor' }).locator('tr[data-label="130"]')
  await hil.getByLabel('Override 130', { exact: true }).selectOption('FORCE')
  await hil.getByLabel('Override 130 amount').fill('99')
  await hil.getByRole('button', { name: 'Set' }).click()
  await expect(hil.locator('td.value')).toHaveText('99')

  // A real round trip: the tab is unmounted and mounted again.
  await tab(page, 'Conditions')
  await tab(page, 'GPS sensors')
  await expect(stopped).toBeChecked()
  await expect(gps1.getByRole('list', { name: 'GPS 1 active faults' })).toContainText('STOPPED TRANSMITTING')
  await expect(gps1).toContainText('NOT TRANSMITTING')
  await page.getByText('GPS 2 bus monitor').click()
  await expect(hil.locator('td.value')).toHaveText('99')
  await expect(hil).toContainText('FORCE 99')
  await expect(hil.getByRole('button', { name: 'Clear' })).toBeVisible()

  // An unrelated control changes only its own fault: GPS 1 stays silent.
  await page.getByLabel('GPS 1 Baro lost').check()
  await expect(gps1).toContainText('NOT TRANSMITTING')
  await expect(gps1.getByRole('list', { name: 'GPS 1 active faults' })).toContainText('BARO LOST')
  await expect(gps1.getByRole('list', { name: 'GPS 1 active faults' })).toContainText('STOPPED TRANSMITTING')

  // A targeted clear removes that override only.
  await hil.getByRole('button', { name: 'Clear' }).click()
  await expect(hil.locator('td.value')).not.toHaveText('99')
  await expect(hil.getByRole('button', { name: 'Clear' })).toHaveCount(0)
  await expect(stopped).toBeChecked()
  await expect(gps1).toContainText('NOT TRANSMITTING')
})

test('a numeric word can be forced with a status from the bus monitor, and the FMS rejects the receiver for it', async ({ page }) => {
  await open(page)
  await tab(page, 'GPS sensors')
  await page.getByText('GPS 1 bus monitor').click()
  const latitude = page.getByRole('table', { name: 'GPS 1 bus monitor' }).locator('tr[data-label="110"]')
  await latitude.getByLabel('Override 110', { exact: true }).selectOption('FORCE')
  await latitude.getByLabel('Override 110 amount').fill('45.3')
  await latitude.getByLabel('Override 110 status').selectOption('NCD')
  await latitude.getByRole('button', { name: 'Set' }).click()
  await expect(latitude.locator('.fmsGpsSsm')).toHaveText('NCD')
  await expect(latitude).toContainText('FORCE 45.3 NCD')
  // Without a NORMAL latitude there is no fix: the FMS navigates on GPS 2 and says why GPS 1 is not usable.
  await expect(page.getByRole('img', { name: /^Sensor routing/ })).toHaveAttribute('aria-label', /FMS on GPS2$/)
  await expect(page.getByTestId('route-gps1')).toContainText('not usable · no fix')
})
