import { expect, renderedTest as test, type Page } from './isolated-client-test'

// The FMS test bench is self-contained: the scripted CMA-9000 runs in the page, so this needs no backend.
// Engine rules are proved in fms-cdu-engine.spec.ts; this proves the rendered panel wires them to real
// pointer, touch-style hold and keyboard input, and that a hardware variation relabels the physical keys.
const open = async (page: Page) => {
  await page.addInitScript(() => { try { window.localStorage.clear() } catch { /* private mode */ } })
  await page.goto('/tests/fixtures/fms-cdu.html')
  await expect(page.locator('.fmsCdu')).toBeVisible()
}
const key = (page: Page, id: string) => page.locator(`.fmsCduKey[data-key="${id}"]`)
const screenLines = async (page: Page) => ((await page.locator('.fmsCduScreen').getAttribute('aria-label')) ?? '').split('\n')
const expectLine = async (page: Page, line: number, pattern: RegExp) =>
  expect.poll(async () => (await screenLines(page))[line] ?? '').toMatch(pattern)

test('keys on the rendered panel enter data, make a modification and execute it', async ({ page }) => {
  await open(page)
  await expectLine(page, 0, /^IDENT/)
  await key(page, 'RTE').click()
  await expectLine(page, 0, /^ACT RTE 1/)
  for (const letter of 'CYYZ') await key(page, letter).click()
  await expectLine(page, 13, /^CYYZ/)
  await key(page, 'LSK1R').click()
  await expectLine(page, 0, /^MOD RTE 1/)
  await expect(page.locator('.fmsCduLamp[data-lamp="EXEC_LIGHT"]')).toHaveClass(/\blit\b/)
  await key(page, 'EXEC').click()
  await expectLine(page, 0, /^ACT RTE 1/)
  await expectLine(page, 2, /CYYZ\s*$/)
  await expect(page.locator('.fmsCduLamp[data-lamp="EXEC_LIGHT"]')).not.toHaveClass(/\blit\b/)
  await expect(page.locator('.fmsBenchLog li').first()).toContainText('EXEC')
})

test('a held key shows the pressed render, and CLR held for a second clears the whole scratchpad', async ({ page }) => {
  await open(page)
  for (const letter of 'ABC') await key(page, letter).click()
  const clr = key(page, 'CLR')
  const box = (await clr.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await expect(clr).toHaveClass(/\bpressed\b/)
  expect(await clr.evaluate(element => getComputedStyle(element).backgroundImage)).toContain('pressed.webp')
  await expectLine(page, 13, /^\s*$/)
  await page.mouse.up()
  await expect(clr).not.toHaveClass(/\bpressed\b/)
  await expectLine(page, 13, /^\s*$/)

  for (const letter of 'ABC') await key(page, letter).click()
  await clr.click()
  await expectLine(page, 13, /^AB\s*$/)
})

test('choosing a hardware variation relabels the same physical keys and annunciators', async ({ page }) => {
  await open(page)
  await expect(key(page, 'F2_2')).toHaveAttribute('aria-label', 'FUEL')
  await expect(page.locator('.fmsCduLamp').nth(5)).toHaveText('GSM')
  await page.getByRole('combobox', { name: 'Hardware variation' }).selectOption('030/430')
  await expect(key(page, 'F2_2')).toHaveAttribute('aria-label', 'TPDR')
  await expect(page.locator('.fmsCduLamp').nth(5)).toHaveText('TX1')
  await key(page, 'F2_2').click()
  await expectLine(page, 0, /^RADIO\s+2\/2$/)
})

test('the physical keyboard drives the focused panel', async ({ page }) => {
  await open(page)
  await page.locator('.fmsCdu').focus()
  await page.keyboard.type('cyyz')
  await expectLine(page, 13, /^CYYZ/)
  await page.keyboard.press('Backspace')
  await expectLine(page, 13, /^CYY\s*$/)
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Backspace')
  await page.keyboard.press('Backspace')
  await key(page, 'RTE').click()
  await page.keyboard.press('F1')
  await expectLine(page, 13, /^CYOW/)
})

test('an alert raised from the bench lights MSG until CLR on the panel acknowledges it', async ({ page }) => {
  await open(page)
  const msg = page.locator('.fmsCduLamp[data-lamp="MSG"]')
  await expect(msg).not.toHaveClass(/\blit\b/)
  await page.getByLabel('Alert message to raise').fill('unable rnp')
  await page.getByRole('button', { name: 'Raise alert' }).click()
  await expect(msg).toHaveClass(/\blit\b/)
  await expectLine(page, 13, /^UNABLE RNP/)
  await key(page, 'CLR').click()
  await expect(msg).not.toHaveClass(/\blit\b/)
})

test('every physical key on the rendered panel can be clicked and reaches the simulation', async ({ page }) => {
  await open(page)
  await page.getByRole('combobox', { name: 'Hardware variation' }).selectOption('050')
  const keys = page.locator('.fmsCduKey')
  const count = await keys.count()
  expect(count).toBe(68)
  for (let i = 0; i < count; i += 1) await keys.nth(i).click()
  await expect(page.locator('.fmsBenchLog h2 small')).toHaveText(String(count))
})

test('conditions from the bench light the panel annunciators, and FMS failure blanks the display', async ({ page }) => {
  await open(page)
  const lamp = (code: string) => page.locator(`.fmsCduLamp[data-lamp="${code}"]`)
  // With GPS lost the FMS updates from radio; only with the DMEs lost as well does it dead reckon and light POS.
  await page.getByRole('checkbox', { name: /^GPS lost sensor/ }).check()
  await expectLine(page, 13, /^GPS NAV LOST/)
  await expect(lamp('POS')).not.toHaveClass(/\blit\b/)
  await page.getByRole('checkbox', { name: /^DME outage/ }).check()
  await expect(lamp('POS')).toHaveClass(/\blit\b/)
  await page.getByLabel('Subsystem request').check()
  await expect(lamp('MENU_LIGHT')).toHaveClass(/\blit\b/)

  await page.getByLabel('FMS failure').check()
  await expect(lamp('FAIL')).toHaveClass(/\blit\b/)
  await expect(lamp('POS')).not.toHaveClass(/\blit\b/)
  await expect.poll(async () => (await screenLines(page)).join('').trim()).toBe('')
  await key(page, 'RTE').click()
  await expect.poll(async () => (await screenLines(page)).join('').trim()).toBe('')
  await page.getByLabel('FMS failure').uncheck()
  await expectLine(page, 0, /^IDENT/)
})

test('a library alert and a sequenced waypoint reach the panel', async ({ page }) => {
  await open(page)
  await page.getByRole('combobox', { name: 'Alert from the manual' }).selectOption('TIMER ALARM')
  await page.getByRole('button', { name: 'Raise', exact: true }).click()
  await expectLine(page, 13, /^TIMER ALARM/)
  await expect(page.locator('.fmsCduLamp[data-lamp="MSG"]')).toHaveClass(/\blit\b/)
  await expect(page.locator('.fmsBench')).toContainText('Active waypoint MUN')
  await page.getByRole('button', { name: 'Jump to next waypoint' }).click()
  await expect(page.locator('.fmsBench')).toContainText('Active waypoint RDG')
  await key(page, 'LEGS').click()
  await expectLine(page, 2, /^RDG/)
})

test('NVG lighting backlights the legends green and holds the display in the NVG range; ambient light moves it', async ({ page }) => {
  await open(page)
  const panel = page.locator('.fmsCdu')
  const luminance = async () => Number(await panel.getAttribute('data-luminance'))
  const day = await luminance()
  await page.getByText('NVG', { exact: true }).click()
  await expect(panel).toHaveClass(/\bmode-nvg\b/)
  expect(await luminance()).toBeLessThanOrEqual(3)
  const legend = await key(page, 'A').evaluate(element => getComputedStyle(element).color)
  expect(legend).toBe('rgb(140, 245, 106)')
  const dim = await luminance()
  await page.getByRole('slider', { name: 'Ambient light' }).fill('100')
  await expect.poll(luminance).toBeGreaterThan(dim)
  expect(await luminance()).toBeLessThanOrEqual(3)
  await page.getByText('Day', { exact: true }).click()
  await expect.poll(luminance).toBe(day)
})

test('Fly moves the aircraft along the route on the map at the chosen rate, and Pause stops it', async ({ page }) => {
  await open(page)
  const map = page.getByRole('img', { name: /^Navigation map/ })
  await expect(map).toHaveAttribute('aria-label', /LNAV mode, active waypoint MUN/)
  await page.getByLabel('Simulation rate').selectOption('64')
  await page.getByRole('button', { name: 'Fly' }).click()
  // MUN is 13.6 NM away: at 64 times real time it is passed within a few seconds.
  await expect(map).toHaveAttribute('aria-label', /active waypoint RDG/, { timeout: 20_000 })
  await expect(page.getByLabel('Guidance')).toContainText('LNAV')
  await page.getByRole('button', { name: 'Pause' }).click()
  const paused = await page.locator('.fmsBench').getByText(/^Active waypoint/).innerText()
  await page.waitForTimeout(1500)
  await expect(page.locator('.fmsBench').getByText(/^Active waypoint/)).toHaveText(paused)
  await page.getByLabel('Map range').selectOption('80')
  await expect(map).toHaveAttribute('aria-label', /80 NM range/)
})

test('IDENT shows both database cycles, and the maintenance page follows a self test and independent operation', async ({ page }) => {
  await open(page)
  await expectLine(page, 4, /^DEMO-2609\s+03SEP-30SEP$/)
  await expectLine(page, 6, /^DEMO-2610\s+01OCT-28OCT$/)
  await key(page, 'INIT_REF').click()
  await key(page, 'LSK6L').click()
  await expectLine(page, 0, /^MAINTENANCE/)
  await key(page, 'LSK2L').click()
  await expectLine(page, 4, /(IN PROG|PASS)$/)
  // The self test runs for five seconds of simulation time.
  await expect.poll(async () => (await screenLines(page))[4] ?? "", { timeout: 15_000 }).toMatch(/PASS$/)
  await expectLine(page, 6, /^DUAL SYNC\s+RTE MATCH$/)
  await page.getByLabel('Independent operation').check()
  await expectLine(page, 6, /^INDEPENDENT\s+RTE MATCH$/)
  await expectLine(page, 8, /^\d{4}Z X-SIDE SYNC LOST/)
})

test('a built-in scenario runs on the bench with its steps checked live, and gives a report and procedure text', async ({ page }) => {
  await open(page)
  const card = page.getByRole('region', { name: 'Scenarios' })
  await page.getByLabel('Simulation rate').selectOption('64')
  await card.getByLabel('Scenario', { exact: true }).selectOption({ label: 'Crew RNP the navigation cannot meet' })
  await card.getByRole('button', { name: 'Run the scenario' }).click()
  await expectLine(page, 0, /PROGRESS/)
  await expect(card.getByRole('status').filter({ hasText: /^PASS/ })).toBeVisible({ timeout: 30_000 })
  await expect(card.getByRole('list', { name: 'Scenario steps' }).locator('li[data-status="pass"]')).toHaveCount(5)
  const [report] = await Promise.all([page.waitForEvent('download'), card.getByRole('button', { name: 'Download run report' }).click()])
  expect(report.suggestedFilename()).toBe('crew-rnp-the-navigation-cannot-meet-run.md')
  await card.getByRole('button', { name: 'Test procedure text' }).click()
  await expect(card.getByLabel('Test procedure text')).toHaveValue(/Steps:\n1\. At the start, press PROG\.\n2\. Then type \.03 into the scratchpad\./)
})

test('a recording of panel keys and a screen check plays back as a scenario and passes', async ({ page }) => {
  await open(page)
  const card = page.getByRole('region', { name: 'Scenarios' })
  await card.getByRole('button', { name: 'Record' }).click()
  await card.getByLabel('Recording name').fill('Open PROG')
  await key(page, 'PROG').click()
  await expectLine(page, 0, /PROGRESS/)
  await card.getByLabel('Screen line to check').selectOption('0')
  await card.getByRole('button', { name: 'Add screen check' }).click()
  await card.getByRole('button', { name: 'Stop recording' }).click()
  await expect(card.getByRole('status').filter({ hasText: 'Recorded 2 steps as “Open PROG”.' })).toBeVisible()
  await expect(card.getByLabel('Scenario', { exact: true })).toHaveValue(/^recorded-/)
  await card.getByRole('button', { name: 'Run the scenario' }).click()
  await expect(card.getByRole('status').filter({ hasText: /^PASS/ })).toBeVisible({ timeout: 15_000 })
})
