import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { Axis, Cartesian3, Event, Matrix3, Matrix4 } from '@cesium/engine'
import { expect, logicTest as test } from './isolated-client-test'
import { MAIN_ROTOR_RADIUS, buildHelicopterGlb } from '../src/fmsCdu/helicopterModel'
import { createAircraftModel, MAIN_ROTOR_RAD_S, TAIL_TO_MAIN, type CesiumModule } from '../src/fmsCdu/otwAircraftModel'

// Brief D (Sean, 29 September): the chase view's helicopter as a glTF model. No open-licence Airbus model could be
// downloaded without signing in, so Sean chose an original model of the class, generated by helicopterModel.ts.
const FILE = 'public/fms-cdu/models/helicopter-light-twin.glb'

/** The GLB's JSON chunk and binary chunk. */
function readGlb(bytes: Uint8Array) {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  expect(view.getUint32(0, true)).toBe(0x46546c67) // "glTF"
  expect(view.getUint32(4, true)).toBe(2)
  expect(view.getUint32(8, true)).toBe(bytes.byteLength)
  const jsonLength = view.getUint32(12, true)
  expect(view.getUint32(16, true)).toBe(0x4e4f534a) // "JSON"
  const json = JSON.parse(new TextDecoder().decode(bytes.subarray(20, 20 + jsonLength)))
  const binAt = 20 + jsonLength
  const binLength = view.getUint32(binAt, true)
  expect(view.getUint32(binAt + 4, true)).toBe(0x004e4942) // "BIN\0"
  return { json, bin: bytes.subarray(binAt + 8, binAt + 8 + binLength), view, binAt: binAt + 8 }
}

test('the committed model is exactly what the generator writes (regenerate with src/fmsCdu/buildHelicopterModel.mjs)', () => {
  const committed = readFileSync(FILE)
  const generated = buildHelicopterGlb()
  expect(createHash('sha256').update(committed).digest('hex')).toBe(createHash('sha256').update(generated).digest('hex'))
  // Small enough to serve with the bench (the brief's limit is about 5 MB).
  expect(committed.byteLength).toBeLessThan(5_000_000)
})

test('the GLB is well formed: every accessor fits its buffer view, every view its buffer, and no textures or images', () => {
  const { json, bin } = readGlb(buildHelicopterGlb())
  expect(json.asset.version).toBe('2.0')
  expect(json.buffers[0].byteLength).toBe(bin.byteLength)
  for (const view of json.bufferViews) {
    expect(view.byteOffset % 4).toBe(0)
    expect(view.byteOffset + view.byteLength).toBeLessThanOrEqual(bin.byteLength)
  }
  const size = { 5126: 4, 5123: 2, 5125: 4 } as Record<number, number>, width = { VEC3: 3, SCALAR: 1 } as Record<string, number>
  for (const accessor of json.accessors) {
    const view = json.bufferViews[accessor.bufferView]
    expect(accessor.count * width[accessor.type] * size[accessor.componentType]).toBeLessThanOrEqual(view.byteLength)
  }
  // Every index is inside its primitive's vertices.
  const data = new DataView(bin.buffer, bin.byteOffset, bin.byteLength)
  for (const mesh of json.meshes) for (const primitive of mesh.primitives) {
    const vertices = json.accessors[primitive.attributes.POSITION].count
    const indices = json.accessors[primitive.indices], view = json.bufferViews[indices.bufferView]
    let largest = 0
    for (let i = 0; i < indices.count; i += 1) largest = Math.max(largest, indices.componentType === 5123 ? data.getUint16(view.byteOffset + i * 2, true) : data.getUint32(view.byteOffset + i * 4, true))
    expect(largest).toBeLessThan(vertices)
  }
  // No liveries or logos: no textures, images or samplers at all.
  expect(json.textures).toBeUndefined()
  expect(json.images).toBeUndefined()
  expect(json.asset.copyright).toMatch(/original generic model, no trademarks/)
})

test('the rotors are separate nodes, placed at the hub and the tail fan, and the model is the size of the class', () => {
  const { json } = readGlb(buildHelicopterGlb())
  expect(json.nodes.map((n: { name: string }) => n.name)).toEqual(['helicopter', 'main_rotor', 'tail_rotor'])
  expect(json.nodes[0].children).toEqual([1, 2])
  expect(json.nodes[1].translation).toEqual([0, 0, 1.55])
  expect(json.nodes[2].translation[0]).toBeLessThan(-6)
  // Overall extent from the POSITION bounds: the main rotor's diameter about 10.2 m, the body about 10 m long.
  const bounds = (mesh: number) => json.meshes[mesh].primitives.map((p: { attributes: { POSITION: number } }) => json.accessors[p.attributes.POSITION])
  const rotor = bounds(1).reduce((r: number, a: { max: number[] }) => Math.max(r, a.max[0], a.max[1]), 0)
  expect(rotor).toBeCloseTo(MAIN_ROTOR_RADIUS, 1)
  const body = bounds(0)
  const length = Math.max(...body.map((a: { max: number[] }) => a.max[0])) - Math.min(...body.map((a: { min: number[] }) => a.min[0]))
  expect(length).toBeGreaterThan(9.5)
  expect(length).toBeLessThan(11)
})

test('the rotor speeds are the class values: about 395 rpm, the tail fan about nine times faster', () => {
  expect(MAIN_ROTOR_RAD_S).toBeCloseTo(41.36, 2)
  expect(TAIL_TO_MAIN).toBeCloseTo(3580 / 395, 6)
})

// Cesium's decoded-file promise and GPU readiness are separate public lifecycle boundaries (#1443).
// The stand-in deliberately throws on early node access, independently of the adapter implementation.
function pendingAircraft() {
  const main = { originalMatrix: Matrix4.IDENTITY, matrix: Matrix4.IDENTITY }
  const tail = { originalMatrix: Matrix4.IDENTITY, matrix: Matrix4.IDENTITY }
  const model = {
    ready: false, readyEvent: new Event(), errorEvent: new Event(), show: false,
    modelMatrix: Matrix4.IDENTITY, destroyed: false,
    getNode(name: string) {
      if (!this.ready) throw new Error('The model is not loaded.')
      return name === 'main_rotor' ? main : tail
    },
    destroy() { this.destroyed = true },
  }
  let decode!: (value: typeof model) => void
  let added = 0, removed = 0, renders = 0
  const Cesium = { Axis, Matrix3, Matrix4, Model: { fromGltfAsync: () => new Promise<typeof model>(resolve => { decode = resolve }) } } as unknown as CesiumModule
  const aircraft = createAircraftModel(Cesium, {
    primitives: {
      add<T>(value: T): T { added += 1; return value },
      remove() { removed += 1; model.destroy(); return true },
    },
    requestRender: () => { renders += 1 },
  }, '/helicopter.glb')
  const decoded = async () => { decode(model); await Promise.resolve(); await Promise.resolve() }
  const makeReady = () => { model.ready = true; model.readyEvent.raiseEvent(model) }
  return { aircraft, model, main, tail, decoded, makeReady, counts: () => ({ added, removed, renders }) }
}

test('a decoded helicopter keeps its fallback and accepts Chase placement until Cesium is render-ready', async () => {
  const state = pendingAircraft()
  await state.decoded()
  expect(state.counts().added).toBe(1) // Adding it is necessary for GPU initialization to run.
  expect(state.aircraft.loaded).toBe(false)
  let settled = false
  void state.aircraft.ready.then(() => { settled = true })
  const placement = Matrix4.fromTranslation(new Cartesian3(1, 2, 3))
  expect(() => state.aircraft.update(placement, 0.5, true)).not.toThrow()
  expect(state.model.show).toBe(true)
  expect(state.model.modelMatrix).toBe(placement)
  await Promise.resolve()
  expect(settled).toBe(false)
  state.makeReady()
  await expect(state.aircraft.ready).resolves.toEqual({ loaded: true })
  expect(state.aircraft.loaded).toBe(true)
  state.aircraft.update(placement, 0.5, true)
  expect(state.main.matrix).not.toBe(Matrix4.IDENTITY)
  expect(state.tail.matrix).not.toBe(Matrix4.IDENTITY)
  expect(state.counts().renders).toBeGreaterThanOrEqual(2)
  state.aircraft.destroy()
})

for (const phase of ['before decoding', 'before GPU readiness'] as const) {
  test(`disposing the helicopter ${phase} settles readiness and releases late resources`, async () => {
    const state = pendingAircraft()
    if (phase === 'before GPU readiness') await state.decoded()
    state.aircraft.destroy()
    if (phase === 'before decoding') await state.decoded()
    await expect(state.aircraft.ready).resolves.toMatchObject({ failed: expect.any(String) })
    expect(state.model.destroyed).toBe(true)
    expect(state.aircraft.loaded).toBe(false)
    expect(state.model.readyEvent.numberOfListeners).toBe(0)
    expect(state.model.errorEvent.numberOfListeners).toBe(0)
    expect(state.counts().added).toBe(phase === 'before decoding' ? 0 : 1)
    expect(() => state.aircraft.update(Matrix4.IDENTITY, 1, true)).not.toThrow()
  })
}
