import{expect,test}from'@playwright/test'
import{apiBase,apiLogin,login,showcaseSeed}from'./auth'

test('primary navigation separates generated data, managed documents, code and problem reporting without breaking historical routes',async({page,request})=>{
  test.setTimeout(90_000)
  const showcase=await showcaseSeed(request)
  await login(page)
  const nav=page.getByRole('navigation',{name:'Primary navigation'})
  const engineering=nav.locator('.navGroup').filter({has:page.locator('summary').filter({hasText:'REQUIREMENTS'})})
  const verification=nav.locator('.navGroup').filter({has:page.locator('summary').filter({hasText:'VERIFICATION'})})
  // #880 §4.3 moved the Digital Thread to RELEASE, beside the release and configuration views whose question
  // it answers. What this test guards is that exactly one group offers it, which is asserted below.
  const release=nav.locator('.navGroup').filter({has:page.locator('summary').filter({hasText:'RELEASE'})})
  await expect(engineering).toBeVisible()
  await expect(verification).toBeVisible()
  await expect(nav.locator('summary').filter({hasText:'ASSURANCE'})).toHaveCount(0)
  await engineering.locator('summary').click()
  await expect(engineering.getByRole('group',{name:'Requirements scope'})).toBeVisible()
  await verification.locator('summary').click()
  await expect(verification.getByRole('group',{name:'Verification scope'})).toBeVisible()
  await expect(nav.getByRole('link',{name:'System Verification',exact:true})).toHaveCount(0)
  await release.locator('summary').click()
  await expect(release.getByRole('link',{name:'Digital Thread'})).toBeVisible()
  await expect(engineering.getByRole('link',{name:'Digital Thread'})).toHaveCount(0)
  await expect(verification.getByRole('link',{name:'Digital Thread'})).toHaveCount(0)
  const reports=nav.locator('.navStandalone').getByRole('link',{name:'Problem Reports'})
  const code=nav.locator('.navStandalone').getByRole('link',{name:'Code traceability'})
  const documentation=nav.locator('.navStandalone').getByRole('link',{name:'Documentation Center'})
  await expect(code).toBeVisible()
  await expect(documentation).toBeVisible()
  await expect(reports).toBeVisible()
  await expect(nav.locator('.navStandalone details')).toHaveCount(0)
  const standaloneNames=await nav.locator('.navStandalone a').evaluateAll(items=>items.map(item=>item.getAttribute('aria-label')))
  expect(standaloneNames).toEqual(['Code traceability','Documentation Center','Problem Reports'])

  await expect(verification.getByRole('link',{name:'System Test Change Requests'})).toBeVisible()
  await expect(verification.getByRole('link',{name:'System Downstream Assessments'})).toHaveCount(0)
  await expect(verification.getByRole('link',{name:'System Test Procedure Explorer'})).toBeVisible()
  await expect(verification.getByRole('link',{name:'System Test Results'})).toBeVisible()
  await expect(verification.getByRole('link',{name:'Generated System Verification Documents'})).toBeVisible()
  await verification.getByRole('group',{name:'Verification scope'}).getByRole('button',{name:'Software'}).click()
  for(const name of['Software Test Change Requests','Test Case/Procedure Explorer','Software HLR Test Results','Software LLR Test Results','Generated Software Verification Documents'])await expect(verification.getByRole('link',{name})).toBeVisible()
  await expect(verification.getByRole('link',{name:/Downstream Assessments/})).toHaveCount(0)

  await reports.click()
  await expect(page.getByRole('heading',{name:'Problem Reports',exact:true})).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading',{name:'Problem Reports',exact:true})).toBeVisible()
  await release.locator('summary').click()
  await release.getByRole('link',{name:'Digital Thread'}).click()
  // §4.2 reclaimed the header: the canvas is the page, so arrival is asserted by the canvas rather than by
  // an H1 that no longer exists.
  await expect(page.locator('.dtPage .dtnRoot')).toBeVisible()
  await expect(page.getByRole('heading',{name:'Digital Thread'})).toHaveCount(0)
  await page.reload()
  await expect(page.locator('.dtPage .dtnRoot')).toBeVisible()

  // Compatibility roots remain valid even though the redundant generic entry is gone.
  await page.goto(`/programs/${showcase.programId}/projects/${showcase.projectId}/releases/${showcase.activeReleaseId}/system-verification`)
  await expect(page.getByRole('heading',{name:'Verification'})).toBeVisible()

  await apiLogin(request)
  const workspaces=await (await request.get(`${apiBase}/api/workspaces`)).json()
  const project=workspaces.flatMap((workspace:{projects:{project:{id:string};releases:{id:string;isReleased:boolean}[]}[]})=>workspace.projects).find((item:{project:{id:string}})=>item.project.id===showcase.projectId)
  expect(project,'The showcase Project workspace').toBeTruthy()
  const released=project!.releases.find((item:{isReleased:boolean})=>item.isReleased)
  expect(released,'A released Build 1.5 workspace').toBeTruthy()
  await page.goto(`/programs/${showcase.programId}/projects/${showcase.projectId}/releases/${released.id}/problem-reports`)
  await expect(page.getByText('Released · read-only').first()).toBeVisible()
  await expect(page.getByRole('heading',{name:'Problem Reports',exact:true})).toBeVisible()
  await expect(nav.locator('summary').filter({hasText:'VERIFICATION'})).toBeVisible()
})
