import { expect, test } from "@playwright/test"

test("compact cards preserve next actions, details, stages and exact links", async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto("/tests/fixtures/team-work.html")
  await expect(page.locator('.teamWorkLane')).toHaveCount(3)
  const work = page.locator('[data-lane="work"] .teamWorkCard').first()
  await expect(work).toContainText('Alex Engineer')
  await expect(work.locator('.teamWorkCardLink')).toContainText('Assigned Build')
  await expect(work.locator('.teamWorkCardLink')).not.toContainText('Native state')
  await expect(work.locator('.teamWorkLanePill')).toHaveCount(0)
  await expect(work.locator('a')).toHaveAttribute('href', '/open/change-request/00000000-0000-0000-0000-000000000001')
  await expect(page.locator('[data-lane="review"] .teamWorkCard')).toHaveCount(16)
  await expect(page.locator('[data-lane="review"]')).toContainText('Alex Engineer (Approval)')
  await expect(page.locator('[data-lane="approved"]')).toContainText('No outstanding action')
  await page.screenshot({ path: 'test-results/team-work-after.png', fullPage: true })
  await work.getByText('Details', { exact: true }).click()
  await expect(work.getByText('Native state', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Current holder', exact: true }).click()
  await expect(page.locator('.teamWorkLanePill').first()).toContainText('In Work')
  await page.getByRole('combobox', { name: 'Artifact Type' }).selectOption('SRCR')
  await expect(page.locator('.teamWorkCard')).toHaveCount(32)
  await page.setViewportSize({ width: 600, height: 900 })
  expect(await page.locator('.teamWorkFilters').evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
})
