using System.Text.Json;
using AeroLink.Domain.Common;
using AeroLink.Domain.Identity;
using AeroLink.Domain.Requirements;
using AeroLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Api;

public static class OperationsEndpoints
{
    public static IEndpointRouteBuilder MapAeroLinkOperationsEndpoints(this IEndpointRouteBuilder app)
    {
        var group=app.MapGroup("/api/operations");
        group.MapGet("/overview",OverviewAsync);
        group.MapPost("/qualification-runs",RecordQualificationAsync);
        group.MapPost("/restore-drills",RecordRestoreDrillAsync);
        group.MapPost("/retention-policies",RecordRetentionPolicyAsync);
        group.MapPost("/upgrade-evidence",RecordUpgradeEvidenceAsync);
        group.MapPost("/alerts",OpenAlertAsync);
        group.MapPost("/alerts/{id:guid}/resolve",ResolveAlertAsync);
        app.MapAeroLinkExternalIdentityAdminEndpoints();
        return app;
    }

    private static async Task<IResult> OverviewAsync(Guid projectId,HttpContext http,AeroLinkDbContext db,CancellationToken ct)
    {
        if(!await http.HasProjectAccessAsync(db,projectId,ct))return Results.Forbid();var checkpoint=(await db.EnterpriseIntegrityCheckpoints.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.CreatedAt).FirstOrDefault();var jobs=await db.EnterpriseOperationJobs.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);var attachments=await db.ControlledAttachments.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);
        var qualifications=(await db.WorkloadQualificationEvidence.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.ExecutedAt).ToList();var restoreDrills=(await db.BackupRestoreDrillEvidence.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.ExecutedAt).ToList();var retention=(await db.RetentionPolicyEvidence.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.ConfiguredAt).ToList();var upgrades=(await db.UpgradeAssuranceEvidence.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.ExecutedAt).ToList();var alerts=(await db.OperationalAlerts.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).OrderByDescending(x=>x.OpenedAt).Take(100).ToList();var productionQualification=qualifications.FirstOrDefault(x=>x.MeetsProductionTarget);
        return Results.Ok(new{generatedAt=DateTimeOffset.UtcNow,health=new{database=await db.Database.CanConnectAsync(ct)?"ready":"not_ready",integrity=checkpoint?.State.ToString()??"not_checked",latestManifest=checkpoint?.ManifestHash,checkpointAt=checkpoint?.CreatedAt,openAlerts=alerts.Count(x=>x.State!=OperationalAlertState.Resolved)},operations=new{runningJobs=jobs.Count(x=>x.State==EnterpriseJobState.Running),failedJobs=jobs.Count(x=>x.State==EnterpriseJobState.Failed),attachments=attachments.Count,attachmentBytes=attachments.Sum(x=>x.Size),unverifiedAttachments=attachments.Count(x=>x.IntegrityVerifiedAt is null)},qualification=new{scaleTargetRequirements=50_000,concurrentUserTarget=150,qualified=productionQualification is not null,evidence=productionQualification is null?null:new{productionQualification.Id,productionQualification.Environment,productionQualification.RequirementCount,productionQualification.ConcurrentUsers,productionQualification.DurationMinutes,productionQualification.ReportHash,productionQualification.ExecutedBy,productionQualification.ExecutedAt}},restoreAssurance=restoreDrills.Take(20).Select(x=>new{x.Id,state=x.State.ToString(),x.TargetRpoMinutes,x.ActualRpoMinutes,x.TargetRtoMinutes,x.ActualRtoMinutes,x.BackupLocation,x.BackupHash,x.EvidenceHash,x.ExecutedAt}),retentionPolicies=retention.GroupBy(x=>x.RecordType).Select(x=>x.First()).Select(x=>new{x.Id,x.RecordType,x.RetentionDays,x.LegalHold,x.Rationale,x.ConfiguredAt}),upgradeEvidence=upgrades.Take(20).Select(x=>new{x.Id,x.FromVersion,x.ToVersion,state=x.State.ToString(),x.EvidenceHash,x.ExecutedAt}),alerts=alerts.Select(x=>new{x.Id,x.Severity,x.Signal,x.Detail,x.RunbookUrl,state=x.State.ToString(),x.OpenedAt,x.ResolvedAt})});
    }

    private static async Task<IResult> RecordQualificationAsync(RecordQualificationRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{using var _=JsonDocument.Parse(request.ResultsJson);var item=new WorkloadQualificationEvidence(request.ProjectId,request.Environment,request.RequirementCount,request.ConcurrentUsers,request.DurationMinutes,request.ResultsJson,request.ReportHash,request.AllPassed,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.WorkloadQualificationEvidence.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/operations/qualification-runs/{item.Id}",new{item.Id,state=item.State.ToString(),item.MeetsProductionTarget,item.ReportHash});}catch(JsonException){return Results.BadRequest(new{error="Qualification results must be valid JSON."});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> RecordRestoreDrillAsync(RecordRestoreDrillRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{var item=new BackupRestoreDrillEvidence(request.ProjectId,request.BackupLocation,request.BackupHash,request.BackupCreatedAt,request.OffsiteVerifiedAt,request.TargetRpoMinutes,request.TargetRtoMinutes,request.ActualRpoMinutes,request.ActualRtoMinutes,request.RestoreEnvironment,request.EvidenceHash,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.BackupRestoreDrillEvidence.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/operations/restore-drills/{item.Id}",new{item.Id,state=item.State.ToString(),item.ActualRpoMinutes,item.ActualRtoMinutes,item.EvidenceHash});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> RecordRetentionPolicyAsync(RecordRetentionPolicyRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{var item=new RetentionPolicyEvidence(request.ProjectId,request.RecordType,request.RetentionDays,request.LegalHold,request.Rationale,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.RetentionPolicyEvidence.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/operations/retention-policies/{item.Id}",new{item.Id,item.RecordType,item.RetentionDays,item.LegalHold});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> RecordUpgradeEvidenceAsync(RecordUpgradeEvidenceRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{using var _=JsonDocument.Parse(request.PreflightJson);using var __=JsonDocument.Parse(request.PostCheckJson);var item=new UpgradeAssuranceEvidence(request.ProjectId,request.FromVersion,request.ToVersion,request.PreflightJson,request.PostCheckJson,request.EvidenceHash,request.Passed,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.UpgradeAssuranceEvidence.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/operations/upgrade-evidence/{item.Id}",new{item.Id,state=item.State.ToString(),item.EvidenceHash});}catch(JsonException){return Results.BadRequest(new{error="Upgrade preflight and post-check evidence must be valid JSON."});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> OpenAlertAsync(OpenOperationalAlertRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{var item=new OperationalAlert(request.ProjectId,request.Severity,request.Signal,request.Detail,request.RunbookUrl,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.OperationalAlerts.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/operations/alerts/{item.Id}",new{item.Id,state=item.State.ToString()});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> ResolveAlertAsync(Guid id,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var item=await db.OperationalAlerts.SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return Results.NotFound();if(!await Authorized(item.ProjectId,http,db,identity,ct))return Results.Forbid();try{item.Resolve(http.UserAccount().UserName,DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return Results.Ok(new{item.Id,state=item.State.ToString(),item.ResolvedAt});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static Task<bool> Authorized(Guid projectId,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)=>http.HasProjectRoleAsync(db,identity,projectId,ct,ProgramRole.ConfigurationManager,ProgramRole.ProgramManager,ProgramRole.Administrator);
}

public sealed record RecordQualificationRequest(Guid ProjectId,string Environment,int RequirementCount,int ConcurrentUsers,int DurationMinutes,string ResultsJson,string ReportHash,bool AllPassed);
public sealed record RecordRestoreDrillRequest(Guid ProjectId,string BackupLocation,string BackupHash,DateTimeOffset BackupCreatedAt,DateTimeOffset OffsiteVerifiedAt,int TargetRpoMinutes,int TargetRtoMinutes,int ActualRpoMinutes,int ActualRtoMinutes,string RestoreEnvironment,string EvidenceHash);
public sealed record RecordRetentionPolicyRequest(Guid ProjectId,string RecordType,int RetentionDays,bool LegalHold,string Rationale);
public sealed record RecordUpgradeEvidenceRequest(Guid ProjectId,string FromVersion,string ToVersion,string PreflightJson,string PostCheckJson,string EvidenceHash,bool Passed);
public sealed record OpenOperationalAlertRequest(Guid ProjectId,string Severity,string Signal,string Detail,string RunbookUrl);
