using System.Data;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using AeroLink.Domain.Common;
using AeroLink.Domain.Identity;
using AeroLink.Domain.Requirements;
using AeroLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Api;

public static class ProductLineCompletionEndpoints
{
    public static IEndpointRouteBuilder MapProductLineCompletionEndpoints(this IEndpointRouteBuilder app)
    {
        var group=app.MapGroup("/api/product-line");group.MapGet("/libraries",LibrariesAsync);group.MapPost("/libraries",CreateLibraryAsync);group.MapPost("/libraries/{id:guid}/revisions",PublishLibraryRevisionAsync);group.MapPost("/libraries/{id:guid}/approve",ApproveLibraryAsync);group.MapPost("/variants/{id:guid}/libraries",SelectLibraryAsync);group.MapPost("/variants/{variantId:guid}/libraries/{reuseId:guid}/decision",DecideLibraryAsync);group.MapGet("/configurations/{baselineId:guid}",ConfigurationAsync);
        var templates=app.MapGroup("/api/publication-templates");templates.MapGet("/",TemplatesAsync);templates.MapPost("/",CreateTemplateAsync);templates.MapPost("/{id:guid}/approve",ApproveTemplateAsync);templates.MapPost("/{id:guid}/begin-revision",BeginTemplateRevisionAsync);return app;
    }
    private static async Task<IResult> LibrariesAsync(Guid projectId,HttpContext http,AeroLinkDbContext db,CancellationToken ct)
    {if(!await http.HasProjectAccessAsync(db,projectId,ct))return Results.Forbid();var libraries=await db.ControlledLibraries.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.LibraryNumber).ToListAsync(ct);var ids=libraries.Select(x=>x.Id).ToList();var revisions=await db.ControlledLibraryRevisions.AsNoTracking().Where(x=>ids.Contains(x.LibraryId)).ToListAsync(ct);var decisions=(await db.LibraryPropagationDecisions.AsNoTracking().Where(x=>ids.Contains(x.LibraryId)).ToListAsync(ct)).OrderByDescending(x=>x.DecidedAt).ToList();var reuses=await(from reuse in db.VariantLibraryReuses.AsNoTracking() join variant in db.ProductVariants.AsNoTracking().Where(x=>x.ProjectId==projectId) on reuse.VariantId equals variant.Id select new{reuse,variant.VariantKey}).ToListAsync(ct);return Results.Ok(libraries.Select(x=>new{x.Id,x.LibraryNumber,x.Name,x.Description,state=x.State.ToString(),x.Version,revisions=revisions.Where(r=>r.LibraryId==x.Id).OrderByDescending(r=>r.Revision).Select(r=>new{r.Id,r.Revision,r.ManifestHash,r.ApprovedBy,r.ApprovedAt}),reuses=reuses.Where(r=>r.reuse.LibraryId==x.Id).Select(r=>new{r.reuse.Id,r.VariantKey,mode=r.reuse.Mode.ToString(),syncState=r.reuse.SynchronizationState.ToString(),r.reuse.SelectedRevisionId,r.reuse.LatestUpstreamRevisionId,r.reuse.DecisionRationale,r.reuse.DecidedBy,r.reuse.UpdatedAt}),decisionHistory=decisions.Where(d=>d.LibraryId==x.Id).Select(d=>new{d.Id,d.ReuseId,d.VariantId,d.PreviousRevisionId,d.UpstreamRevisionId,decision=d.Decision.ToString(),d.Rationale,d.DecidedBy,d.DecidedAt})}));}
    private static async Task<IResult> CreateLibraryAsync(CreateControlledLibraryRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await http.HasProjectRoleAsync(db,identity,request.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();try{var item=new ControlledLibrary(request.ProjectId,request.LibraryNumber,request.Name,request.Description??"",http.UserAccount().UserName,DateTimeOffset.UtcNow);db.ControlledLibraries.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/product-line/libraries/{item.Id}",new{item.Id,item.LibraryNumber});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}catch(DbUpdateException){return Results.Conflict(new{error="A controlled library with this number already exists."});}}
    private static async Task<IResult> PublishLibraryRevisionAsync(Guid id,PublishLibraryRevisionRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var library=await db.ControlledLibraries.SingleOrDefaultAsync(x=>x.Id==id,ct);if(library is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,library.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();await using var transaction=await db.Database.BeginTransactionAsync(IsolationLevel.Serializable,ct);try{var content=Canonical(request.ContentJson);var next=(await db.ControlledLibraryRevisions.Where(x=>x.LibraryId==id).MaxAsync(x=>(int?)x.Revision,ct)??0)+1;var now=DateTimeOffset.UtcNow;var revision=new ControlledLibraryRevision(id,next,content,Hash(content),http.UserAccount().UserName,now);db.ControlledLibraryRevisions.Add(revision);var reuses=await db.VariantLibraryReuses.Where(x=>x.LibraryId==id).ToListAsync(ct);foreach(var reuse in reuses)reuse.NotifyUpstream(revision.Id,now);await db.SaveChangesAsync(ct);await transaction.CommitAsync(ct);return Results.Created($"/api/product-line/libraries/{id}/revisions/{revision.Id}",new{revision.Id,revision.Revision,revision.ManifestHash,notifiedVariants=reuses.Count});}catch(JsonException){return Results.BadRequest(new{error="Controlled library content must be valid JSON."});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}catch(DbUpdateException){return Results.Conflict(new{error="A concurrent library revision was published. Refresh and retry.",code="library_revision_changed"});}}
    private static async Task<IResult> ApproveLibraryAsync(Guid id,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var item=await db.ControlledLibraries.SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,item.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();if(!await db.ControlledLibraryRevisions.AnyAsync(x=>x.LibraryId==id,ct))return Results.BadRequest(new{error="Publish at least one immutable revision before approving this library."});try{item.Approve(http.UserAccount().UserName,DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return Results.Ok(new{item.Id,state=item.State.ToString(),item.Version});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> SelectLibraryAsync(Guid id,SelectVariantLibraryRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var variant=await db.ProductVariants.SingleOrDefaultAsync(x=>x.Id==id,ct);if(variant is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,variant.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();if(variant.State!=ProductVariantState.Draft)return Results.Conflict(new{error="Library reuse is frozen when a variant is approved."});var revision=await(from r in db.ControlledLibraryRevisions join l in db.ControlledLibraries on r.LibraryId equals l.Id where r.Id==request.LibraryRevisionId select new{Revision=r,Library=l}).SingleOrDefaultAsync(ct);if(revision is null||revision.Library.ProjectId!=variant.ProjectId||revision.Library.State!=ControlledLibraryState.Approved)return Results.BadRequest(new{error="Only an approved library revision in this Project can be reused."});try{var applicability=Canonical(request.ApplicabilityJson??"{}");var reuse=new VariantLibraryReuse(id,revision.Library.Id,revision.Revision.Id,request.Mode,applicability,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.VariantLibraryReuses.Add(reuse);await db.SaveChangesAsync(ct);return Results.Created($"/api/product-line/variants/{id}/libraries/{reuse.Id}",new{reuse.Id,mode=reuse.Mode.ToString(),syncState=reuse.SynchronizationState.ToString()});}catch(JsonException){return Results.BadRequest(new{error="Reuse applicability must be valid JSON."});}catch(DbUpdateException){return Results.Conflict(new{error="This library is already reused by the variant."});}}
    private static async Task<IResult> DecideLibraryAsync(Guid variantId,Guid reuseId,LibraryPropagationDecisionRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var variant=await db.ProductVariants.SingleOrDefaultAsync(x=>x.Id==variantId,ct);var reuse=await db.VariantLibraryReuses.SingleOrDefaultAsync(x=>x.Id==reuseId&&x.VariantId==variantId,ct);if(variant is null||reuse is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,variant.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();try{var now=DateTimeOffset.UtcNow;var actor=http.UserAccount().UserName;var evidence=new LibraryPropagationDecision(reuse.Id,variant.Id,reuse.LibraryId,reuse.SelectedRevisionId,request.UpstreamRevisionId,request.Decision,request.Rationale,actor,now);reuse.Decide(request.Decision,request.UpstreamRevisionId,request.Rationale,actor,now);db.LibraryPropagationDecisions.Add(evidence);await db.SaveChangesAsync(ct);return Results.Ok(new{reuse.Id,decisionEvidenceId=evidence.Id,mode=reuse.Mode.ToString(),syncState=reuse.SynchronizationState.ToString(),reuse.SelectedRevisionId,reuse.LatestUpstreamRevisionId,reuse.Version});}catch(DomainException ex){return Results.Conflict(new{error=ex.Message});}catch(DbUpdateConcurrencyException){return Results.Conflict(new{error="The reuse decision changed. Refresh and retry.",code="reuse_decision_changed"});}}
    private static async Task<IResult> ConfigurationAsync(Guid baselineId,HttpContext http,AeroLinkDbContext db,VariantConfigurationProjectionService projector,CancellationToken ct)
    {var projectId=await(from baseline in db.ProductVariantBaselines where baseline.Id==baselineId join variant in db.ProductVariants on baseline.VariantId equals variant.Id select (Guid?)variant.ProjectId).SingleOrDefaultAsync(ct);if(projectId is null)return Results.NotFound();if(!await http.HasProjectAccessAsync(db,projectId.Value,ct))return Results.Forbid();var projection=await projector.ProjectAsync(baselineId,ct);return projection is null?Results.NotFound():Results.Ok(projection);}
    private static async Task<IResult> TemplatesAsync(Guid projectId,HttpContext http,AeroLinkDbContext db,CancellationToken ct)
    {if(!await http.HasProjectAccessAsync(db,projectId,ct))return Results.Forbid();var items=await db.DocumentTemplates.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.TemplateNumber).ToListAsync(ct);var ids=items.Select(x=>x.Id).ToList();var revisions=await db.DocumentTemplateRevisions.AsNoTracking().Where(x=>ids.Contains(x.TemplateId)).ToListAsync(ct);return Results.Ok(items.Select(x=>new{x.Id,x.TemplateNumber,x.Title,state=x.State.ToString(),x.ApprovedRevision,x.ApprovedBy,x.ApprovedAt,x.Version,revisions=revisions.Where(r=>r.TemplateId==x.Id).OrderByDescending(r=>r.Revision).Select(r=>new{r.Id,r.Revision,r.TemplateKind,r.Organization,r.ManifestHash,r.ApprovedBy,r.ApprovedAt})}));}
    private static async Task<IResult> CreateTemplateAsync(CreatePublicationTemplateRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await http.HasProjectRoleAsync(db,identity,request.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();try{Canonical(request.BodyJson);var item=new DocumentTemplate(request.ProjectId,request.TemplateNumber,request.Title,request.BodyJson,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.DocumentTemplates.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/publication-templates/{item.Id}",new{item.Id,item.TemplateNumber});}catch(JsonException){return Results.BadRequest(new{error="Template content must be valid JSON."});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> ApproveTemplateAsync(Guid id,ApprovePublicationTemplateRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var item=await db.DocumentTemplates.SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,item.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();try{var body=Canonical(item.Body);var revision=item.Approve(http.UserAccount().UserName,DateTimeOffset.UtcNow);var snapshot=Canonical(JsonSerializer.Serialize(new{item.TemplateNumber,item.Title,templateKind=request.TemplateKind,organization=request.Organization,body=JsonNode.Parse(body)}));var evidence=new DocumentTemplateRevision(item.Id,revision,request.TemplateKind,request.Organization,body,Hash(snapshot),http.UserAccount().UserName,DateTimeOffset.UtcNow);db.DocumentTemplateRevisions.Add(evidence);await db.SaveChangesAsync(ct);return Results.Ok(new{item.Id,state=item.State.ToString(),templateRevisionId=evidence.Id,evidence.Revision,evidence.ManifestHash});}catch(JsonException){return Results.BadRequest(new{error="Template content must be valid JSON."});}catch(DomainException ex){return Results.Conflict(new{error=ex.Message});}}
    private static async Task<IResult> BeginTemplateRevisionAsync(Guid id,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var item=await db.DocumentTemplates.SingleOrDefaultAsync(x=>x.Id==id,ct);if(item is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,item.ProjectId,ct,ProgramRole.ConfigurationManager))return Results.Forbid();try{item.BeginSuccessorRevision(http.UserAccount().UserName,DateTimeOffset.UtcNow);await db.SaveChangesAsync(ct);return Results.Ok(new{item.Id,state=item.State.ToString(),nextRevision=item.ApprovedRevision+1,item.Version});}catch(DomainException ex){return Results.Conflict(new{error=ex.Message});}}
    private static string Canonical(string json){var node=JsonNode.Parse(json)??throw new JsonException();return CanonicalNode(node).ToJsonString(new JsonSerializerOptions{WriteIndented=false});}
    private static JsonNode CanonicalNode(JsonNode node)=>node switch{JsonObject obj=>new JsonObject(obj.OrderBy(x=>x.Key,StringComparer.Ordinal).Select(x=>KeyValuePair.Create<string,JsonNode?>(x.Key,x.Value is null?null:CanonicalNode(x.Value)))),JsonArray array=>new JsonArray(array.Select(x=>x is null?null:CanonicalNode(x)).ToArray()),_=>node.DeepClone()};
    private static string Hash(string value)=>Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value))).ToLowerInvariant();
}
public sealed record CreateControlledLibraryRequest(Guid ProjectId,string LibraryNumber,string Name,string? Description);
public sealed record PublishLibraryRevisionRequest(string ContentJson);
public sealed record SelectVariantLibraryRequest(Guid LibraryRevisionId,VariantReuseMode Mode,string? ApplicabilityJson);
public sealed record LibraryPropagationDecisionRequest(Guid UpstreamRevisionId,PropagationDecisionKind Decision,string Rationale);
public sealed record CreatePublicationTemplateRequest(Guid ProjectId,string TemplateNumber,string Title,string BodyJson);
public sealed record ApprovePublicationTemplateRequest(string TemplateKind,string Organization);
