using System.Text.Json;
using AeroLink.Domain.Identity;
using AeroLink.Domain.Requirements;
using AeroLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Api;

public static class PublicationEndpoints
{
    public static IEndpointRouteBuilder MapAeroLinkPublicationEndpoints(this IEndpointRouteBuilder app)
    {
        app.MapPost("/api/publications/jobs",CreateJobAsync);
        app.MapPost("/api/publications/configuration-jobs",CreateConfigurationJobAsync);
        app.MapPost("/api/publications/release-packages",CreateReleasePackageAsync);
        app.MapGet("/api/publications/jobs/{id:guid}",GetJobAsync);
        app.MapGet("/api/publications/jobs/{id:guid}/verify",VerifyJobAsync);
        return app;
    }
    private static async Task<IResult> CreateConfigurationJobAsync(CreateConfigurationPublicationJobRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {var baseline=await db.ProductVariantBaselines.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==request.VariantBaselineId,ct);if(baseline is null)return Results.NotFound();var variant=await db.ProductVariants.AsNoTracking().SingleAsync(x=>x.Id==baseline.VariantId,ct);if(!await http.HasProjectRoleAsync(db,identity,variant.ProjectId,ct,ProgramRole.ConfigurationManager,ProgramRole.ProgramManager))return Results.Forbid();var template=await db.DocumentTemplateRevisions.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==request.TemplateRevisionId,ct);if(template is null||!await db.DocumentTemplates.AnyAsync(x=>x.Id==template.TemplateId&&x.ProjectId==variant.ProjectId,ct))return Results.BadRequest(new{error="The approved template revision is not in this Project."});if(request.PreviousVariantBaselineId is not null&&!await(from b in db.ProductVariantBaselines join v in db.ProductVariants on b.VariantId equals v.Id where b.Id==request.PreviousVariantBaselineId&&v.ProjectId==variant.ProjectId select b.Id).AnyAsync(ct))return Results.BadRequest(new{error="The redline predecessor configuration is not in this Project."});var format=request.Format.Trim().ToLowerInvariant();if(format is not("pdf" or "docx"))return Results.BadRequest(new{error="Configuration publications support PDF or DOCX."});var key=string.IsNullOrWhiteSpace(request.IdempotencyKey)?$"variant-publication:{baseline.Id:N}:{template.Id:N}:{request.PreviousVariantBaselineId}:{format}":request.IdempotencyKey.Trim();var existing=await db.EnterpriseOperationJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.ProjectId==variant.ProjectId&&x.IdempotencyKey==key,ct);if(existing is not null)return Results.Ok(Map(existing,true));var payload=JsonSerializer.Serialize(new ConfigurationPublicationJobPayload(baseline.Id,format,template.Id,request.PreviousVariantBaselineId));var job=new EnterpriseOperationJob(variant.ProjectId,"BackgroundVariantPublication",payload,1,http.UserAccount().UserName,DateTimeOffset.UtcNow,key);db.EnterpriseOperationJobs.Add(job);await db.SaveChangesAsync(ct);return Results.Accepted($"/api/publications/jobs/{job.Id}",Map(job,false));}
    private static async Task<IResult> CreateReleasePackageAsync(CreateReleaseEvidencePackageRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await http.HasProjectRoleAsync(db,identity,request.ProjectId,ct,ProgramRole.ConfigurationManager,ProgramRole.ProgramManager))return Results.Forbid();var ids=request.PublicationJobIds.Distinct().ToList();if(ids.Count==0)return Results.BadRequest(new{error="Select at least one completed controlled publication."});var valid=await db.EnterpriseOperationJobs.AsNoTracking().CountAsync(x=>ids.Contains(x.Id)&&x.ProjectId==request.ProjectId&&x.State==EnterpriseJobState.Completed&&x.JobType.Contains("Publication"),ct);if(valid!=ids.Count)return Results.BadRequest(new{error="Every package member must be a completed publication in this Project."});var key=string.IsNullOrWhiteSpace(request.IdempotencyKey)?$"release-evidence-package:{request.ProjectId:N}:{string.Join(':',ids.Order())}":request.IdempotencyKey.Trim();var existing=await db.EnterpriseOperationJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.ProjectId==request.ProjectId&&x.IdempotencyKey==key,ct);if(existing is not null)return Results.Ok(Map(existing,true));var job=new EnterpriseOperationJob(request.ProjectId,"BackgroundReleaseEvidencePackage",JsonSerializer.Serialize(new ReleaseEvidencePackageJobPayload(ids)),ids.Count,http.UserAccount().UserName,DateTimeOffset.UtcNow,key);db.EnterpriseOperationJobs.Add(job);await db.SaveChangesAsync(ct);return Results.Accepted($"/api/publications/jobs/{job.Id}",Map(job,false));}

    private static async Task<IResult> CreateJobAsync(CreatePublicationJobRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {
        var document=await db.ControlledDocuments.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==request.DocumentId,ct);if(document is null)return Results.NotFound();if(!await http.HasProjectRoleAsync(db,identity,document.ProjectId,ct,ProgramRole.Engineer,ProgramRole.ConfigurationManager,ProgramRole.ProgramManager))return Results.Forbid();var format=request.Format.Trim().ToLowerInvariant();if(format is not ("pdf" or "docx"))return Results.BadRequest(new{error="Controlled publications support PDF or DOCX."});if(request.PreviousDocumentId is not null&&!await db.ControlledDocuments.AnyAsync(x=>x.Id==request.PreviousDocumentId&&x.ProjectId==document.ProjectId,ct))return Results.BadRequest(new{error="The redline predecessor is not in this Project."});if(request.TemplateId is not null&&!await db.DocumentTemplates.AnyAsync(x=>x.Id==request.TemplateId&&x.ProjectId==document.ProjectId&&x.State==DocumentTemplateState.Approved,ct))return Results.BadRequest(new{error="Only an approved Project template can govern a publication."});var key=string.IsNullOrWhiteSpace(request.IdempotencyKey)?$"publication:{request.DocumentId:N}:{format}:{request.PreviousDocumentId}:{request.TemplateId}":request.IdempotencyKey.Trim();var existing=await db.EnterpriseOperationJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.ProjectId==document.ProjectId&&x.IdempotencyKey==key,ct);if(existing is not null)return Results.Ok(Map(existing,true));var payload=JsonSerializer.Serialize(new PublicationJobPayload(request.DocumentId,format,request.PreviousDocumentId,request.TemplateId));var job=new EnterpriseOperationJob(document.ProjectId,"BackgroundControlledPublication",payload,1,http.UserAccount().UserName,DateTimeOffset.UtcNow,key);db.EnterpriseOperationJobs.Add(job);await db.SaveChangesAsync(ct);return Results.Accepted($"/api/publications/jobs/{job.Id}",Map(job,false));
    }
    private static async Task<IResult> GetJobAsync(Guid id,HttpContext http,AeroLinkDbContext db,CancellationToken ct)
    {var job=await db.EnterpriseOperationJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id&&x.JobType.StartsWith("Background")&&(x.JobType.Contains("Publication")||x.JobType.Contains("EvidencePackage")),ct);if(job is null)return Results.NotFound();if(!await http.HasProjectAccessAsync(db,job.ProjectId,ct))return Results.Forbid();return Results.Ok(Map(job,false));}
    private static async Task<IResult> VerifyJobAsync(Guid id,HttpContext http,AeroLinkDbContext db,EvidenceFileStore store,CancellationToken ct)
    {var job=await db.EnterpriseOperationJobs.AsNoTracking().SingleOrDefaultAsync(x=>x.Id==id,ct);if(job is null)return Results.NotFound();if(!await http.HasProjectAccessAsync(db,job.ProjectId,ct))return Results.Forbid();if(job.State!=EnterpriseJobState.Completed)return Results.BadRequest(new{error="The publication is not complete."});using var result=JsonDocument.Parse(job.ResultJson);var root=result.RootElement;if(!Try(root,"StorageKey",out var storage)||!Try(root,"Sha256",out var expected))return Results.BadRequest(new{error="The publication result has no integrity evidence."});var actual=await store.ComputeSha256Async(storage!,ct);return Results.Ok(new{valid=string.Equals(actual,expected,StringComparison.OrdinalIgnoreCase),expected,actual,verifiedAt=DateTimeOffset.UtcNow,sourceManifestHash=Value(root,"SourceManifestHash"),templateManifestHash=Value(root,"TemplateManifestHash")});}
    private static bool Try(JsonElement root,string name,out string? value){if(root.TryGetProperty(name,out var p)||root.TryGetProperty(char.ToLowerInvariant(name[0])+name[1..],out p)){value=p.GetString();return !string.IsNullOrWhiteSpace(value);}value=null;return false;}
    private static string? Value(JsonElement root,string name)=>Try(root,name,out var value)?value:null;
    private static object Map(EnterpriseOperationJob job,bool reused)=>new{job.Id,state=job.State.ToString(),job.ProgressPercent,job.Attempt,job.LastError,job.ResultJson,job.CreatedAt,job.UpdatedAt,job.CompletedAt,reused,downloadUrl=job.State==EnterpriseJobState.Completed?$"/api/enterprise-hardening/jobs/{job.Id}/download":null};
}

public sealed record CreatePublicationJobRequest(Guid DocumentId,string Format,Guid? PreviousDocumentId,Guid? TemplateId,string? IdempotencyKey);
public sealed record CreateConfigurationPublicationJobRequest(Guid VariantBaselineId,string Format,Guid TemplateRevisionId,Guid? PreviousVariantBaselineId,string? IdempotencyKey);
public sealed record CreateReleaseEvidencePackageRequest(Guid ProjectId,IReadOnlyList<Guid> PublicationJobIds,string? IdempotencyKey);
