using System.Text;
using System.Text.Json;
using AeroLink.Domain.Common;
using AeroLink.Domain.Identity;
using AeroLink.Domain.Requirements;
using AeroLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace AeroLink.Api;

public static class QualityIntelligenceEndpoints
{
    public static IEndpointRouteBuilder MapAeroLinkQualityIntelligenceEndpoints(this IEndpointRouteBuilder app)
    {
        var group=app.MapGroup("/api/quality");group.MapGet("/portfolio",PortfolioAsync);group.MapPost("/objectives",CreateObjectiveAsync);group.MapPost("/waivers",CreateWaiverAsync);group.MapPost("/evidence-index",IndexEvidenceAsync);group.MapPost("/exports",ExportAsync);return app;
    }
    private static async Task<IResult> PortfolioAsync(Guid projectId,HttpContext http,AeroLinkDbContext db,CancellationToken ct)
    {if(!await http.HasProjectAccessAsync(db,projectId,ct))return Results.Forbid();var now=DateTimeOffset.UtcNow;var releases=await db.Releases.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);var scrs=await db.SystemChangeRequests.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);var prs=await db.ProblemReports.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);var docs=await db.ControlledDocuments.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct);var objectives=await db.QualityLifecycleObjectives.AsNoTracking().Where(x=>x.ProjectId==projectId&&x.IsActive).OrderBy(x=>x.Code).ToListAsync(ct);var waivers=(await db.ReadinessWaivers.AsNoTracking().Where(x=>x.ProjectId==projectId).ToListAsync(ct)).Where(x=>x.IsActive(now)).OrderBy(x=>x.ExpiresAt).ToList();var evidence=await db.CertificationEvidenceIndex.AsNoTracking().Where(x=>x.ProjectId==projectId).OrderBy(x=>x.ObjectiveCode).ToListAsync(ct);return Results.Ok(new{generatedAt=now,claimBoundary="Lifecycle evidence is indexed for review; AeroLink does not make certification claims.",summary=new{releases=releases.Count,controlledChanges=scrs.Count,openProblemReports=prs.Count(x=>x.State!=ProblemReportState.Closed),controlledDocuments=docs.Count,objectives=objectives.Count,activeWaivers=waivers.Count,indexedEvidence=evidence.Count},trends=releases.OrderBy(x=>x.Version).Select(release=>new{release.Id,release.Version,release.IsReleased,changes=scrs.Count(x=>x.TargetReleaseId==release.Id),publications=docs.Count(x=>x.ReleaseId==release.Id)}),objectives=objectives.Select(x=>new{x.Id,x.Code,x.Title,x.TargetJson,x.EvidenceExpectation,evidenceCount=evidence.Count(e=>e.ObjectiveCode==x.Code)}),waivers=waivers.Select(x=>new{x.Id,x.BlockerType,x.BlockerId,x.Rationale,x.ApprovedBy,x.ExpiresAt}),evidence=evidence.Select(x=>new{x.Id,x.ObjectiveCode,x.ArtifactType,x.ArtifactId,x.EvidenceHash,x.ClaimBoundary,x.IndexedBy,x.IndexedAt})});}
    private static async Task<IResult> CreateObjectiveAsync(CreateQualityObjectiveRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{using var _=JsonDocument.Parse(request.TargetJson);var item=new QualityLifecycleObjective(request.ProjectId,request.Code,request.Title,request.TargetJson,request.EvidenceExpectation,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.QualityLifecycleObjectives.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/quality/objectives/{item.Id}",new{item.Id,item.Code});}catch(JsonException){return Results.BadRequest(new{error="Objective targets must be valid JSON."});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}catch(DbUpdateException){return Results.Conflict(new{error="An objective with this code already exists."});}}
    private static async Task<IResult> CreateWaiverAsync(CreateReadinessWaiverRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{var item=new ReadinessWaiver(request.ProjectId,request.BlockerType,request.BlockerId,request.Rationale,request.ApprovedBy,request.ExpiresAt,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.ReadinessWaivers.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/quality/waivers/{item.Id}",new{item.Id,item.ExpiresAt});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}}
    private static async Task<IResult> IndexEvidenceAsync(IndexCertificationEvidenceRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();try{var item=new CertificationEvidenceIndexEntry(request.ProjectId,request.ObjectiveCode,request.ArtifactType,request.ArtifactId,request.EvidenceHash,request.ClaimBoundary,http.UserAccount().UserName,DateTimeOffset.UtcNow);db.CertificationEvidenceIndex.Add(item);await db.SaveChangesAsync(ct);return Results.Created($"/api/quality/evidence-index/{item.Id}",new{item.Id,item.EvidenceHash});}catch(DomainException ex){return Results.BadRequest(new{error=ex.Message});}catch(DbUpdateException){return Results.Conflict(new{error="This evidence is already indexed for the objective."});}}
    private static async Task<IResult> ExportAsync(CreateQualityExportRequest request,HttpContext http,AeroLinkDbContext db,IdentityService identity,EvidenceFileStore store,CancellationToken ct)
    {if(!await Authorized(request.ProjectId,http,db,identity,ct))return Results.Forbid();var portfolioResult=await PortfolioAsync(request.ProjectId,http,db,ct);if(portfolioResult is not IValueHttpResult value||value.Value is null)return portfolioResult;var json=JsonSerializer.Serialize(value.Value,new JsonSerializerOptions{WriteIndented=true});await using var content=new MemoryStream(Encoding.UTF8.GetBytes(json));var stored=await store.StoreAsync(content,$"aerolink-quality-portfolio-{DateTime.UtcNow:yyyyMMddHHmmss}.json","application/json",ct);var job=new EnterpriseOperationJob(request.ProjectId,"ControlledQualityPortfolioExport",JsonSerializer.Serialize(new{request.ProjectId}),1,http.UserAccount().UserName,DateTimeOffset.UtcNow,request.IdempotencyKey??$"quality-export:{request.ProjectId:N}:{stored.Sha256}");job.Start(DateTimeOffset.UtcNow);job.Complete(1,0,JsonSerializer.Serialize(new{stored.StorageKey,stored.OriginalFileName,stored.ContentType,stored.Size,stored.Sha256,claimBoundary="Evidence index only; no certification claim."}),DateTimeOffset.UtcNow);db.EnterpriseOperationJobs.Add(job);await db.SaveChangesAsync(ct);return Results.Created($"/api/enterprise-hardening/jobs/{job.Id}",new{job.Id,stored.Sha256,downloadUrl=$"/api/enterprise-hardening/jobs/{job.Id}/download"});}
    private static Task<bool> Authorized(Guid projectId,HttpContext http,AeroLinkDbContext db,IdentityService identity,CancellationToken ct)=>http.HasProjectRoleAsync(db,identity,projectId,ct,ProgramRole.ConfigurationManager,ProgramRole.ProgramManager,ProgramRole.Administrator);
}
public sealed record CreateQualityObjectiveRequest(Guid ProjectId,string Code,string Title,string TargetJson,string EvidenceExpectation);
public sealed record CreateReadinessWaiverRequest(Guid ProjectId,string BlockerType,Guid BlockerId,string Rationale,string ApprovedBy,DateTimeOffset ExpiresAt);
public sealed record IndexCertificationEvidenceRequest(Guid ProjectId,string ObjectiveCode,string ArtifactType,Guid ArtifactId,string EvidenceHash,string ClaimBoundary);
public sealed record CreateQualityExportRequest(Guid ProjectId,string? IdempotencyKey);
