<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>AeroLink.DocumentConnector</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\AeroLink.ConnectorProtocol\AeroLink.ConnectorProtocol.csproj" />
    <ProjectReference Include="..\..\src\AeroLink.DocumentSecurity\AeroLink.DocumentSecurity.csproj" />
  </ItemGroup>
</Project>
