using System.Text.Json;
using AeroLink.Infrastructure.Persistence;

namespace AeroLink.Api.Tests;

/// <summary>
/// #913: the FMS showcase promises 100% portrait coverage for its active project members, which only
/// holds while the client portrait manifest covers every account the identity seeder can create. The
/// manifest (product/client/src/people-manifest.json, generated by
/// product/client/scripts/generate-people-portraits.mjs) must therefore contain every username in the
/// IdentityService directory — curated accounts, generated accounts, and the administrator — or a new
/// seeded account would silently fall back to initials on every person surface.
/// </summary>
public class PeoplePortraitManifestTests
{
    private static readonly string RepoRoot = FindRepoRoot(AppContext.BaseDirectory);
    private static readonly string ManifestPath = Path.Combine(RepoRoot, "product", "client", "src", "people-manifest.json");

    [Fact]
    public void Portrait_manifest_covers_every_seeded_identity_service_account()
    {
        var manifest = JsonSerializer.Deserialize<JsonElement>(File.ReadAllText(ManifestPath));
        var portraits = manifest.GetProperty("people");
        var covered = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var entry in portraits.EnumerateObject())
            covered.Add(entry.Name);

        // The system administrator is a real identity, not a synthetic cast member: audit surfaces
        // render its raw account and person surfaces use the initials fallback for it.
        foreach (var account in IdentitySeeder.SeedDirectoryUserNames().Where(x => x != IdentityService.SystemAdministratorUserName))
            Assert.True(covered.Contains(account),
                $"Seeded account '{account}' has no portrait in people-manifest.json. Run product/client/scripts/generate-people-portraits.mjs and commit the generated portrait.");
    }

    [Fact]
    public void Manifest_entries_carry_a_file_and_a_display_name()
    {
        var manifest = JsonSerializer.Deserialize<JsonElement>(File.ReadAllText(ManifestPath));
        foreach (var entry in manifest.GetProperty("people").EnumerateObject())
        {
            var file = entry.Value.GetProperty("file").GetString();
            var name = entry.Value.GetProperty("name").GetString();
            Assert.False(string.IsNullOrWhiteSpace(file), $"{entry.Name}: manifest entry has no portrait file.");
            Assert.True(file!.StartsWith("/people/"), $"{entry.Name}: portrait file must be served from /people/.");
            Assert.False(string.IsNullOrWhiteSpace(name), $"{entry.Name}: manifest entry has no display name.");
        }
    }

    private static string FindRepoRoot(string start)
    {
        var current = start;
        for (var i = 0; i < 10; i++)
        {
            if (Directory.Exists(Path.Combine(current, "product", "client", "src"))) return current;
            current = Path.GetDirectoryName(current)!;
        }
        throw new InvalidOperationException($"Repository root not found above {start}");
    }
}
