// <auto-generated />
using System;
using AeroLink.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AeroLink.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AeroLinkDbContext))]
    [Migration("20260712150808_BackfillLifecycleClassification")]
    partial class BackfillLifecycleClassification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AeroLink.Domain.Baselines.BaselineEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId", "OccurredAt");

                    b.ToTable("baseline_events", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Baselines.BaselineScrSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScrDisplayNumber")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ScrId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId", "ScrId")
                        .IsUnique();

                    b.ToTable("baseline_scr_selections", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Baselines.CandidateBaseline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FrozenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("PredecessorBaselineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequirementsHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("RequirementsMaterializedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BaseNumber", "Revision")
                        .IsUnique();

                    b.HasIndex("ProjectId", "ReleaseId", "State");

                    b.ToTable("candidate_baselines", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.ApprovalStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApproverId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReviewCycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewCycleId", "Position")
                        .IsUnique();

                    b.ToTable("approval_steps", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.RequirementChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScrId")
                        .HasColumnType("uuid");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("BaseNumber");

                    b.HasIndex("ScrId", "BaseNumber", "Revision")
                        .IsUnique();

                    b.ToTable("requirement_changes", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.ReviewCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScrId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ScrId", "Sequence")
                        .IsUnique();

                    b.ToTable("review_cycles", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.SystemChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Analysis")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("TargetReleaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "State");

                    b.HasIndex("ProjectId", "UpdatedAt");

                    b.HasIndex("ProjectId", "BaseNumber", "Revision")
                        .IsUnique();

                    b.ToTable("system_change_requests", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Common.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "OccurredAt");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Programs.ProgramRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("programs", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Programs.ProjectRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProgramId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoftwareProduct")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId", "Name")
                        .IsUnique();

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Programs.SoftwareBuild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuildNumber")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ReleasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("BaselineId");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("ProjectId", "BuildNumber")
                        .IsUnique();

                    b.HasIndex("ProjectId", "ReleaseId", "RecordedAt");

                    b.ToTable("software_builds", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Programs.SoftwareRelease", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Version")
                        .IsUnique();

                    b.ToTable("software_releases", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.BaselineRequirementSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId");

                    b.HasIndex("RevisionId");

                    b.HasIndex("BaselineId", "ArtifactId")
                        .IsUnique();

                    b.HasIndex("BaselineId", "RevisionId")
                        .IsUnique();

                    b.ToTable("baseline_requirement_selections", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.RequirementArtifact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BaseNumber")
                        .IsUnique();

                    b.ToTable("requirements", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.RequirementRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArtifactId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EffectiveBaselineId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceScrId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("VerificationMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveBaselineId");

                    b.HasIndex("SourceScrId");

                    b.HasIndex("ArtifactId", "Revision")
                        .IsUnique();

                    b.ToTable("requirement_revisions", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Traceability.ControlledDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArtifactCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("BaselineId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("BaselineId", "Type");

                    b.HasIndex("ProjectId", "DocumentNumber", "Revision")
                        .IsUnique();

                    b.ToTable("controlled_documents", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Traceability.RequirementTraceLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SourceRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TargetRevisionId");

                    b.HasIndex("SourceRevisionId", "TargetRevisionId", "Type")
                        .IsUnique();

                    b.ToTable("requirement_trace_links", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Determination")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("EvidenceReference")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExecutedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("ProcedureRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RetestOfExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SoftwareBuildId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureRevisionId");

                    b.HasIndex("RetestOfExecutionId");

                    b.HasIndex("SoftwareBuildId");

                    b.HasIndex("ProjectId", "ExecutedAt");

                    b.ToTable("test_executions", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "BaseNumber")
                        .IsUnique();

                    b.ToTable("test_procedures", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestProcedureRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Preconditions")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<Guid>("ProcedureId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("character varying(16000)");

                    b.HasKey("Id");

                    b.HasIndex("ProcedureId", "Revision")
                        .IsUnique();

                    b.ToTable("test_procedure_revisions", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestRequirementCoverage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProcedureRevisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequirementRevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequirementRevisionId");

                    b.HasIndex("ProcedureRevisionId", "RequirementRevisionId")
                        .IsUnique();

                    b.ToTable("test_requirement_coverage", (string)null);
                });

            modelBuilder.Entity("AeroLink.Domain.Baselines.BaselineEvent", b =>
                {
                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany("Events")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Baselines.BaselineScrSelection", b =>
                {
                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany("Selections")
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.ApprovalStep", b =>
                {
                    b.HasOne("AeroLink.Domain.ChangeControl.ReviewCycle", null)
                        .WithMany("Steps")
                        .HasForeignKey("ReviewCycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.RequirementChange", b =>
                {
                    b.HasOne("AeroLink.Domain.ChangeControl.SystemChangeRequest", null)
                        .WithMany("RequirementChanges")
                        .HasForeignKey("ScrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.ReviewCycle", b =>
                {
                    b.HasOne("AeroLink.Domain.ChangeControl.SystemChangeRequest", null)
                        .WithMany("ReviewCycles")
                        .HasForeignKey("ScrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Common.AuditEvent", b =>
                {
                    b.HasOne("AeroLink.Domain.ChangeControl.SystemChangeRequest", null)
                        .WithMany("AuditEvents")
                        .HasForeignKey("AggregateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Programs.SoftwareBuild", b =>
                {
                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany()
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Programs.SoftwareRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.BaselineRequirementSelection", b =>
                {
                    b.HasOne("AeroLink.Domain.Requirements.RequirementArtifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany()
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Requirements.RequirementRevision", null)
                        .WithMany()
                        .HasForeignKey("RevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.RequirementArtifact", b =>
                {
                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Requirements.RequirementRevision", b =>
                {
                    b.HasOne("AeroLink.Domain.Requirements.RequirementArtifact", null)
                        .WithMany()
                        .HasForeignKey("ArtifactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany()
                        .HasForeignKey("EffectiveBaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.ChangeControl.SystemChangeRequest", null)
                        .WithMany()
                        .HasForeignKey("SourceScrId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Traceability.ControlledDocument", b =>
                {
                    b.HasOne("AeroLink.Domain.Baselines.CandidateBaseline", null)
                        .WithMany()
                        .HasForeignKey("BaselineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Programs.SoftwareRelease", null)
                        .WithMany()
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Traceability.RequirementTraceLink", b =>
                {
                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Requirements.RequirementRevision", null)
                        .WithMany()
                        .HasForeignKey("SourceRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Requirements.RequirementRevision", null)
                        .WithMany()
                        .HasForeignKey("TargetRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestExecution", b =>
                {
                    b.HasOne("AeroLink.Domain.Verification.TestProcedureRevision", null)
                        .WithMany()
                        .HasForeignKey("ProcedureRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Verification.TestExecution", null)
                        .WithMany()
                        .HasForeignKey("RetestOfExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AeroLink.Domain.Programs.SoftwareBuild", null)
                        .WithMany()
                        .HasForeignKey("SoftwareBuildId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestProcedure", b =>
                {
                    b.HasOne("AeroLink.Domain.Programs.ProjectRecord", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestProcedureRevision", b =>
                {
                    b.HasOne("AeroLink.Domain.Verification.TestProcedure", null)
                        .WithMany()
                        .HasForeignKey("ProcedureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Verification.TestRequirementCoverage", b =>
                {
                    b.HasOne("AeroLink.Domain.Verification.TestProcedureRevision", null)
                        .WithMany()
                        .HasForeignKey("ProcedureRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AeroLink.Domain.Requirements.RequirementRevision", null)
                        .WithMany()
                        .HasForeignKey("RequirementRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AeroLink.Domain.Baselines.CandidateBaseline", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Selections");
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.ReviewCycle", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("AeroLink.Domain.ChangeControl.SystemChangeRequest", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("RequirementChanges");

                    b.Navigation("ReviewCycles");
                });
#pragma warning restore 612, 618
        }
    }
}
