using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AeroLink.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Regenerated from the integrated post-#701/#747 model. Carries this branch's complete schema delta:
    /// the software Procedure proposal vocabulary columns, the governed migration completion marker, the
    /// bounded per-baseline cutover provenance and typed migration-source tables, the isolated rollback
    /// cleanup evidence table, the referential-integrity FKs/alternate keys, and (below) the PostgreSQL
    /// integrity and immutability triggers. Never hand-merge the designer or model snapshot; they are
    /// regenerated by EF tooling.
    /// </summary>
    /// <inheritdoc />
    public partial class AddExecutionCutoverSchema : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "Cleanup",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "EnvironmentSetup",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ExpectedObservations",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "OrderedSteps",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "TestData",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ToolingAutomation",
                table: "test_procedure_changes",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddUniqueConstraint(
                name: "AK_test_procedure_revisions_ProcedureId_Id",
                table: "test_procedure_revisions",
                columns: new[] { "ProcedureId", "Id" });

            migrationBuilder.AddUniqueConstraint(
                name: "AK_baseline_events_BaselineId_Id",
                table: "baseline_events",
                columns: new[] { "BaselineId", "Id" });

            migrationBuilder.CreateTable(
                name: "baseline_execution_cutover_provenance",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    BaselineId = table.Column<Guid>(type: "uuid", nullable: false),
                    EventId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    TotalMappings = table.Column<int>(type: "integer", nullable: false),
                    CanonicalAggregateHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    EntryCount = table.Column<int>(type: "integer", nullable: false),
                    Content = table.Column<string>(type: "character varying(2000)", maxLength: 2000, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_baseline_execution_cutover_provenance", x => x.Id);
                    table.ForeignKey(
                        name: "FK_baseline_execution_cutover_provenance_baseline_events_Basel~",
                        columns: x => new { x.BaselineId, x.EventId },
                        principalTable: "baseline_events",
                        principalColumns: new[] { "BaselineId", "Id" },
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_baseline_execution_cutover_provenance_candidate_baselines_B~",
                        column: x => x.BaselineId,
                        principalTable: "candidate_baselines",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "governed_migration_completions",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    Marker = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                    Actor = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    CompletedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    TotalsJson = table.Column<string>(type: "character varying(4000)", maxLength: 4000, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_governed_migration_completions", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "rollback_cleanup_failure_evidence",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    OperationId = table.Column<Guid>(type: "uuid", nullable: false),
                    Sequence = table.Column<int>(type: "integer", nullable: false),
                    TotalKeys = table.Column<int>(type: "integer", nullable: false),
                    CanonicalAggregateHash = table.Column<string>(type: "character varying(64)", maxLength: 64, nullable: false),
                    EntryCount = table.Column<int>(type: "integer", nullable: false),
                    Content = table.Column<string>(type: "character varying(1500)", maxLength: 1500, nullable: false),
                    CreatedAt = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_rollback_cleanup_failure_evidence", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "test_procedure_migration_sources",
                columns: table => new
                {
                    Id = table.Column<Guid>(type: "uuid", nullable: false),
                    ProjectId = table.Column<Guid>(type: "uuid", nullable: false),
                    SourceCaseRevisionId = table.Column<Guid>(type: "uuid", nullable: false),
                    GeneratedProcedureArtifactId = table.Column<Guid>(type: "uuid", nullable: false),
                    GeneratedProcedureRevisionId = table.Column<Guid>(type: "uuid", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_test_procedure_migration_sources", x => x.Id);
                    table.ForeignKey(
                        name: "FK_test_procedure_migration_sources_projects_ProjectId",
                        column: x => x.ProjectId,
                        principalTable: "projects",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    // Creation order is deliberate: PostgreSQL reports the FIRST violated FK per row, so
                    // ordering artifact -> revision -> source -> composite lets each raw-SQL attack
                    // exercise its intended guard deterministically.
                    table.ForeignKey(
                        name: "FK_test_procedure_migration_sources_test_procedures_GeneratedP~",
                        column: x => x.GeneratedProcedureArtifactId,
                        principalTable: "test_procedures",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_test_procedure_migration_sources_test_procedure_revisions_G~",
                        column: x => x.GeneratedProcedureRevisionId,
                        principalTable: "test_procedure_revisions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_test_procedure_migration_sources_test_procedure_revisions_S~",
                        column: x => x.SourceCaseRevisionId,
                        principalTable: "test_procedure_revisions",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_test_procedure_migration_sources_test_procedure_revisions_~1",
                        columns: x => new { x.GeneratedProcedureArtifactId, x.GeneratedProcedureRevisionId },
                        principalTable: "test_procedure_revisions",
                        principalColumns: new[] { "ProcedureId", "Id" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_test_procedure_revisions_ProcedureId_Id",
                table: "test_procedure_revisions",
                columns: new[] { "ProcedureId", "Id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_baseline_events_BaselineId_Id",
                table: "baseline_events",
                columns: new[] { "BaselineId", "Id" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_baseline_execution_cutover_provenance_BaselineId_EventId",
                table: "baseline_execution_cutover_provenance",
                columns: new[] { "BaselineId", "EventId" });

            migrationBuilder.CreateIndex(
                name: "IX_baseline_execution_cutover_provenance_BaselineId_Sequence",
                table: "baseline_execution_cutover_provenance",
                columns: new[] { "BaselineId", "Sequence" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_baseline_execution_cutover_provenance_EventId",
                table: "baseline_execution_cutover_provenance",
                column: "EventId");

            migrationBuilder.CreateIndex(
                name: "IX_governed_migration_completions_Marker",
                table: "governed_migration_completions",
                column: "Marker",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_rollback_cleanup_failure_evidence_OperationId_Sequence",
                table: "rollback_cleanup_failure_evidence",
                columns: new[] { "OperationId", "Sequence" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_test_procedure_migration_sources_GeneratedProcedureArtifact~",
                table: "test_procedure_migration_sources",
                columns: new[] { "GeneratedProcedureArtifactId", "GeneratedProcedureRevisionId" });

            migrationBuilder.CreateIndex(
                name: "IX_test_procedure_migration_sources_GeneratedProcedureRevision~",
                table: "test_procedure_migration_sources",
                column: "GeneratedProcedureRevisionId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_test_procedure_migration_sources_ProjectId",
                table: "test_procedure_migration_sources",
                column: "ProjectId");

            migrationBuilder.CreateIndex(
                name: "IX_test_procedure_migration_sources_SourceCaseRevisionId",
                table: "test_procedure_migration_sources",
                column: "SourceCaseRevisionId",
                unique: true);

            // PostgreSQL-only triggers: ordinary foreign keys cannot express artifact kind, project ownership,
            // same-aggregate event type, or immutability. These make the controlled provenance and cleanup
            // evidence fail closed at the database boundary for raw SQL and every other persistence seam.
            migrationBuilder.Sql("""
                CREATE OR REPLACE FUNCTION aerolink_refuse_provenance_mutation() RETURNS trigger AS $$
                BEGIN
                    RAISE EXCEPTION 'Execution cutover provenance and migration sources are immutable historical evidence';
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER refuse_baseline_provenance_mutation
                    BEFORE UPDATE OR DELETE ON baseline_execution_cutover_provenance
                    FOR EACH ROW EXECUTE FUNCTION aerolink_refuse_provenance_mutation();

                CREATE TRIGGER refuse_migration_source_mutation
                    BEFORE UPDATE OR DELETE ON test_procedure_migration_sources
                    FOR EACH ROW EXECUTE FUNCTION aerolink_refuse_provenance_mutation();

                CREATE TRIGGER refuse_cleanup_evidence_mutation
                    BEFORE UPDATE OR DELETE ON rollback_cleanup_failure_evidence
                    FOR EACH ROW EXECUTE FUNCTION aerolink_refuse_provenance_mutation();

                CREATE OR REPLACE FUNCTION aerolink_enforce_provenance_event_kind() RETURNS trigger AS $$
                DECLARE
                    event_type text;
                BEGIN
                    SELECT e."EventType" INTO event_type
                    FROM baseline_events e
                    WHERE e."Id" = NEW."EventId";
                    -- Existence and same-baseline linkage are the composite foreign key's job; the trigger
                    -- only enforces the event TYPE on an event that exists.
                    IF event_type IS NOT NULL AND event_type <> 'ExecutionCutoverManifestMigrated' THEN
                        RAISE EXCEPTION 'Execution cutover provenance must reference an ExecutionCutoverManifestMigrated event of the same baseline';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER enforce_provenance_event_kind
                    BEFORE INSERT OR UPDATE ON baseline_execution_cutover_provenance
                    FOR EACH ROW EXECUTE FUNCTION aerolink_enforce_provenance_event_kind();

                CREATE OR REPLACE FUNCTION aerolink_enforce_migration_source_integrity() RETURNS trigger AS $$
                DECLARE
                    source_kind text;
                    source_level text;
                    source_project uuid;
                    generated_kind text;
                    generated_project uuid;
                BEGIN
                    SELECT p."ArtifactKind", p."Level", p."ProjectId"
                    INTO source_kind, source_level, source_project
                    FROM test_procedure_revisions r
                    JOIN test_procedures p ON p."Id" = r."ProcedureId"
                    WHERE r."Id" = NEW."SourceCaseRevisionId";
                    -- Existence is the foreign keys' job; the trigger only enforces semantics on rows that
                    -- exist, so a missing identity is reported by its intended FK rather than masked here.
                    IF source_kind IS NOT NULL
                        AND (source_kind <> 'Case'
                        OR source_level = 'System'
                        OR source_project <> NEW."ProjectId") THEN
                        RAISE EXCEPTION 'Migration source Case revision must be a software Case in the stated project';
                    END IF;
                    SELECT p."ArtifactKind", p."ProjectId"
                    INTO generated_kind, generated_project
                    FROM test_procedures p
                    WHERE p."Id" = NEW."GeneratedProcedureArtifactId";
                    IF generated_kind IS NOT NULL
                        AND (generated_kind <> 'Procedure'
                        OR generated_project <> NEW."ProjectId") THEN
                        RAISE EXCEPTION 'Migration generated artifact must be a Procedure in the stated project';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                CREATE TRIGGER enforce_migration_source_integrity
                    BEFORE INSERT OR UPDATE ON test_procedure_migration_sources
                    FOR EACH ROW EXECUTE FUNCTION aerolink_enforce_migration_source_integrity();
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                DROP TRIGGER IF EXISTS enforce_migration_source_integrity ON test_procedure_migration_sources;
                DROP TRIGGER IF EXISTS refuse_migration_source_mutation ON test_procedure_migration_sources;
                DROP TRIGGER IF EXISTS refuse_cleanup_evidence_mutation ON rollback_cleanup_failure_evidence;
                DROP TRIGGER IF EXISTS enforce_provenance_event_kind ON baseline_execution_cutover_provenance;
                DROP TRIGGER IF EXISTS refuse_baseline_provenance_mutation ON baseline_execution_cutover_provenance;
                DROP FUNCTION IF EXISTS aerolink_enforce_migration_source_integrity();
                DROP FUNCTION IF EXISTS aerolink_enforce_provenance_event_kind();
                DROP FUNCTION IF EXISTS aerolink_refuse_provenance_mutation();
                """);

            migrationBuilder.DropTable(
                name: "baseline_execution_cutover_provenance");

            migrationBuilder.DropTable(
                name: "governed_migration_completions");

            migrationBuilder.DropTable(
                name: "rollback_cleanup_failure_evidence");

            migrationBuilder.DropTable(
                name: "test_procedure_migration_sources");

            migrationBuilder.DropUniqueConstraint(
                name: "AK_test_procedure_revisions_ProcedureId_Id",
                table: "test_procedure_revisions");

            migrationBuilder.DropIndex(
                name: "IX_test_procedure_revisions_ProcedureId_Id",
                table: "test_procedure_revisions");

            migrationBuilder.DropUniqueConstraint(
                name: "AK_baseline_events_BaselineId_Id",
                table: "baseline_events");

            migrationBuilder.DropIndex(
                name: "IX_baseline_events_BaselineId_Id",
                table: "baseline_events");

            migrationBuilder.DropColumn(
                name: "Cleanup",
                table: "test_procedure_changes");

            migrationBuilder.DropColumn(
                name: "EnvironmentSetup",
                table: "test_procedure_changes");

            migrationBuilder.DropColumn(
                name: "ExpectedObservations",
                table: "test_procedure_changes");

            migrationBuilder.DropColumn(
                name: "OrderedSteps",
                table: "test_procedure_changes");

            migrationBuilder.DropColumn(
                name: "TestData",
                table: "test_procedure_changes");

            migrationBuilder.DropColumn(
                name: "ToolingAutomation",
                table: "test_procedure_changes");
        }
    }
}
